import { computeItineraryNumberOfDays } from '@/helper/itineraryDaysHelper';
import { ItineraryRoute } from '@/types/itinerary.type';

const balticFynCircle14Route: ItineraryRoute = {
  metaTitle: '14-Day Heiligenhafen Route | Boat4You',
  metaDesc: '14-day itinerary from Heiligenhafen.',
  id: 'baltic-fyn-circle-14-days',
  startingPoint: 'Heiligenhafen',
  otherPoints: ['Svendborg', 'Faaborg', 'Sonderborg'],
  cardImage: {
    src: '/images/itinerary/germany/baltic-germany-photos/heiligenhafen.webp',
    alt: 'German Baltic & Danish Isles',
  },
  gallery: [],
  routeDays: [
    {
      id: 'baltic-fyn-circle-14-days-day-1',
      routeFrom: 'Heiligenhafen',
      routeTo: 'Burgtiefe (Fehmarn)',
      day: 1,
      mapPin: { desktop: { left: 86.8, top: 84.1 }, mobile: { left: 86.8, top: 84.1 } },
      description: 'Day 1: Heiligenhafen to Burgtiefe (Fehmarn).',
      gallery: [{ src: '/images/itinerary/germany/baltic-germany-photos/fehmarn.webp', alt: 'Burgtiefe (Fehmarn)' }],
    },
    {
      id: 'baltic-fyn-circle-14-days-day-2',
      routeFrom: 'Burgtiefe (Fehmarn)',
      routeTo: 'Bagenkop',
      day: 2,
      mapPin: { desktop: { left: 61.0, top: 48.4 }, mobile: { left: 61.0, top: 48.4 } },
      description: 'Day 2: Burgtiefe (Fehmarn) to Bagenkop.',
      gallery: [],
    },
    {
      id: 'baltic-fyn-circle-14-days-day-3',
      routeFrom: 'Bagenkop',
      routeTo: 'Marstal',
      day: 3,
      mapPin: { desktop: { left: 53.5, top: 38.3 }, mobile: { left: 53.5, top: 38.3 } },
      description: 'Day 3: Bagenkop to Marstal.',
      gallery: [{ src: '/images/itinerary/germany/baltic-germany-photos/marstal-harbour.webp', alt: 'Marstal' }],
    },
    {
      id: 'baltic-fyn-circle-14-days-day-4',
      routeFrom: 'Marstal',
      routeTo: 'Svendborg',
      day: 4,
      mapPin: { desktop: { left: 58.0, top: 17.2 }, mobile: { left: 58.0, top: 17.2 } },
      description: 'Day 4: Marstal to Svendborg.',
      gallery: [{ src: '/images/itinerary/germany/baltic-germany-photos/svendborg.webp', alt: 'Svendborg' }],
    },
    {
      id: 'baltic-fyn-circle-14-days-day-5',
      routeFrom: 'Svendborg',
      routeTo: 'Faaborg',
      day: 5,
      mapPin: { desktop: { left: 40.2, top: 13.2 }, mobile: { left: 40.2, top: 13.2 } },
      description: 'Day 5: Svendborg to Faaborg.',
      gallery: [],
    },
    {
      id: 'baltic-fyn-circle-14-days-day-6',
      routeFrom: 'Faaborg',
      routeTo: 'Aeroskobing',
      day: 6,
      mapPin: { desktop: { left: 48.3, top: 34.5 }, mobile: { left: 48.3, top: 34.5 } },
      description: 'Day 6: Faaborg to Aeroskobing.',
      gallery: [{ src: '/images/itinerary/germany/baltic-germany-photos/aeroskobing.webp', alt: 'Aeroskobing' }],
    },
    {
      id: 'baltic-fyn-circle-14-days-day-7',
      routeFrom: 'Aeroskobing',
      routeTo: 'Dyvig',
      day: 7,
      mapPin: { desktop: { left: 13.2, top: 25.8 }, mobile: { left: 13.2, top: 25.8 } },
      description: 'Day 7: Aeroskobing to Dyvig.',
      gallery: [],
    },
    {
      id: 'baltic-fyn-circle-14-days-day-8',
      routeFrom: 'Dyvig',
      routeTo: 'Sonderborg',
      day: 8,
      mapPin: { desktop: { left: 17.7, top: 31.9 }, mobile: { left: 17.7, top: 31.9 } },
      description: 'Day 8: Dyvig to Sonderborg.',
      gallery: [{ src: '/images/itinerary/germany/baltic-germany-photos/sonderborg-castle.webp', alt: 'Sonderborg' }],
    },
    {
      id: 'baltic-fyn-circle-14-days-day-9',
      routeFrom: 'Sonderborg',
      routeTo: 'Aeroskobing',
      day: 9,
      mapPin: { desktop: { left: 48.3, top: 34.5 }, mobile: { left: 48.3, top: 34.5 } },
      description: 'Day 9: Sonderborg to Aeroskobing.',
      gallery: [{ src: '/images/itinerary/germany/baltic-germany-photos/aeroskobing.webp', alt: 'Aeroskobing' }],
    },
    {
      id: 'baltic-fyn-circle-14-days-day-10',
      routeFrom: 'Aeroskobing',
      routeTo: 'Marstal',
      day: 10,
      mapPin: { desktop: { left: 53.5, top: 38.3 }, mobile: { left: 53.5, top: 38.3 } },
      description: 'Day 10: Aeroskobing to Marstal.',
      gallery: [{ src: '/images/itinerary/germany/baltic-germany-photos/marstal-harbour.webp', alt: 'Marstal' }],
    },
    {
      id: 'baltic-fyn-circle-14-days-day-11',
      routeFrom: 'Marstal',
      routeTo: 'Bagenkop',
      day: 11,
      mapPin: { desktop: { left: 61.0, top: 48.4 }, mobile: { left: 61.0, top: 48.4 } },
      description: 'Day 11: Marstal to Bagenkop.',
      gallery: [],
    },
    {
      id: 'baltic-fyn-circle-14-days-day-12',
      routeFrom: 'Bagenkop',
      routeTo: 'Burgtiefe (Fehmarn)',
      day: 12,
      mapPin: { desktop: { left: 86.8, top: 84.1 }, mobile: { left: 86.8, top: 84.1 } },
      description: 'Day 12: Bagenkop to Burgtiefe (Fehmarn).',
      gallery: [{ src: '/images/itinerary/germany/baltic-germany-photos/fehmarn.webp', alt: 'Burgtiefe (Fehmarn)' }],
    },
    {
      id: 'baltic-fyn-circle-14-days-day-13',
      routeFrom: 'Burgtiefe (Fehmarn)',
      routeTo: 'Grossenbrode',
      day: 13,
      mapPin: { desktop: { left: 81.1, top: 85.9 }, mobile: { left: 81.1, top: 85.9 } },
      description: 'Day 13: Burgtiefe (Fehmarn) to Grossenbrode.',
      gallery: [],
    },
    {
      id: 'baltic-fyn-circle-14-days-day-14',
      routeFrom: 'Grossenbrode',
      routeTo: 'Heiligenhafen',
      day: 14,
      mapPin: { desktop: { left: 75.9, top: 86.8 }, mobile: { left: 75.9, top: 86.8 } },
      description: 'Day 14: Grossenbrode to Heiligenhafen.',
      gallery: [{ src: '/images/itinerary/germany/baltic-germany-photos/heiligenhafen.webp', alt: 'Heiligenhafen' }],
    },
  ],
  map: {
    desktop: {
      image: {
        src: '/images/itinerary/germany/baltic-germany-maps/baltic-fyn-circle-14-days-map.webp',
        alt: 'German Baltic & Danish Isles route map',
      },
      width: 1350,
      height: 1111,
    },
    mobile: {
      image: {
        src: '/images/itinerary/germany/baltic-germany-maps/baltic-fyn-circle-14-days-map.webp',
        alt: 'German Baltic & Danish Isles route map',
      },
      width: 1350,
      height: 1111,
    },
  },
};

export default computeItineraryNumberOfDays(balticFynCircle14Route);
