import { computeItineraryNumberOfDays } from '@/helper/itineraryDaysHelper';
import { ItineraryRoute } from '@/types/itinerary.type';

const bviFullLoop14Route: ItineraryRoute = {
  metaTitle: '14-Day Tortola (Road Town) Route | Boat4You',
  metaDesc: 'Two-week itinerary from Tortola (Road Town).',
  id: 'bvi-full-loop-14-days',
  startingPoint: 'Tortola (Road Town)',
  otherPoints: ['Anegada', 'Cane Garden Bay', 'Cooper Island'],
  cardImage: { src: '/images/itinerary/caribbeans/bvi-itinerary/itinerary-card.webp', alt: '14-day route' },
  gallery: [],
  routeDays: [
    {
      id: 'bvi-full-loop-14-days-day-1',
      routeFrom: 'Tortola (Road Town)',
      routeTo: 'Norman Island',
      day: 1,
      mapPin: { desktop: { left: 39.1, top: 86.8 }, mobile: { left: 39.1, top: 86.8 } },
      description: 'Day 1: Tortola (Road Town) to Norman Island.',
      gallery: [],
    },
    {
      id: 'bvi-full-loop-14-days-day-2',
      routeFrom: 'Norman Island',
      routeTo: 'Peter Island',
      day: 2,
      mapPin: { desktop: { left: 46.8, top: 79.0 }, mobile: { left: 46.8, top: 79.0 } },
      description: 'Day 2: Norman Island to Peter Island.',
      gallery: [],
    },
    {
      id: 'bvi-full-loop-14-days-day-3',
      routeFrom: 'Peter Island',
      routeTo: 'Cooper Island',
      day: 3,
      mapPin: { desktop: { left: 55.4, top: 76.1 }, mobile: { left: 55.4, top: 76.1 } },
      description: 'Day 3: Peter Island to Cooper Island.',
      gallery: [],
    },
    {
      id: 'bvi-full-loop-14-days-day-4',
      routeFrom: 'Cooper Island',
      routeTo: 'The Baths (Virgin Gorda)',
      day: 4,
      mapPin: { desktop: { left: 72.4, top: 67.8 }, mobile: { left: 72.4, top: 67.8 } },
      description: 'Day 4: Cooper Island to The Baths (Virgin Gorda).',
      gallery: [],
    },
    {
      id: 'bvi-full-loop-14-days-day-5',
      routeFrom: 'The Baths (Virgin Gorda)',
      routeTo: 'North Sound (Leverick Bay)',
      day: 5,
      mapPin: { desktop: { left: 86.8, top: 54.9 }, mobile: { left: 86.8, top: 54.9 } },
      description: 'Day 5: The Baths (Virgin Gorda) to North Sound (Leverick Bay).',
      gallery: [],
    },
    {
      id: 'bvi-full-loop-14-days-day-6',
      routeFrom: 'North Sound (Leverick Bay)',
      routeTo: 'Anegada',
      day: 6,
      mapPin: { desktop: { left: 82.3, top: 13.2 }, mobile: { left: 82.3, top: 13.2 } },
      description: 'Day 6: North Sound (Leverick Bay) to Anegada.',
      gallery: [],
    },
    {
      id: 'bvi-full-loop-14-days-day-7',
      routeFrom: 'Anegada',
      routeTo: 'North Sound (Leverick Bay)',
      day: 7,
      mapPin: { desktop: { left: 86.8, top: 54.9 }, mobile: { left: 86.8, top: 54.9 } },
      description: 'Day 7: Anegada to North Sound (Leverick Bay).',
      gallery: [],
    },
    {
      id: 'bvi-full-loop-14-days-day-8',
      routeFrom: 'North Sound (Leverick Bay)',
      routeTo: 'Scrub Island',
      day: 8,
      mapPin: { desktop: { left: 55.1, top: 57.1 }, mobile: { left: 55.1, top: 57.1 } },
      description: 'Day 8: North Sound (Leverick Bay) to Scrub Island.',
      gallery: [],
    },
    {
      id: 'bvi-full-loop-14-days-day-9',
      routeFrom: 'Scrub Island',
      routeTo: 'Cane Garden Bay',
      day: 9,
      mapPin: { desktop: { left: 30.3, top: 68.0 }, mobile: { left: 30.3, top: 68.0 } },
      description: 'Day 9: Scrub Island to Cane Garden Bay.',
      gallery: [],
    },
    {
      id: 'bvi-full-loop-14-days-day-10',
      routeFrom: 'Cane Garden Bay',
      routeTo: 'Jost Van Dyke',
      day: 10,
      mapPin: { desktop: { left: 13.2, top: 64.1 }, mobile: { left: 13.2, top: 64.1 } },
      description: 'Day 10: Cane Garden Bay to Jost Van Dyke.',
      gallery: [],
    },
    {
      id: 'bvi-full-loop-14-days-day-11',
      routeFrom: 'Jost Van Dyke',
      routeTo: 'Cane Garden Bay',
      day: 11,
      mapPin: { desktop: { left: 30.3, top: 68.0 }, mobile: { left: 30.3, top: 68.0 } },
      description: 'Day 11: Jost Van Dyke to Cane Garden Bay.',
      gallery: [],
    },
    {
      id: 'bvi-full-loop-14-days-day-12',
      routeFrom: 'Cane Garden Bay',
      routeTo: 'Norman Island',
      day: 12,
      mapPin: { desktop: { left: 39.1, top: 86.8 }, mobile: { left: 39.1, top: 86.8 } },
      description: 'Day 12: Cane Garden Bay to Norman Island.',
      gallery: [],
    },
    {
      id: 'bvi-full-loop-14-days-day-13',
      routeFrom: 'Norman Island',
      routeTo: 'Peter Island',
      day: 13,
      mapPin: { desktop: { left: 46.8, top: 79.0 }, mobile: { left: 46.8, top: 79.0 } },
      description: 'Day 13: Norman Island to Peter Island.',
      gallery: [],
    },
    {
      id: 'bvi-full-loop-14-days-day-14',
      routeFrom: 'Peter Island',
      routeTo: 'Tortola (Road Town)',
      day: 14,
      mapPin: { desktop: { left: 34.7, top: 69.2 }, mobile: { left: 34.7, top: 69.2 } },
      description: 'Day 14: Peter Island to Tortola (Road Town).',
      gallery: [],
    },
  ],
  map: {
    desktop: {
      image: { src: '/images/itinerary/caribbeans/bvi-maps/bvi-full-loop-14-days-map.webp', alt: 'Route map' },
      width: 1350,
      height: 1508,
    },
    mobile: {
      image: { src: '/images/itinerary/caribbeans/bvi-maps/bvi-full-loop-14-days-map.webp', alt: 'Route map' },
      width: 1350,
      height: 1508,
    },
  },
};

export default computeItineraryNumberOfDays(bviFullLoop14Route);
