import { computeItineraryNumberOfDays } from '@/helper/itineraryDaysHelper';
import { ItineraryRoute } from '@/types/itinerary.type';

const brittanyIslands14Route: ItineraryRoute = {
  metaTitle: '14-Day Le Crouesty Route | Boat4You',
  metaDesc: '14-day itinerary from Le Crouesty.',
  id: 'brittany-islands-14-days',
  startingPoint: 'Le Crouesty',
  otherPoints: ['Ile de Groix', 'Belle-Ile (Le Palais)', 'La Trinite-sur-Mer'],
  cardImage: { src: '/images/destinations/france.webp', alt: 'Brittany & Atlantic' },
  gallery: [],
  routeDays: [
    {
      id: 'brittany-islands-14-days-day-1',
      routeFrom: 'Le Crouesty',
      routeTo: 'Vannes',
      day: 1,
      mapPin: { desktop: { left: 86.8, top: 29.6 }, mobile: { left: 86.8, top: 29.6 } },
      description: 'Day 1: Le Crouesty to Vannes.',
      gallery: [],
    },
    {
      id: 'brittany-islands-14-days-day-2',
      routeFrom: 'Vannes',
      routeTo: 'Ile aux Moines',
      day: 2,
      mapPin: { desktop: { left: 77.1, top: 40.4 }, mobile: { left: 77.1, top: 40.4 } },
      description: 'Day 2: Vannes to Ile aux Moines.',
      gallery: [],
    },
    {
      id: 'brittany-islands-14-days-day-3',
      routeFrom: 'Ile aux Moines',
      routeTo: 'La Trinite-sur-Mer',
      day: 3,
      mapPin: { desktop: { left: 58.2, top: 42.4 }, mobile: { left: 58.2, top: 42.4 } },
      description: 'Day 3: Ile aux Moines to La Trinite-sur-Mer.',
      gallery: [],
    },
    {
      id: 'brittany-islands-14-days-day-4',
      routeFrom: 'La Trinite-sur-Mer',
      routeTo: 'Houat',
      day: 4,
      mapPin: { desktop: { left: 66.0, top: 77.7 }, mobile: { left: 66.0, top: 77.7 } },
      description: 'Day 4: La Trinite-sur-Mer to Houat.',
      gallery: [],
    },
    {
      id: 'brittany-islands-14-days-day-5',
      routeFrom: 'Houat',
      routeTo: 'Hoedic',
      day: 5,
      mapPin: { desktop: { left: 74.2, top: 86.8 }, mobile: { left: 74.2, top: 86.8 } },
      description: 'Day 5: Houat to Hoedic.',
      gallery: [],
    },
    {
      id: 'brittany-islands-14-days-day-6',
      routeFrom: 'Hoedic',
      routeTo: 'Belle-Ile (Le Palais)',
      day: 6,
      mapPin: { desktop: { left: 45.0, top: 85.3 }, mobile: { left: 45.0, top: 85.3 } },
      description: 'Day 6: Hoedic to Belle-Ile (Le Palais).',
      gallery: [],
    },
    {
      id: 'brittany-islands-14-days-day-7',
      routeFrom: 'Belle-Ile (Le Palais)',
      routeTo: 'Sauzon',
      day: 7,
      mapPin: { desktop: { left: 37.9, top: 81.0 }, mobile: { left: 37.9, top: 81.0 } },
      description: 'Day 7: Belle-Ile (Le Palais) to Sauzon.',
      gallery: [],
    },
    {
      id: 'brittany-islands-14-days-day-8',
      routeFrom: 'Sauzon',
      routeTo: 'Ile de Groix',
      day: 8,
      mapPin: { desktop: { left: 13.2, top: 31.4 }, mobile: { left: 13.2, top: 31.4 } },
      description: 'Day 8: Sauzon to Ile de Groix.',
      gallery: [],
    },
    {
      id: 'brittany-islands-14-days-day-9',
      routeFrom: 'Ile de Groix',
      routeTo: 'Lorient',
      day: 9,
      mapPin: { desktop: { left: 22.3, top: 13.2 }, mobile: { left: 22.3, top: 13.2 } },
      description: 'Day 9: Ile de Groix to Lorient.',
      gallery: [],
    },
    {
      id: 'brittany-islands-14-days-day-10',
      routeFrom: 'Lorient',
      routeTo: 'Ile de Groix',
      day: 10,
      mapPin: { desktop: { left: 13.2, top: 31.4 }, mobile: { left: 13.2, top: 31.4 } },
      description: 'Day 10: Lorient to Ile de Groix.',
      gallery: [],
    },
    {
      id: 'brittany-islands-14-days-day-11',
      routeFrom: 'Ile de Groix',
      routeTo: 'Belle-Ile (Le Palais)',
      day: 11,
      mapPin: { desktop: { left: 45.0, top: 85.3 }, mobile: { left: 45.0, top: 85.3 } },
      description: 'Day 11: Ile de Groix to Belle-Ile (Le Palais).',
      gallery: [],
    },
    {
      id: 'brittany-islands-14-days-day-12',
      routeFrom: 'Belle-Ile (Le Palais)',
      routeTo: 'Houat',
      day: 12,
      mapPin: { desktop: { left: 66.0, top: 77.7 }, mobile: { left: 66.0, top: 77.7 } },
      description: 'Day 12: Belle-Ile (Le Palais) to Houat.',
      gallery: [],
    },
    {
      id: 'brittany-islands-14-days-day-13',
      routeFrom: 'Houat',
      routeTo: 'Le Crouesty',
      day: 13,
      mapPin: { desktop: { left: 72.4, top: 50.2 }, mobile: { left: 72.4, top: 50.2 } },
      description: 'Day 13: Houat to Le Crouesty.',
      gallery: [],
    },
    {
      id: 'brittany-islands-14-days-day-14',
      routeFrom: 'Le Crouesty',
      routeTo: 'Le Crouesty',
      day: 14,
      mapPin: { desktop: { left: 72.4, top: 50.2 }, mobile: { left: 72.4, top: 50.2 } },
      description: 'Day 14: Le Crouesty to Le Crouesty.',
      gallery: [],
    },
  ],
  map: {
    desktop: {
      image: {
        src: '/images/itinerary/france/atlantic-france-maps/brittany-islands-14-days-map.webp',
        alt: 'Brittany & Atlantic route map',
      },
      width: 1350,
      height: 1173,
    },
    mobile: {
      image: {
        src: '/images/itinerary/france/atlantic-france-maps/brittany-islands-14-days-map.webp',
        alt: 'Brittany & Atlantic route map',
      },
      width: 1350,
      height: 1173,
    },
  },
};

export default computeItineraryNumberOfDays(brittanyIslands14Route);
