import { computeItineraryNumberOfDays } from '@/helper/itineraryDaysHelper';
import { ItineraryRoute } from '@/types/itinerary.type';

const andamanExplorer14Route: ItineraryRoute = {
  metaTitle: '14-Day Yacht Haven (Phuket) Route | Boat4You',
  metaDesc: '14-day itinerary from Yacht Haven (Phuket).',
  id: 'andaman-explorer-14-days',
  startingPoint: 'Yacht Haven (Phuket)',
  otherPoints: ['Ko Phi Phi Don', 'Ko Lanta', 'Ko Kradan'],
  cardImage: { src: '/images/itinerary/thailand/thailand-photos/thailand-andaman.webp', alt: 'Thailand (Andaman Sea)' },
  gallery: [],
  routeDays: [
    {
      id: 'andaman-explorer-14-days-day-1',
      routeFrom: 'Yacht Haven (Phuket)',
      routeTo: 'Ko Phanak',
      day: 1,
      mapPin: { desktop: { left: 24.6, top: 15.9 }, mobile: { left: 24.6, top: 15.9 } },
      description: 'Day 1: Yacht Haven (Phuket) to Ko Phanak.',
      gallery: [],
    },
    {
      id: 'andaman-explorer-14-days-day-2',
      routeFrom: 'Ko Phanak',
      routeTo: 'Ko Hong (Phang Nga)',
      day: 2,
      mapPin: { desktop: { left: 25.5, top: 13.2 }, mobile: { left: 25.5, top: 13.2 } },
      description: 'Day 2: Ko Phanak to Ko Hong (Phang Nga).',
      gallery: [
        { src: '/images/itinerary/thailand/thailand-photos/phang-nga-bay-karsts.webp', alt: 'Ko Hong (Phang Nga)' },
      ],
    },
    {
      id: 'andaman-explorer-14-days-day-3',
      routeFrom: 'Ko Hong (Phang Nga)',
      routeTo: 'Ko Yao Noi',
      day: 3,
      mapPin: { desktop: { left: 33.2, top: 22.8 }, mobile: { left: 33.2, top: 22.8 } },
      description: 'Day 3: Ko Hong (Phang Nga) to Ko Yao Noi.',
      gallery: [],
    },
    {
      id: 'andaman-explorer-14-days-day-4',
      routeFrom: 'Ko Yao Noi',
      routeTo: 'Railay (Krabi)',
      day: 4,
      mapPin: { desktop: { left: 51.7, top: 30.8 }, mobile: { left: 51.7, top: 30.8 } },
      description: 'Day 4: Ko Yao Noi to Railay (Krabi).',
      gallery: [{ src: '/images/itinerary/thailand/thailand-photos/railay-krabi.webp', alt: 'Railay (Krabi)' }],
    },
    {
      id: 'andaman-explorer-14-days-day-5',
      routeFrom: 'Railay (Krabi)',
      routeTo: 'Ko Phi Phi Don',
      day: 5,
      mapPin: { desktop: { left: 47.1, top: 52.3 }, mobile: { left: 47.1, top: 52.3 } },
      description: 'Day 5: Railay (Krabi) to Ko Phi Phi Don.',
      gallery: [],
    },
    {
      id: 'andaman-explorer-14-days-day-6',
      routeFrom: 'Ko Phi Phi Don',
      routeTo: 'Ko Phi Phi Le',
      day: 6,
      mapPin: { desktop: { left: 46.1, top: 57.4 }, mobile: { left: 46.1, top: 57.4 } },
      description: 'Day 6: Ko Phi Phi Don to Ko Phi Phi Le.',
      gallery: [],
    },
    {
      id: 'andaman-explorer-14-days-day-7',
      routeFrom: 'Ko Phi Phi Le',
      routeTo: 'Ko Lanta',
      day: 7,
      mapPin: { desktop: { left: 67.3, top: 59.7 }, mobile: { left: 67.3, top: 59.7 } },
      description: 'Day 7: Ko Phi Phi Le to Ko Lanta.',
      gallery: [{ src: '/images/itinerary/thailand/thailand-photos/ko-lanta.webp', alt: 'Ko Lanta' }],
    },
    {
      id: 'andaman-explorer-14-days-day-8',
      routeFrom: 'Ko Lanta',
      routeTo: 'Ko Muk',
      day: 8,
      mapPin: { desktop: { left: 86.8, top: 82.5 }, mobile: { left: 86.8, top: 82.5 } },
      description: 'Day 8: Ko Lanta to Ko Muk.',
      gallery: [],
    },
    {
      id: 'andaman-explorer-14-days-day-9',
      routeFrom: 'Ko Muk',
      routeTo: 'Ko Kradan',
      day: 9,
      mapPin: { desktop: { left: 84.3, top: 86.8 }, mobile: { left: 84.3, top: 86.8 } },
      description: 'Day 9: Ko Muk to Ko Kradan.',
      gallery: [],
    },
    {
      id: 'andaman-explorer-14-days-day-10',
      routeFrom: 'Ko Kradan',
      routeTo: 'Ko Lanta',
      day: 10,
      mapPin: { desktop: { left: 67.3, top: 59.7 }, mobile: { left: 67.3, top: 59.7 } },
      description: 'Day 10: Ko Kradan to Ko Lanta.',
      gallery: [{ src: '/images/itinerary/thailand/thailand-photos/ko-lanta.webp', alt: 'Ko Lanta' }],
    },
    {
      id: 'andaman-explorer-14-days-day-11',
      routeFrom: 'Ko Lanta',
      routeTo: 'Ko Phi Phi Don',
      day: 11,
      mapPin: { desktop: { left: 47.1, top: 52.3 }, mobile: { left: 47.1, top: 52.3 } },
      description: 'Day 11: Ko Lanta to Ko Phi Phi Don.',
      gallery: [],
    },
    {
      id: 'andaman-explorer-14-days-day-12',
      routeFrom: 'Ko Phi Phi Don',
      routeTo: 'Ko Rang Yai',
      day: 12,
      mapPin: { desktop: { left: 21.6, top: 34.8 }, mobile: { left: 21.6, top: 34.8 } },
      description: 'Day 12: Ko Phi Phi Don to Ko Rang Yai.',
      gallery: [],
    },
    {
      id: 'andaman-explorer-14-days-day-13',
      routeFrom: 'Ko Rang Yai',
      routeTo: 'Ko Yao Noi',
      day: 13,
      mapPin: { desktop: { left: 33.2, top: 22.8 }, mobile: { left: 33.2, top: 22.8 } },
      description: 'Day 13: Ko Rang Yai to Ko Yao Noi.',
      gallery: [],
    },
    {
      id: 'andaman-explorer-14-days-day-14',
      routeFrom: 'Ko Yao Noi',
      routeTo: 'Yacht Haven (Phuket)',
      day: 14,
      mapPin: { desktop: { left: 13.2, top: 17.5 }, mobile: { left: 13.2, top: 17.5 } },
      description: 'Day 14: Ko Yao Noi to Yacht Haven (Phuket).',
      gallery: [],
    },
  ],
  map: {
    desktop: {
      image: {
        src: '/images/itinerary/thailand/thailand-maps/andaman-explorer-14-days-map.webp',
        alt: 'Thailand (Andaman Sea) route map',
      },
      width: 1350,
      height: 1324,
    },
    mobile: {
      image: {
        src: '/images/itinerary/thailand/thailand-maps/andaman-explorer-14-days-map.webp',
        alt: 'Thailand (Andaman Sea) route map',
      },
      width: 1350,
      height: 1324,
    },
  },
};

export default computeItineraryNumberOfDays(andamanExplorer14Route);
