import { computeItineraryNumberOfDays } from '@/helper/itineraryDaysHelper';
import { ItineraryRoute } from '@/types/itinerary.type';

const lycianCoast14Route: ItineraryRoute = {
  metaTitle: '14-Day Göcek Route | Boat4You',
  metaDesc: 'Two-week itinerary from Göcek.',
  id: 'lycian-coast-14-days',
  startingPoint: 'Göcek',
  otherPoints: ['Butterfly Valley', 'Coldwater Bay', 'Ekincik'],
  cardImage: { src: '/images/itinerary/turkey/bodrum-itinerary/routes/bodrum-didim.webp', alt: '14-day route' },
  gallery: [],
  routeDays: [
    {
      id: 'lycian-coast-14-days-day-1',
      routeFrom: 'Göcek',
      routeTo: 'Sarsala Bay',
      day: 1,
      mapPin: { desktop: { left: 61.1, top: 34.6 }, mobile: { left: 61.1, top: 34.6 } },
      description: 'Day 1: Göcek to Sarsala Bay.',
      gallery: [{ src: '/images/itinerary/turkey/destinations/sarsala-bay.webp', alt: 'Sarsala Bay' }],
    },
    {
      id: 'lycian-coast-14-days-day-2',
      routeFrom: 'Sarsala Bay',
      routeTo: 'Kapı Creek',
      day: 2,
      mapPin: { desktop: { left: 53.2, top: 63.1 }, mobile: { left: 53.2, top: 63.1 } },
      description: 'Day 2: Sarsala Bay to Kapı Creek.',
      gallery: [],
    },
    {
      id: 'lycian-coast-14-days-day-3',
      routeFrom: 'Kapı Creek',
      routeTo: 'Ruin Bay',
      day: 3,
      mapPin: { desktop: { left: 58.6, top: 34.7 }, mobile: { left: 58.6, top: 34.7 } },
      description: 'Day 3: Kapı Creek to Ruin Bay.',
      gallery: [{ src: '/images/itinerary/turkey/destinations/ruin-bay.webp', alt: 'Ruin Bay' }],
    },
    {
      id: 'lycian-coast-14-days-day-4',
      routeFrom: 'Ruin Bay',
      routeTo: 'Wall Bay',
      day: 4,
      mapPin: { desktop: { left: 67.1, top: 38.1 }, mobile: { left: 67.1, top: 38.1 } },
      description: 'Day 4: Ruin Bay to Wall Bay.',
      gallery: [{ src: '/images/itinerary/turkey/destinations/wall-bay.webp', alt: 'Wall Bay' }],
    },
    {
      id: 'lycian-coast-14-days-day-5',
      routeFrom: 'Wall Bay',
      routeTo: 'Fethiye',
      day: 5,
      mapPin: { desktop: { left: 85.2, top: 64.0 }, mobile: { left: 85.2, top: 64.0 } },
      description: 'Day 5: Wall Bay to Fethiye.',
      gallery: [{ src: '/images/itinerary/turkey/destinations/fethiye.webp', alt: 'Fethiye' }],
    },
    {
      id: 'lycian-coast-14-days-day-6',
      routeFrom: 'Fethiye',
      routeTo: 'Gemiler Island',
      day: 6,
      mapPin: { desktop: { left: 77.7, top: 80.3 }, mobile: { left: 77.7, top: 80.3 } },
      description: 'Day 6: Fethiye to Gemiler Island.',
      gallery: [{ src: '/images/itinerary/turkey/destinations/gemiler-island.webp', alt: 'Gemiler Island' }],
    },
    {
      id: 'lycian-coast-14-days-day-7',
      routeFrom: 'Gemiler Island',
      routeTo: 'Ölüdeniz',
      day: 7,
      mapPin: { desktop: { left: 86.8, top: 81.7 }, mobile: { left: 86.8, top: 81.7 } },
      description: 'Day 7: Gemiler Island to Ölüdeniz.',
      gallery: [],
    },
    {
      id: 'lycian-coast-14-days-day-8',
      routeFrom: 'Ölüdeniz',
      routeTo: 'Butterfly Valley',
      day: 8,
      mapPin: { desktop: { left: 84.5, top: 86.8 }, mobile: { left: 84.5, top: 86.8 } },
      description: 'Day 8: Ölüdeniz to Butterfly Valley.',
      gallery: [{ src: '/images/itinerary/turkey/destinations/butterfly-valley.webp', alt: 'Butterfly Valley' }],
    },
    {
      id: 'lycian-coast-14-days-day-9',
      routeFrom: 'Butterfly Valley',
      routeTo: 'Coldwater Bay',
      day: 9,
      mapPin: { desktop: { left: 44.9, top: 40.8 }, mobile: { left: 44.9, top: 40.8 } },
      description: 'Day 9: Butterfly Valley to Coldwater Bay.',
      gallery: [],
    },
    {
      id: 'lycian-coast-14-days-day-10',
      routeFrom: 'Coldwater Bay',
      routeTo: 'Gemiler Island',
      day: 10,
      mapPin: { desktop: { left: 77.7, top: 80.3 }, mobile: { left: 77.7, top: 80.3 } },
      description: 'Day 10: Coldwater Bay to Gemiler Island.',
      gallery: [{ src: '/images/itinerary/turkey/destinations/gemiler-island.webp', alt: 'Gemiler Island' }],
    },
    {
      id: 'lycian-coast-14-days-day-11',
      routeFrom: 'Gemiler Island',
      routeTo: 'Ekincik',
      day: 11,
      mapPin: { desktop: { left: 13.2, top: 13.2 }, mobile: { left: 13.2, top: 13.2 } },
      description: 'Day 11: Gemiler Island to Ekincik.',
      gallery: [{ src: '/images/itinerary/turkey/destinations/ekincik.webp', alt: 'Ekincik' }],
    },
    {
      id: 'lycian-coast-14-days-day-12',
      routeFrom: 'Ekincik',
      routeTo: 'Kızıkuyruk Koyu',
      day: 12,
      mapPin: { desktop: { left: 54.7, top: 77.6 }, mobile: { left: 54.7, top: 77.6 } },
      description: 'Day 12: Ekincik to Kızıkuyruk Koyu.',
      gallery: [],
    },
    {
      id: 'lycian-coast-14-days-day-13',
      routeFrom: 'Kızıkuyruk Koyu',
      routeTo: 'Sarsala Bay',
      day: 13,
      mapPin: { desktop: { left: 61.1, top: 34.6 }, mobile: { left: 61.1, top: 34.6 } },
      description: 'Day 13: Kızıkuyruk Koyu to Sarsala Bay.',
      gallery: [{ src: '/images/itinerary/turkey/destinations/sarsala-bay.webp', alt: 'Sarsala Bay' }],
    },
    {
      id: 'lycian-coast-14-days-day-14',
      routeFrom: 'Sarsala Bay',
      routeTo: 'Göcek',
      day: 14,
      mapPin: { desktop: { left: 63.3, top: 32.3 }, mobile: { left: 63.3, top: 32.3 } },
      description: 'Day 14: Sarsala Bay to Göcek.',
      gallery: [{ src: '/images/itinerary/turkey/destinations/gocek.webp', alt: 'Göcek' }],
    },
  ],
  map: {
    desktop: {
      image: { src: '/images/itinerary/turkey/gocek-maps/lycian-coast-14-days-map.webp', alt: 'Route map' },
      width: 1350,
      height: 831,
    },
    mobile: {
      image: { src: '/images/itinerary/turkey/gocek-maps/lycian-coast-14-days-map.webp', alt: 'Route map' },
      width: 1350,
      height: 831,
    },
  },
};

export default computeItineraryNumberOfDays(lycianCoast14Route);
