import { computeItineraryNumberOfDays } from '@/helper/itineraryDaysHelper';
import { ItineraryRoute } from '@/types/itinerary.type';

const montenegroAdriatic14Route: ItineraryRoute = {
  metaTitle: '14-Day Porto Montenegro (Tivat) Route | Boat4You',
  metaDesc: '14-day itinerary from Porto Montenegro (Tivat).',
  id: 'montenegro-adriatic-14-days',
  startingPoint: 'Porto Montenegro (Tivat)',
  otherPoints: ['Kotor', 'Sveti Stefan', 'Bar'],
  cardImage: { src: '/images/itinerary/montenegro/montenegro-photos/porto-montenegro-tivat.webp', alt: 'Montenegro' },
  gallery: [],
  routeDays: [
    {
      id: 'montenegro-adriatic-14-days-day-1',
      routeFrom: 'Porto Montenegro (Tivat)',
      routeTo: 'Rose',
      day: 1,
      mapPin: { desktop: { left: 17.2, top: 25.0 }, mobile: { left: 17.2, top: 25.0 } },
      description: 'Day 1: Porto Montenegro (Tivat) to Rose.',
      gallery: [],
    },
    {
      id: 'montenegro-adriatic-14-days-day-2',
      routeFrom: 'Rose',
      routeTo: 'Herceg Novi',
      day: 2,
      mapPin: { desktop: { left: 13.2, top: 19.9 }, mobile: { left: 13.2, top: 19.9 } },
      description: 'Day 2: Rose to Herceg Novi.',
      gallery: [{ src: '/images/itinerary/montenegro/montenegro-photos/herceg-novi.webp', alt: 'Herceg Novi' }],
    },
    {
      id: 'montenegro-adriatic-14-days-day-3',
      routeFrom: 'Herceg Novi',
      routeTo: 'Perast',
      day: 3,
      mapPin: { desktop: { left: 34.8, top: 13.2 }, mobile: { left: 34.8, top: 13.2 } },
      description: 'Day 3: Herceg Novi to Perast.',
      gallery: [
        { src: '/images/itinerary/montenegro/montenegro-photos/perast-our-lady-of-the-rocks.webp', alt: 'Perast' },
      ],
    },
    {
      id: 'montenegro-adriatic-14-days-day-4',
      routeFrom: 'Perast',
      routeTo: 'Kotor',
      day: 4,
      mapPin: { desktop: { left: 44.1, top: 25.0 }, mobile: { left: 44.1, top: 25.0 } },
      description: 'Day 4: Perast to Kotor.',
      gallery: [{ src: '/images/itinerary/montenegro/montenegro-photos/kotor-bay.webp', alt: 'Kotor' }],
    },
    {
      id: 'montenegro-adriatic-14-days-day-5',
      routeFrom: 'Kotor',
      routeTo: 'Lustica Bay',
      day: 5,
      mapPin: { desktop: { left: 26.9, top: 32.9 }, mobile: { left: 26.9, top: 32.9 } },
      description: 'Day 5: Kotor to Lustica Bay.',
      gallery: [],
    },
    {
      id: 'montenegro-adriatic-14-days-day-6',
      routeFrom: 'Lustica Bay',
      routeTo: 'Zanjice',
      day: 6,
      mapPin: { desktop: { left: 17.0, top: 30.3 }, mobile: { left: 17.0, top: 30.3 } },
      description: 'Day 6: Lustica Bay to Zanjice.',
      gallery: [],
    },
    {
      id: 'montenegro-adriatic-14-days-day-7',
      routeFrom: 'Zanjice',
      routeTo: 'Budva',
      day: 7,
      mapPin: { desktop: { left: 53.1, top: 52.8 }, mobile: { left: 53.1, top: 52.8 } },
      description: 'Day 7: Zanjice to Budva.',
      gallery: [{ src: '/images/itinerary/montenegro/montenegro-photos/budva-old-town.webp', alt: 'Budva' }],
    },
    {
      id: 'montenegro-adriatic-14-days-day-8',
      routeFrom: 'Budva',
      routeTo: 'Sveti Stefan',
      day: 8,
      mapPin: { desktop: { left: 60.3, top: 57.0 }, mobile: { left: 60.3, top: 57.0 } },
      description: 'Day 8: Budva to Sveti Stefan.',
      gallery: [{ src: '/images/itinerary/montenegro/montenegro-photos/sveti-stefan.webp', alt: 'Sveti Stefan' }],
    },
    {
      id: 'montenegro-adriatic-14-days-day-9',
      routeFrom: 'Sveti Stefan',
      routeTo: 'Petrovac',
      day: 9,
      mapPin: { desktop: { left: 67.0, top: 66.6 }, mobile: { left: 67.0, top: 66.6 } },
      description: 'Day 9: Sveti Stefan to Petrovac.',
      gallery: [],
    },
    {
      id: 'montenegro-adriatic-14-days-day-10',
      routeFrom: 'Petrovac',
      routeTo: 'Bar',
      day: 10,
      mapPin: { desktop: { left: 86.8, top: 86.8 }, mobile: { left: 86.8, top: 86.8 } },
      description: 'Day 10: Petrovac to Bar.',
      gallery: [],
    },
    {
      id: 'montenegro-adriatic-14-days-day-11',
      routeFrom: 'Bar',
      routeTo: 'Petrovac',
      day: 11,
      mapPin: { desktop: { left: 67.0, top: 66.6 }, mobile: { left: 67.0, top: 66.6 } },
      description: 'Day 11: Bar to Petrovac.',
      gallery: [],
    },
    {
      id: 'montenegro-adriatic-14-days-day-12',
      routeFrom: 'Petrovac',
      routeTo: 'Budva',
      day: 12,
      mapPin: { desktop: { left: 53.1, top: 52.8 }, mobile: { left: 53.1, top: 52.8 } },
      description: 'Day 12: Petrovac to Budva.',
      gallery: [{ src: '/images/itinerary/montenegro/montenegro-photos/budva-old-town.webp', alt: 'Budva' }],
    },
    {
      id: 'montenegro-adriatic-14-days-day-13',
      routeFrom: 'Budva',
      routeTo: 'Bigova',
      day: 13,
      mapPin: { desktop: { left: 35.3, top: 38.2 }, mobile: { left: 35.3, top: 38.2 } },
      description: 'Day 13: Budva to Bigova.',
      gallery: [],
    },
    {
      id: 'montenegro-adriatic-14-days-day-14',
      routeFrom: 'Bigova',
      routeTo: 'Porto Montenegro (Tivat)',
      day: 14,
      mapPin: { desktop: { left: 33.7, top: 23.3 }, mobile: { left: 33.7, top: 23.3 } },
      description: 'Day 14: Bigova to Porto Montenegro (Tivat).',
      gallery: [
        {
          src: '/images/itinerary/montenegro/montenegro-photos/porto-montenegro-tivat.webp',
          alt: 'Porto Montenegro (Tivat)',
        },
      ],
    },
  ],
  map: {
    desktop: {
      image: {
        src: '/images/itinerary/montenegro/montenegro-maps/montenegro-adriatic-14-days-map.webp',
        alt: 'Montenegro route map',
      },
      width: 1350,
      height: 1283,
    },
    mobile: {
      image: {
        src: '/images/itinerary/montenegro/montenegro-maps/montenegro-adriatic-14-days-map.webp',
        alt: 'Montenegro route map',
      },
      width: 1350,
      height: 1283,
    },
  },
};

export default computeItineraryNumberOfDays(montenegroAdriatic14Route);
