import { computeItineraryNumberOfDays } from '@/helper/itineraryDaysHelper';
import { ItineraryRoute } from '@/types/itinerary.type';

const gokovaGulf14Route: ItineraryRoute = {
  metaTitle: '14-Day Bodrum Route | Boat4You',
  metaDesc: 'Two-week itinerary from Bodrum.',
  id: 'gokova-gulf-14-days',
  startingPoint: 'Bodrum',
  otherPoints: ['Akyaka', 'Cleopatra Island', 'Didim'],
  cardImage: { src: '/images/itinerary/turkey/bodrum-itinerary/routes/bodrum.webp', alt: '14-day route' },
  gallery: [],
  routeDays: [
    {
      id: 'gokova-gulf-14-days-day-1',
      routeFrom: 'Bodrum',
      routeTo: 'Kara Ada',
      day: 1,
      mapPin: { desktop: { left: 24.0, top: 62.9 }, mobile: { left: 24.0, top: 62.9 } },
      description: 'Day 1: Bodrum to Kara Ada.',
      gallery: [],
    },
    {
      id: 'gokova-gulf-14-days-day-2',
      routeFrom: 'Kara Ada',
      routeTo: 'Çökertme',
      day: 2,
      mapPin: { desktop: { left: 46.5, top: 63.0 }, mobile: { left: 46.5, top: 63.0 } },
      description: 'Day 2: Kara Ada to Çökertme.',
      gallery: [{ src: '/images/itinerary/turkey/destinations/cokertme.webp', alt: 'Çökertme' }],
    },
    {
      id: 'gokova-gulf-14-days-day-3',
      routeFrom: 'Çökertme',
      routeTo: 'Ören',
      day: 3,
      mapPin: { desktop: { left: 61.1, top: 59.0 }, mobile: { left: 61.1, top: 59.0 } },
      description: 'Day 3: Çökertme to Ören.',
      gallery: [{ src: '/images/itinerary/turkey/destinations/oren.webp', alt: 'Ören' }],
    },
    {
      id: 'gokova-gulf-14-days-day-4',
      routeFrom: 'Ören',
      routeTo: 'Akyaka',
      day: 4,
      mapPin: { desktop: { left: 86.8, top: 58.4 }, mobile: { left: 86.8, top: 58.4 } },
      description: 'Day 4: Ören to Akyaka.',
      gallery: [{ src: '/images/itinerary/turkey/destinations/akyaka.webp', alt: 'Akyaka' }],
    },
    {
      id: 'gokova-gulf-14-days-day-5',
      routeFrom: 'Akyaka',
      routeTo: 'Cleopatra Island',
      day: 5,
      mapPin: { desktop: { left: 68.3, top: 86.8 }, mobile: { left: 68.3, top: 86.8 } },
      description: 'Day 5: Akyaka to Cleopatra Island.',
      gallery: [{ src: '/images/itinerary/turkey/destinations/cleopatra-island.webp', alt: 'Cleopatra Island' }],
    },
    {
      id: 'gokova-gulf-14-days-day-6',
      routeFrom: 'Cleopatra Island',
      routeTo: 'Karaca',
      day: 6,
      mapPin: { desktop: { left: 75.6, top: 75.2 }, mobile: { left: 75.6, top: 75.2 } },
      description: 'Day 6: Cleopatra Island to Karaca.',
      gallery: [{ src: '/images/itinerary/turkey/destinations/karaca-island.webp', alt: 'Karaca' }],
    },
    {
      id: 'gokova-gulf-14-days-day-7',
      routeFrom: 'Karaca',
      routeTo: 'Mersincik',
      day: 7,
      mapPin: { desktop: { left: 51.7, top: 64.9 }, mobile: { left: 51.7, top: 64.9 } },
      description: 'Day 7: Karaca to Mersincik.',
      gallery: [{ src: '/images/itinerary/turkey/destinations/mersincik.webp', alt: 'Mersincik' }],
    },
    {
      id: 'gokova-gulf-14-days-day-8',
      routeFrom: 'Mersincik',
      routeTo: 'Çökertme',
      day: 8,
      mapPin: { desktop: { left: 46.5, top: 63.0 }, mobile: { left: 46.5, top: 63.0 } },
      description: 'Day 8: Mersincik to Çökertme.',
      gallery: [{ src: '/images/itinerary/turkey/destinations/cokertme.webp', alt: 'Çökertme' }],
    },
    {
      id: 'gokova-gulf-14-days-day-9',
      routeFrom: 'Çökertme',
      routeTo: 'Kara Ada',
      day: 9,
      mapPin: { desktop: { left: 24.0, top: 62.9 }, mobile: { left: 24.0, top: 62.9 } },
      description: 'Day 9: Çökertme to Kara Ada.',
      gallery: [],
    },
    {
      id: 'gokova-gulf-14-days-day-10',
      routeFrom: 'Kara Ada',
      routeTo: 'Göl Türkbükü',
      day: 10,
      mapPin: { desktop: { left: 16.9, top: 46.6 }, mobile: { left: 16.9, top: 46.6 } },
      description: 'Day 10: Kara Ada to Göl Türkbükü.',
      gallery: [],
    },
    {
      id: 'gokova-gulf-14-days-day-11',
      routeFrom: 'Göl Türkbükü',
      routeTo: 'Güllük',
      day: 11,
      mapPin: { desktop: { left: 35.8, top: 30.5 }, mobile: { left: 35.8, top: 30.5 } },
      description: 'Day 11: Göl Türkbükü to Güllük.',
      gallery: [{ src: '/images/itinerary/turkey/destinations/milas-gulluk.webp', alt: 'Güllük' }],
    },
    {
      id: 'gokova-gulf-14-days-day-12',
      routeFrom: 'Güllük',
      routeTo: 'Didim',
      day: 12,
      mapPin: { desktop: { left: 13.2, top: 13.2 }, mobile: { left: 13.2, top: 13.2 } },
      description: 'Day 12: Güllük to Didim.',
      gallery: [{ src: '/images/itinerary/turkey/destinations/didim.webp', alt: 'Didim' }],
    },
    {
      id: 'gokova-gulf-14-days-day-13',
      routeFrom: 'Didim',
      routeTo: 'Göl Türkbükü',
      day: 13,
      mapPin: { desktop: { left: 16.9, top: 46.6 }, mobile: { left: 16.9, top: 46.6 } },
      description: 'Day 13: Didim to Göl Türkbükü.',
      gallery: [],
    },
    {
      id: 'gokova-gulf-14-days-day-14',
      routeFrom: 'Göl Türkbükü',
      routeTo: 'Bodrum',
      day: 14,
      mapPin: { desktop: { left: 24.4, top: 60.2 }, mobile: { left: 24.4, top: 60.2 } },
      description: 'Day 14: Göl Türkbükü to Bodrum.',
      gallery: [{ src: '/images/itinerary/turkey/destinations/bodrum-town.webp', alt: 'Bodrum' }],
    },
  ],
  map: {
    desktop: {
      image: { src: '/images/itinerary/turkey/bodrum-maps/gokova-gulf-14-days-map.webp', alt: 'Route map' },
      width: 1350,
      height: 815,
    },
    mobile: {
      image: { src: '/images/itinerary/turkey/bodrum-maps/gokova-gulf-14-days-map.webp', alt: 'Route map' },
      width: 1350,
      height: 815,
    },
  },
};

export default computeItineraryNumberOfDays(gokovaGulf14Route);
