import { computeItineraryNumberOfDays } from '@/helper/itineraryDaysHelper';
import { ItineraryRoute } from '@/types/itinerary.type';

const sporadesGrandTour14Route: ItineraryRoute = {
  metaTitle: '14-Day Skiathos Marina Route | Boat4You',
  metaDesc: 'Two-week itinerary from Skiathos Marina.',
  id: 'sporades-grand-tour-14-days',
  startingPoint: 'Skiathos Marina',
  otherPoints: ['Agia Kiriaki', 'Alonissos', 'Koukounaries (Skiathos)'],
  cardImage: { src: '/images/itinerary/greece/skiathos-itinerary/routes/sporades.webp', alt: '14-day route' },
  gallery: [],
  routeDays: [
    {
      id: 'sporades-grand-tour-14-days-day-1',
      routeFrom: 'Skiathos Marina',
      routeTo: 'Skopelos',
      day: 1,
      mapPin: { desktop: { left: 48.8, top: 52.0 }, mobile: { left: 48.8, top: 52.0 } },
      description: 'Day 1: Skiathos Marina to Skopelos.',
      gallery: [{ src: '/images/itinerary/greece/destinations/skopelos.webp', alt: 'Skopelos' }],
    },
    {
      id: 'sporades-grand-tour-14-days-day-2',
      routeFrom: 'Skopelos',
      routeTo: 'Alonissos',
      day: 2,
      mapPin: { desktop: { left: 54.8, top: 47.3 }, mobile: { left: 54.8, top: 47.3 } },
      description: 'Day 2: Skopelos to Alonissos.',
      gallery: [{ src: '/images/itinerary/greece/destinations/alonissos.webp', alt: 'Alonissos' }],
    },
    {
      id: 'sporades-grand-tour-14-days-day-3',
      routeFrom: 'Alonissos',
      routeTo: 'Kyra Panagia',
      day: 3,
      mapPin: { desktop: { left: 64.3, top: 18.5 }, mobile: { left: 64.3, top: 18.5 } },
      description: 'Day 3: Alonissos to Kyra Panagia.',
      gallery: [{ src: '/images/itinerary/greece/destinations/kyra.webp', alt: 'Kyra Panagia' }],
    },
    {
      id: 'sporades-grand-tour-14-days-day-4',
      routeFrom: 'Kyra Panagia',
      routeTo: 'Skyros',
      day: 4,
      mapPin: { desktop: { left: 86.8, top: 86.8 }, mobile: { left: 86.8, top: 86.8 } },
      description: 'Day 4: Kyra Panagia to Skyros.',
      gallery: [{ src: '/images/itinerary/greece/destinations/skyros.webp', alt: 'Skyros' }],
    },
    {
      id: 'sporades-grand-tour-14-days-day-5',
      routeFrom: 'Skyros',
      routeTo: 'Kyra Panagia',
      day: 5,
      mapPin: { desktop: { left: 64.3, top: 18.5 }, mobile: { left: 64.3, top: 18.5 } },
      description: 'Day 5: Skyros to Kyra Panagia.',
      gallery: [{ src: '/images/itinerary/greece/destinations/kyra.webp', alt: 'Kyra Panagia' }],
    },
    {
      id: 'sporades-grand-tour-14-days-day-6',
      routeFrom: 'Kyra Panagia',
      routeTo: 'Tzortzi Bay (Alonissos)',
      day: 6,
      mapPin: { desktop: { left: 54.8, top: 47.3 }, mobile: { left: 54.8, top: 47.3 } },
      description: 'Day 6: Kyra Panagia to Tzortzi Bay (Alonissos).',
      gallery: [{ src: '/images/itinerary/greece/destinations/alonissos.webp', alt: 'Tzortzi Bay (Alonissos)' }],
    },
    {
      id: 'sporades-grand-tour-14-days-day-7',
      routeFrom: 'Tzortzi Bay (Alonissos)',
      routeTo: 'Alonissos',
      day: 7,
      mapPin: { desktop: { left: 54.8, top: 47.3 }, mobile: { left: 54.8, top: 47.3 } },
      description: 'Day 7: Tzortzi Bay (Alonissos) to Alonissos.',
      gallery: [{ src: '/images/itinerary/greece/destinations/alonissos.webp', alt: 'Alonissos' }],
    },
    {
      id: 'sporades-grand-tour-14-days-day-8',
      routeFrom: 'Alonissos',
      routeTo: 'Skopelos',
      day: 8,
      mapPin: { desktop: { left: 48.8, top: 52.0 }, mobile: { left: 48.8, top: 52.0 } },
      description: 'Day 8: Alonissos to Skopelos.',
      gallery: [{ src: '/images/itinerary/greece/destinations/skopelos.webp', alt: 'Skopelos' }],
    },
    {
      id: 'sporades-grand-tour-14-days-day-9',
      routeFrom: 'Skopelos',
      routeTo: 'Trikeri Island',
      day: 9,
      mapPin: { desktop: { left: 19.0, top: 56.5 }, mobile: { left: 19.0, top: 56.5 } },
      description: 'Day 9: Skopelos to Trikeri Island.',
      gallery: [{ src: '/images/itinerary/greece/destinations/trikeri.webp', alt: 'Trikeri Island' }],
    },
    {
      id: 'sporades-grand-tour-14-days-day-10',
      routeFrom: 'Trikeri Island',
      routeTo: 'Agia Kiriaki',
      day: 10,
      mapPin: { desktop: { left: 19.0, top: 56.6 }, mobile: { left: 19.0, top: 56.6 } },
      description: 'Day 10: Trikeri Island to Agia Kiriaki.',
      gallery: [{ src: '/images/itinerary/greece/destinations/kiriaki.webp', alt: 'Agia Kiriaki' }],
    },
    {
      id: 'sporades-grand-tour-14-days-day-11',
      routeFrom: 'Agia Kiriaki',
      routeTo: 'Volos',
      day: 11,
      mapPin: { desktop: { left: 13.2, top: 13.2 }, mobile: { left: 13.2, top: 13.2 } },
      description: 'Day 11: Agia Kiriaki to Volos.',
      gallery: [{ src: '/images/itinerary/greece/destinations/volos-town-island.webp', alt: 'Volos' }],
    },
    {
      id: 'sporades-grand-tour-14-days-day-12',
      routeFrom: 'Volos',
      routeTo: 'Trikeri Island',
      day: 12,
      mapPin: { desktop: { left: 19.0, top: 56.5 }, mobile: { left: 19.0, top: 56.5 } },
      description: 'Day 12: Volos to Trikeri Island.',
      gallery: [{ src: '/images/itinerary/greece/destinations/trikeri.webp', alt: 'Trikeri Island' }],
    },
    {
      id: 'sporades-grand-tour-14-days-day-13',
      routeFrom: 'Trikeri Island',
      routeTo: 'Koukounaries (Skiathos)',
      day: 13,
      mapPin: { desktop: { left: 35.0, top: 47.7 }, mobile: { left: 35.0, top: 47.7 } },
      description: 'Day 13: Trikeri Island to Koukounaries (Skiathos).',
      gallery: [{ src: '/images/itinerary/greece/destinations/koukounaries.webp', alt: 'Koukounaries (Skiathos)' }],
    },
    {
      id: 'sporades-grand-tour-14-days-day-14',
      routeFrom: 'Koukounaries (Skiathos)',
      routeTo: 'Skiathos Marina',
      day: 14,
      mapPin: { desktop: { left: 38.0, top: 45.7 }, mobile: { left: 38.0, top: 45.7 } },
      description: 'Day 14: Koukounaries (Skiathos) to Skiathos Marina.',
      gallery: [{ src: '/images/itinerary/greece/destinations/skiathos-town-island.webp', alt: 'Skiathos Marina' }],
    },
  ],
  map: {
    desktop: {
      image: { src: '/images/itinerary/greece/sporades-maps/sporades-grand-tour-14-days-map.webp', alt: 'Route map' },
      width: 1350,
      height: 487,
    },
    mobile: {
      image: { src: '/images/itinerary/greece/sporades-maps/sporades-grand-tour-14-days-map.webp', alt: 'Route map' },
      width: 1350,
      height: 487,
    },
  },
};

export default computeItineraryNumberOfDays(sporadesGrandTour14Route);
