import { computeItineraryNumberOfDays } from '@/helper/itineraryDaysHelper';
import { ItineraryRoute } from '@/types/itinerary.type';

const windwardTwoWeek14Route: ItineraryRoute = {
  metaTitle: '14-Day Le Marin Route | Boat4You',
  metaDesc: 'Two-week itinerary from Le Marin.',
  id: 'windward-two-week-14-days',
  startingPoint: 'Le Marin',
  otherPoints: ['Anse Couleuvre', 'Anse Dufour', 'Grande Anse d’Arlet'],
  cardImage: { src: '/images/itinerary/caribbeans/martinique-itinerary/itinerary-card.webp', alt: '14-day route' },
  gallery: [],
  routeDays: [
    {
      id: 'windward-two-week-14-days-day-1',
      routeFrom: 'Le Marin',
      routeTo: 'Sainte-Anne',
      day: 1,
      mapPin: { desktop: { left: 83.9, top: 43.3 }, mobile: { left: 83.9, top: 43.3 } },
      description: 'Day 1: Le Marin to Sainte-Anne.',
      gallery: [{ src: '/images/itinerary/caribbeans/destinations/sainte-anne.webp', alt: 'Sainte-Anne' }],
    },
    {
      id: 'windward-two-week-14-days-day-2',
      routeFrom: 'Sainte-Anne',
      routeTo: 'Grande Anse d’Arlet',
      day: 2,
      mapPin: { desktop: { left: 41.9, top: 39.4 }, mobile: { left: 41.9, top: 39.4 } },
      description: 'Day 2: Sainte-Anne to Grande Anse d’Arlet.',
      gallery: [{ src: '/images/itinerary/caribbeans/destinations/grande-anse.webp', alt: 'Grande Anse d’Arlet' }],
    },
    {
      id: 'windward-two-week-14-days-day-3',
      routeFrom: 'Grande Anse d’Arlet',
      routeTo: 'Anse Dufour',
      day: 3,
      mapPin: { desktop: { left: 42.0, top: 36.6 }, mobile: { left: 42.0, top: 36.6 } },
      description: 'Day 3: Grande Anse d’Arlet to Anse Dufour.',
      gallery: [{ src: '/images/itinerary/caribbeans/destinations/anse-dufour.webp', alt: 'Anse Dufour' }],
    },
    {
      id: 'windward-two-week-14-days-day-4',
      routeFrom: 'Anse Dufour',
      routeTo: 'Saint-Pierre',
      day: 4,
      mapPin: { desktop: { left: 23.3, top: 21.2 }, mobile: { left: 23.3, top: 21.2 } },
      description: 'Day 4: Anse Dufour to Saint-Pierre.',
      gallery: [{ src: '/images/itinerary/caribbeans/destinations/saint-pierre.webp', alt: 'Saint-Pierre' }],
    },
    {
      id: 'windward-two-week-14-days-day-5',
      routeFrom: 'Saint-Pierre',
      routeTo: 'Anse Couleuvre',
      day: 5,
      mapPin: { desktop: { left: 13.2, top: 13.2 }, mobile: { left: 13.2, top: 13.2 } },
      description: 'Day 5: Saint-Pierre to Anse Couleuvre.',
      gallery: [{ src: '/images/itinerary/caribbeans/destinations/anse-couleuvre.webp', alt: 'Anse Couleuvre' }],
    },
    {
      id: 'windward-two-week-14-days-day-6',
      routeFrom: 'Anse Couleuvre',
      routeTo: 'Saint-Pierre',
      day: 6,
      mapPin: { desktop: { left: 23.3, top: 21.2 }, mobile: { left: 23.3, top: 21.2 } },
      description: 'Day 6: Anse Couleuvre to Saint-Pierre.',
      gallery: [{ src: '/images/itinerary/caribbeans/destinations/saint-pierre.webp', alt: 'Saint-Pierre' }],
    },
    {
      id: 'windward-two-week-14-days-day-7',
      routeFrom: 'Saint-Pierre',
      routeTo: 'Grande Anse d’Arlet',
      day: 7,
      mapPin: { desktop: { left: 41.9, top: 39.4 }, mobile: { left: 41.9, top: 39.4 } },
      description: 'Day 7: Saint-Pierre to Grande Anse d’Arlet.',
      gallery: [{ src: '/images/itinerary/caribbeans/destinations/grande-anse.webp', alt: 'Grande Anse d’Arlet' }],
    },
    {
      id: 'windward-two-week-14-days-day-8',
      routeFrom: 'Grande Anse d’Arlet',
      routeTo: 'Le Marin',
      day: 8,
      mapPin: { desktop: { left: 86.8, top: 40.9 }, mobile: { left: 86.8, top: 40.9 } },
      description: 'Day 8: Grande Anse d’Arlet to Le Marin.',
      gallery: [{ src: '/images/itinerary/caribbeans/destinations/le-marin.webp', alt: 'Le Marin' }],
    },
    {
      id: 'windward-two-week-14-days-day-9',
      routeFrom: 'Le Marin',
      routeTo: 'Rodney Bay (St. Lucia)',
      day: 9,
      mapPin: { desktop: { left: 70.2, top: 70.5 }, mobile: { left: 70.2, top: 70.5 } },
      description: 'Day 9: Le Marin to Rodney Bay (St. Lucia).',
      gallery: [],
    },
    {
      id: 'windward-two-week-14-days-day-10',
      routeFrom: 'Rodney Bay (St. Lucia)',
      routeTo: 'Marigot Bay (St. Lucia)',
      day: 10,
      mapPin: { desktop: { left: 54.5, top: 78.6 }, mobile: { left: 54.5, top: 78.6 } },
      description: 'Day 10: Rodney Bay (St. Lucia) to Marigot Bay (St. Lucia).',
      gallery: [{ src: '/images/itinerary/caribbeans/destinations/marigot.webp', alt: 'Marigot Bay (St. Lucia)' }],
    },
    {
      id: 'windward-two-week-14-days-day-11',
      routeFrom: 'Marigot Bay (St. Lucia)',
      routeTo: 'Soufrière (Pitons)',
      day: 11,
      mapPin: { desktop: { left: 47.8, top: 86.8 }, mobile: { left: 47.8, top: 86.8 } },
      description: 'Day 11: Marigot Bay (St. Lucia) to Soufrière (Pitons).',
      gallery: [],
    },
    {
      id: 'windward-two-week-14-days-day-12',
      routeFrom: 'Soufrière (Pitons)',
      routeTo: 'Marigot Bay (St. Lucia)',
      day: 12,
      mapPin: { desktop: { left: 54.5, top: 78.6 }, mobile: { left: 54.5, top: 78.6 } },
      description: 'Day 12: Soufrière (Pitons) to Marigot Bay (St. Lucia).',
      gallery: [{ src: '/images/itinerary/caribbeans/destinations/marigot.webp', alt: 'Marigot Bay (St. Lucia)' }],
    },
    {
      id: 'windward-two-week-14-days-day-13',
      routeFrom: 'Marigot Bay (St. Lucia)',
      routeTo: 'Rodney Bay (St. Lucia)',
      day: 13,
      mapPin: { desktop: { left: 70.2, top: 70.5 }, mobile: { left: 70.2, top: 70.5 } },
      description: 'Day 13: Marigot Bay (St. Lucia) to Rodney Bay (St. Lucia).',
      gallery: [],
    },
    {
      id: 'windward-two-week-14-days-day-14',
      routeFrom: 'Rodney Bay (St. Lucia)',
      routeTo: 'Le Marin',
      day: 14,
      mapPin: { desktop: { left: 86.8, top: 40.9 }, mobile: { left: 86.8, top: 40.9 } },
      description: 'Day 14: Rodney Bay (St. Lucia) to Le Marin.',
      gallery: [{ src: '/images/itinerary/caribbeans/destinations/le-marin.webp', alt: 'Le Marin' }],
    },
  ],
  map: {
    desktop: {
      image: {
        src: '/images/itinerary/caribbeans/martinique-maps/windward-two-week-14-days-map.webp',
        alt: 'Route map',
      },
      width: 1350,
      height: 3905,
    },
    mobile: {
      image: {
        src: '/images/itinerary/caribbeans/martinique-maps/windward-two-week-14-days-map.webp',
        alt: 'Route map',
      },
      width: 1350,
      height: 3905,
    },
  },
};

export default computeItineraryNumberOfDays(windwardTwoWeek14Route);
