import { computeItineraryNumberOfDays } from '@/helper/itineraryDaysHelper';
import { ItineraryRoute } from '@/types/itinerary.type';

const sardiniaMaddalena14Route: ItineraryRoute = {
  metaTitle: '14-Day Olbia Route | Boat4You',
  metaDesc: 'Two-week itinerary from Olbia.',
  id: 'sardinia-maddalena-14-days',
  startingPoint: 'Olbia',
  otherPoints: ['Bonifacio', 'Caprera', 'Golfo Aranci'],
  cardImage: { src: '/images/itinerary/italy/sardinia-itinerary/routes/olbia-long.webp', alt: '14-day route' },
  gallery: [],
  routeDays: [
    {
      id: 'sardinia-maddalena-14-days-day-1',
      routeFrom: 'Olbia',
      routeTo: 'Tavolara Island',
      day: 1,
      mapPin: { desktop: { left: 86.8, top: 84.5 }, mobile: { left: 86.8, top: 84.5 } },
      description: 'Day 1: Olbia to Tavolara Island.',
      gallery: [{ src: '/images/itinerary/italy/destinations/tavolara-island.webp', alt: 'Tavolara Island' }],
    },
    {
      id: 'sardinia-maddalena-14-days-day-2',
      routeFrom: 'Tavolara Island',
      routeTo: 'Porto San Paolo',
      day: 2,
      mapPin: { desktop: { left: 78.3, top: 86.8 }, mobile: { left: 78.3, top: 86.8 } },
      description: 'Day 2: Tavolara Island to Porto San Paolo.',
      gallery: [{ src: '/images/itinerary/italy/destinations/porto-san-paolo.webp', alt: 'Porto San Paolo' }],
    },
    {
      id: 'sardinia-maddalena-14-days-day-3',
      routeFrom: 'Porto San Paolo',
      routeTo: 'Golfo Aranci',
      day: 3,
      mapPin: { desktop: { left: 75.1, top: 71.2 }, mobile: { left: 75.1, top: 71.2 } },
      description: 'Day 3: Porto San Paolo to Golfo Aranci.',
      gallery: [{ src: '/images/itinerary/italy/destinations/golfo-aranci.webp', alt: 'Golfo Aranci' }],
    },
    {
      id: 'sardinia-maddalena-14-days-day-4',
      routeFrom: 'Golfo Aranci',
      routeTo: 'Porto Rotondo',
      day: 4,
      mapPin: { desktop: { left: 64.8, top: 65.2 }, mobile: { left: 64.8, top: 65.2 } },
      description: 'Day 4: Golfo Aranci to Porto Rotondo.',
      gallery: [{ src: '/images/itinerary/italy/destinations/porto-san-paolo.webp', alt: 'Porto Rotondo' }],
    },
    {
      id: 'sardinia-maddalena-14-days-day-5',
      routeFrom: 'Porto Rotondo',
      routeTo: 'Porto Cervo',
      day: 5,
      mapPin: { desktop: { left: 63.9, top: 49.8 }, mobile: { left: 63.9, top: 49.8 } },
      description: 'Day 5: Porto Rotondo to Porto Cervo.',
      gallery: [{ src: '/images/itinerary/italy/destinations/porto-san-paolo.webp', alt: 'Porto Cervo' }],
    },
    {
      id: 'sardinia-maddalena-14-days-day-6',
      routeFrom: 'Porto Cervo',
      routeTo: 'Portisco',
      day: 6,
      mapPin: { desktop: { left: 66.2, top: 68.5 }, mobile: { left: 66.2, top: 68.5 } },
      description: 'Day 6: Porto Cervo to Portisco.',
      gallery: [{ src: '/images/itinerary/italy/destinations/portisco.webp', alt: 'Portisco' }],
    },
    {
      id: 'sardinia-maddalena-14-days-day-7',
      routeFrom: 'Portisco',
      routeTo: 'Caprera',
      day: 7,
      mapPin: { desktop: { left: 54.9, top: 39.4 }, mobile: { left: 54.9, top: 39.4 } },
      description: 'Day 7: Portisco to Caprera.',
      gallery: [{ src: '/images/itinerary/italy/destinations/caprera.webp', alt: 'Caprera' }],
    },
    {
      id: 'sardinia-maddalena-14-days-day-8',
      routeFrom: 'Caprera',
      routeTo: 'La Maddalena',
      day: 8,
      mapPin: { desktop: { left: 46.1, top: 39.0 }, mobile: { left: 46.1, top: 39.0 } },
      description: 'Day 8: Caprera to La Maddalena.',
      gallery: [{ src: '/images/itinerary/italy/destinations/la-maddalena.webp', alt: 'La Maddalena' }],
    },
    {
      id: 'sardinia-maddalena-14-days-day-9',
      routeFrom: 'La Maddalena',
      routeTo: 'Spargi',
      day: 9,
      mapPin: { desktop: { left: 36.8, top: 34.0 }, mobile: { left: 36.8, top: 34.0 } },
      description: 'Day 9: La Maddalena to Spargi.',
      gallery: [{ src: '/images/itinerary/italy/destinations/spargi.webp', alt: 'Spargi' }],
    },
    {
      id: 'sardinia-maddalena-14-days-day-10',
      routeFrom: 'Spargi',
      routeTo: 'Santa Teresa Gallura',
      day: 10,
      mapPin: { desktop: { left: 16.9, top: 34.7 }, mobile: { left: 16.9, top: 34.7 } },
      description: 'Day 10: Spargi to Santa Teresa Gallura.',
      gallery: [{ src: '/images/itinerary/italy/destinations/santa-teresa-gallura.webp', alt: 'Santa Teresa Gallura' }],
    },
    {
      id: 'sardinia-maddalena-14-days-day-11',
      routeFrom: 'Santa Teresa Gallura',
      routeTo: 'Bonifacio',
      day: 11,
      mapPin: { desktop: { left: 13.2, top: 13.2 }, mobile: { left: 13.2, top: 13.2 } },
      description: 'Day 11: Santa Teresa Gallura to Bonifacio.',
      gallery: [{ src: '/images/itinerary/italy/destinations/bonifacio.webp', alt: 'Bonifacio' }],
    },
    {
      id: 'sardinia-maddalena-14-days-day-12',
      routeFrom: 'Bonifacio',
      routeTo: 'Palau',
      day: 12,
      mapPin: { desktop: { left: 43.4, top: 43.5 }, mobile: { left: 43.4, top: 43.5 } },
      description: 'Day 12: Bonifacio to Palau.',
      gallery: [{ src: '/images/itinerary/italy/destinations/palau.webp', alt: 'Palau' }],
    },
    {
      id: 'sardinia-maddalena-14-days-day-13',
      routeFrom: 'Palau',
      routeTo: 'Tavolara Island',
      day: 13,
      mapPin: { desktop: { left: 86.8, top: 84.5 }, mobile: { left: 86.8, top: 84.5 } },
      description: 'Day 13: Palau to Tavolara Island.',
      gallery: [{ src: '/images/itinerary/italy/destinations/tavolara-island.webp', alt: 'Tavolara Island' }],
    },
    {
      id: 'sardinia-maddalena-14-days-day-14',
      routeFrom: 'Tavolara Island',
      routeTo: 'Olbia',
      day: 14,
      mapPin: { desktop: { left: 58.9, top: 80.9 }, mobile: { left: 58.9, top: 80.9 } },
      description: 'Day 14: Tavolara Island to Olbia.',
      gallery: [{ src: '/images/itinerary/italy/destinations/olbia.webp', alt: 'Olbia' }],
    },
  ],
  map: {
    desktop: {
      image: { src: '/images/itinerary/italy/sardinia-maps/sardinia-maddalena-14-days-map.webp', alt: 'Route map' },
      width: 1350,
      height: 1663,
    },
    mobile: {
      image: { src: '/images/itinerary/italy/sardinia-maps/sardinia-maddalena-14-days-map.webp', alt: 'Route map' },
      width: 1350,
      height: 1663,
    },
  },
};

export default computeItineraryNumberOfDays(sardiniaMaddalena14Route);
