import { computeItineraryNumberOfDays } from '@/helper/itineraryDaysHelper';
import { ItineraryRoute } from '@/types/itinerary.type';

const corsicaGrandTour14Route: ItineraryRoute = {
  metaTitle: '14-Day Ajaccio Route | Boat4You',
  metaDesc: '14-day itinerary from Ajaccio.',
  id: 'corsica-grand-tour-14-days',
  startingPoint: 'Ajaccio',
  otherPoints: ['Girolata', 'Bonifacio', 'Porto-Vecchio'],
  cardImage: { src: '/images/itinerary/france/corsica-photos/ajaccio.webp', alt: 'Corsica' },
  gallery: [],
  routeDays: [
    {
      id: 'corsica-grand-tour-14-days-day-1',
      routeFrom: 'Ajaccio',
      routeTo: 'Sagone',
      day: 1,
      mapPin: { desktop: { left: 29.0, top: 40.4 }, mobile: { left: 29.0, top: 40.4 } },
      description: 'Day 1: Ajaccio to Sagone.',
      gallery: [],
    },
    {
      id: 'corsica-grand-tour-14-days-day-2',
      routeFrom: 'Sagone',
      routeTo: 'Cargese',
      day: 2,
      mapPin: { desktop: { left: 18.8, top: 39.3 }, mobile: { left: 18.8, top: 39.3 } },
      description: 'Day 2: Sagone to Cargese.',
      gallery: [],
    },
    {
      id: 'corsica-grand-tour-14-days-day-3',
      routeFrom: 'Cargese',
      routeTo: 'Capo Rosso',
      day: 3,
      mapPin: { desktop: { left: 13.2, top: 33.6 }, mobile: { left: 13.2, top: 33.6 } },
      description: 'Day 3: Cargese to Capo Rosso.',
      gallery: [],
    },
    {
      id: 'corsica-grand-tour-14-days-day-4',
      routeFrom: 'Capo Rosso',
      routeTo: 'Girolata',
      day: 4,
      mapPin: { desktop: { left: 20.4, top: 26.4 }, mobile: { left: 20.4, top: 26.4 } },
      description: 'Day 4: Capo Rosso to Girolata.',
      gallery: [{ src: '/images/itinerary/france/corsica-photos/girolata.webp', alt: 'Girolata' }],
    },
    {
      id: 'corsica-grand-tour-14-days-day-5',
      routeFrom: 'Girolata',
      routeTo: 'Calvi',
      day: 5,
      mapPin: { desktop: { left: 34.9, top: 13.2 }, mobile: { left: 34.9, top: 13.2 } },
      description: 'Day 5: Girolata to Calvi.',
      gallery: [{ src: '/images/itinerary/france/corsica-photos/calvi-citadel.webp', alt: 'Calvi' }],
    },
    {
      id: 'corsica-grand-tour-14-days-day-6',
      routeFrom: 'Calvi',
      routeTo: 'Girolata',
      day: 6,
      mapPin: { desktop: { left: 20.4, top: 26.4 }, mobile: { left: 20.4, top: 26.4 } },
      description: 'Day 6: Calvi to Girolata.',
      gallery: [{ src: '/images/itinerary/france/corsica-photos/girolata.webp', alt: 'Girolata' }],
    },
    {
      id: 'corsica-grand-tour-14-days-day-7',
      routeFrom: 'Girolata',
      routeTo: 'Ajaccio',
      day: 7,
      mapPin: { desktop: { left: 33.0, top: 52.1 }, mobile: { left: 33.0, top: 52.1 } },
      description: 'Day 7: Girolata to Ajaccio.',
      gallery: [{ src: '/images/itinerary/france/corsica-photos/ajaccio.webp', alt: 'Ajaccio' }],
    },
    {
      id: 'corsica-grand-tour-14-days-day-8',
      routeFrom: 'Ajaccio',
      routeTo: 'Porto Pollo',
      day: 8,
      mapPin: { desktop: { left: 38.9, top: 64.8 }, mobile: { left: 38.9, top: 64.8 } },
      description: 'Day 8: Ajaccio to Porto Pollo.',
      gallery: [],
    },
    {
      id: 'corsica-grand-tour-14-days-day-9',
      routeFrom: 'Porto Pollo',
      routeTo: 'Campomoro',
      day: 9,
      mapPin: { desktop: { left: 40.2, top: 69.1 }, mobile: { left: 40.2, top: 69.1 } },
      description: 'Day 9: Porto Pollo to Campomoro.',
      gallery: [],
    },
    {
      id: 'corsica-grand-tour-14-days-day-10',
      routeFrom: 'Campomoro',
      routeTo: 'Bonifacio',
      day: 10,
      mapPin: { desktop: { left: 75.2, top: 83.7 }, mobile: { left: 75.2, top: 83.7 } },
      description: 'Day 10: Campomoro to Bonifacio.',
      gallery: [{ src: '/images/itinerary/france/corsica-photos/bonifacio-cliffs.webp', alt: 'Bonifacio' }],
    },
    {
      id: 'corsica-grand-tour-14-days-day-11',
      routeFrom: 'Bonifacio',
      routeTo: 'Iles Lavezzi',
      day: 11,
      mapPin: { desktop: { left: 85.0, top: 86.8 }, mobile: { left: 85.0, top: 86.8 } },
      description: 'Day 11: Bonifacio to Iles Lavezzi.',
      gallery: [{ src: '/images/itinerary/france/corsica-photos/lavezzi-islands.webp', alt: 'Iles Lavezzi' }],
    },
    {
      id: 'corsica-grand-tour-14-days-day-12',
      routeFrom: 'Iles Lavezzi',
      routeTo: 'Rondinara',
      day: 12,
      mapPin: { desktop: { left: 86.8, top: 78.8 }, mobile: { left: 86.8, top: 78.8 } },
      description: 'Day 12: Iles Lavezzi to Rondinara.',
      gallery: [],
    },
    {
      id: 'corsica-grand-tour-14-days-day-13',
      routeFrom: 'Rondinara',
      routeTo: 'Propriano',
      day: 13,
      mapPin: { desktop: { left: 49.2, top: 66.6 }, mobile: { left: 49.2, top: 66.6 } },
      description: 'Day 13: Rondinara to Propriano.',
      gallery: [{ src: '/images/itinerary/france/corsica-photos/propriano.webp', alt: 'Propriano' }],
    },
    {
      id: 'corsica-grand-tour-14-days-day-14',
      routeFrom: 'Propriano',
      routeTo: 'Ajaccio',
      day: 14,
      mapPin: { desktop: { left: 33.0, top: 52.1 }, mobile: { left: 33.0, top: 52.1 } },
      description: 'Day 14: Propriano to Ajaccio.',
      gallery: [{ src: '/images/itinerary/france/corsica-photos/ajaccio.webp', alt: 'Ajaccio' }],
    },
  ],
  map: {
    desktop: {
      image: {
        src: '/images/itinerary/france/corsica-maps/corsica-grand-tour-14-days-map.webp',
        alt: 'Corsica route map',
      },
      width: 1350,
      height: 3042,
    },
    mobile: {
      image: {
        src: '/images/itinerary/france/corsica-maps/corsica-grand-tour-14-days-map.webp',
        alt: 'Corsica route map',
      },
      width: 1350,
      height: 3042,
    },
  },
};

export default computeItineraryNumberOfDays(corsicaGrandTour14Route);
