import { computeItineraryNumberOfDays } from '@/helper/itineraryDaysHelper';
import { ItineraryRoute } from '@/types/itinerary.type';

const amalfiCilento14Route: ItineraryRoute = {
  metaTitle: '14-Day Salerno Route | Boat4You',
  metaDesc: 'Two-week itinerary from Salerno.',
  id: 'amalfi-cilento-14-days',
  startingPoint: 'Salerno',
  otherPoints: ['Acciaroli', 'Agropoli', 'Amalfi'],
  cardImage: { src: '/images/itinerary/italy/amalfi-itinerary/routes/genova.webp', alt: '14-day route' },
  gallery: [],
  routeDays: [
    {
      id: 'amalfi-cilento-14-days-day-1',
      routeFrom: 'Salerno',
      routeTo: 'Cetara',
      day: 1,
      mapPin: { desktop: { left: 55.7, top: 31.7 }, mobile: { left: 55.7, top: 31.7 } },
      description: 'Day 1: Salerno to Cetara.',
      gallery: [],
    },
    {
      id: 'amalfi-cilento-14-days-day-2',
      routeFrom: 'Cetara',
      routeTo: 'Amalfi',
      day: 2,
      mapPin: { desktop: { left: 50.3, top: 32.9 }, mobile: { left: 50.3, top: 32.9 } },
      description: 'Day 2: Cetara to Amalfi.',
      gallery: [],
    },
    {
      id: 'amalfi-cilento-14-days-day-3',
      routeFrom: 'Amalfi',
      routeTo: 'Positano',
      day: 3,
      mapPin: { desktop: { left: 44.0, top: 33.5 }, mobile: { left: 44.0, top: 33.5 } },
      description: 'Day 3: Amalfi to Positano.',
      gallery: [],
    },
    {
      id: 'amalfi-cilento-14-days-day-4',
      routeFrom: 'Positano',
      routeTo: 'Sorrento',
      day: 4,
      mapPin: { desktop: { left: 38.2, top: 33.6 }, mobile: { left: 38.2, top: 33.6 } },
      description: 'Day 4: Positano to Sorrento.',
      gallery: [],
    },
    {
      id: 'amalfi-cilento-14-days-day-5',
      routeFrom: 'Sorrento',
      routeTo: 'Naples',
      day: 5,
      mapPin: { desktop: { left: 32.4, top: 13.2 }, mobile: { left: 32.4, top: 13.2 } },
      description: 'Day 5: Sorrento to Naples.',
      gallery: [],
    },
    {
      id: 'amalfi-cilento-14-days-day-6',
      routeFrom: 'Naples',
      routeTo: 'Ischia',
      day: 6,
      mapPin: { desktop: { left: 15.0, top: 23.4 }, mobile: { left: 15.0, top: 23.4 } },
      description: 'Day 6: Naples to Ischia.',
      gallery: [],
    },
    {
      id: 'amalfi-cilento-14-days-day-7',
      routeFrom: 'Ischia',
      routeTo: 'Casamicciola Terme',
      day: 7,
      mapPin: { desktop: { left: 13.2, top: 22.9 }, mobile: { left: 13.2, top: 22.9 } },
      description: 'Day 7: Ischia to Casamicciola Terme.',
      gallery: [],
    },
    {
      id: 'amalfi-cilento-14-days-day-8',
      routeFrom: 'Casamicciola Terme',
      routeTo: 'Sorrento',
      day: 8,
      mapPin: { desktop: { left: 38.2, top: 33.6 }, mobile: { left: 38.2, top: 33.6 } },
      description: 'Day 8: Casamicciola Terme to Sorrento.',
      gallery: [],
    },
    {
      id: 'amalfi-cilento-14-days-day-9',
      routeFrom: 'Sorrento',
      routeTo: 'Amalfi',
      day: 9,
      mapPin: { desktop: { left: 50.3, top: 32.9 }, mobile: { left: 50.3, top: 32.9 } },
      description: 'Day 9: Sorrento to Amalfi.',
      gallery: [],
    },
    {
      id: 'amalfi-cilento-14-days-day-10',
      routeFrom: 'Amalfi',
      routeTo: 'Agropoli',
      day: 10,
      mapPin: { desktop: { left: 71.3, top: 58.3 }, mobile: { left: 71.3, top: 58.3 } },
      description: 'Day 10: Amalfi to Agropoli.',
      gallery: [],
    },
    {
      id: 'amalfi-cilento-14-days-day-11',
      routeFrom: 'Agropoli',
      routeTo: 'Acciaroli',
      day: 11,
      mapPin: { desktop: { left: 72.9, top: 74.0 }, mobile: { left: 72.9, top: 74.0 } },
      description: 'Day 11: Agropoli to Acciaroli.',
      gallery: [],
    },
    {
      id: 'amalfi-cilento-14-days-day-12',
      routeFrom: 'Acciaroli',
      routeTo: 'Palinuro',
      day: 12,
      mapPin: { desktop: { left: 86.8, top: 86.8 }, mobile: { left: 86.8, top: 86.8 } },
      description: 'Day 12: Acciaroli to Palinuro.',
      gallery: [],
    },
    {
      id: 'amalfi-cilento-14-days-day-13',
      routeFrom: 'Palinuro',
      routeTo: 'Agropoli',
      day: 13,
      mapPin: { desktop: { left: 71.3, top: 58.3 }, mobile: { left: 71.3, top: 58.3 } },
      description: 'Day 13: Palinuro to Agropoli.',
      gallery: [],
    },
    {
      id: 'amalfi-cilento-14-days-day-14',
      routeFrom: 'Agropoli',
      routeTo: 'Salerno',
      day: 14,
      mapPin: { desktop: { left: 59.2, top: 28.6 }, mobile: { left: 59.2, top: 28.6 } },
      description: 'Day 14: Agropoli to Salerno.',
      gallery: [],
    },
  ],
  map: {
    desktop: {
      image: { src: '/images/itinerary/italy/amalfi-maps/amalfi-cilento-14-days-map.webp', alt: 'Route map' },
      width: 1350,
      height: 1057,
    },
    mobile: {
      image: { src: '/images/itinerary/italy/amalfi-maps/amalfi-cilento-14-days-map.webp', alt: 'Route map' },
      width: 1350,
      height: 1057,
    },
  },
};

export default computeItineraryNumberOfDays(amalfiCilento14Route);
