import { computeItineraryNumberOfDays } from '@/helper/itineraryDaysHelper';
import { ItineraryRoute } from '@/types/itinerary.type';

const dutchWaters14Route: ItineraryRoute = {
  metaTitle: '14-Day Lemmer Route | Boat4You',
  metaDesc: '14-day itinerary from Lemmer.',
  id: 'dutch-waters-14-days',
  startingPoint: 'Lemmer',
  otherPoints: ['Enkhuizen', 'Muiden', 'Makkum'],
  cardImage: { src: '/images/itinerary/netherlands/netherlands-photos/lemmer.webp', alt: 'IJsselmeer & Dutch Waters' },
  gallery: [],
  routeDays: [
    {
      id: 'dutch-waters-14-days-day-1',
      routeFrom: 'Lemmer',
      routeTo: 'Stavoren',
      day: 1,
      mapPin: { desktop: { left: 48.7, top: 31.1 }, mobile: { left: 48.7, top: 31.1 } },
      description: 'Day 1: Lemmer to Stavoren.',
      gallery: [],
    },
    {
      id: 'dutch-waters-14-days-day-2',
      routeFrom: 'Stavoren',
      routeTo: 'Makkum',
      day: 2,
      mapPin: { desktop: { left: 53.1, top: 13.2 }, mobile: { left: 53.1, top: 13.2 } },
      description: 'Day 2: Stavoren to Makkum.',
      gallery: [],
    },
    {
      id: 'dutch-waters-14-days-day-3',
      routeFrom: 'Makkum',
      routeTo: 'Medemblik',
      day: 3,
      mapPin: { desktop: { left: 20.8, top: 42.2 }, mobile: { left: 20.8, top: 42.2 } },
      description: 'Day 3: Makkum to Medemblik.',
      gallery: [{ src: '/images/itinerary/netherlands/netherlands-photos/medemblik.webp', alt: 'Medemblik' }],
    },
    {
      id: 'dutch-waters-14-days-day-4',
      routeFrom: 'Medemblik',
      routeTo: 'Enkhuizen',
      day: 4,
      mapPin: { desktop: { left: 41.1, top: 49.1 }, mobile: { left: 41.1, top: 49.1 } },
      description: 'Day 4: Medemblik to Enkhuizen.',
      gallery: [{ src: '/images/itinerary/netherlands/netherlands-photos/enkhuizen-harbour.webp', alt: 'Enkhuizen' }],
    },
    {
      id: 'dutch-waters-14-days-day-5',
      routeFrom: 'Enkhuizen',
      routeTo: 'Hoorn',
      day: 5,
      mapPin: { desktop: { left: 15.8, top: 55.5 }, mobile: { left: 15.8, top: 55.5 } },
      description: 'Day 5: Enkhuizen to Hoorn.',
      gallery: [{ src: '/images/itinerary/netherlands/netherlands-photos/hoorn.webp', alt: 'Hoorn' }],
    },
    {
      id: 'dutch-waters-14-days-day-6',
      routeFrom: 'Hoorn',
      routeTo: 'Volendam',
      day: 6,
      mapPin: { desktop: { left: 16.7, top: 70.4 }, mobile: { left: 16.7, top: 70.4 } },
      description: 'Day 6: Hoorn to Volendam.',
      gallery: [{ src: '/images/itinerary/netherlands/netherlands-photos/volendam.webp', alt: 'Volendam' }],
    },
    {
      id: 'dutch-waters-14-days-day-7',
      routeFrom: 'Volendam',
      routeTo: 'Marken',
      day: 7,
      mapPin: { desktop: { left: 20.3, top: 74.1 }, mobile: { left: 20.3, top: 74.1 } },
      description: 'Day 7: Volendam to Marken.',
      gallery: [],
    },
    {
      id: 'dutch-waters-14-days-day-8',
      routeFrom: 'Marken',
      routeTo: 'Monnickendam',
      day: 8,
      mapPin: { desktop: { left: 13.2, top: 73.7 }, mobile: { left: 13.2, top: 73.7 } },
      description: 'Day 8: Marken to Monnickendam.',
      gallery: [],
    },
    {
      id: 'dutch-waters-14-days-day-9',
      routeFrom: 'Monnickendam',
      routeTo: 'Muiden',
      day: 9,
      mapPin: { desktop: { left: 16.7, top: 86.8 }, mobile: { left: 16.7, top: 86.8 } },
      description: 'Day 9: Monnickendam to Muiden.',
      gallery: [],
    },
    {
      id: 'dutch-waters-14-days-day-10',
      routeFrom: 'Muiden',
      routeTo: 'Volendam',
      day: 10,
      mapPin: { desktop: { left: 16.7, top: 70.4 }, mobile: { left: 16.7, top: 70.4 } },
      description: 'Day 10: Muiden to Volendam.',
      gallery: [{ src: '/images/itinerary/netherlands/netherlands-photos/volendam.webp', alt: 'Volendam' }],
    },
    {
      id: 'dutch-waters-14-days-day-11',
      routeFrom: 'Volendam',
      routeTo: 'Enkhuizen',
      day: 11,
      mapPin: { desktop: { left: 41.1, top: 49.1 }, mobile: { left: 41.1, top: 49.1 } },
      description: 'Day 11: Volendam to Enkhuizen.',
      gallery: [{ src: '/images/itinerary/netherlands/netherlands-photos/enkhuizen-harbour.webp', alt: 'Enkhuizen' }],
    },
    {
      id: 'dutch-waters-14-days-day-12',
      routeFrom: 'Enkhuizen',
      routeTo: 'Urk',
      day: 12,
      mapPin: { desktop: { left: 74.7, top: 53.3 }, mobile: { left: 74.7, top: 53.3 } },
      description: 'Day 12: Enkhuizen to Urk.',
      gallery: [],
    },
    {
      id: 'dutch-waters-14-days-day-13',
      routeFrom: 'Urk',
      routeTo: 'Lemmer',
      day: 13,
      mapPin: { desktop: { left: 86.8, top: 34.6 }, mobile: { left: 86.8, top: 34.6 } },
      description: 'Day 13: Urk to Lemmer.',
      gallery: [{ src: '/images/itinerary/netherlands/netherlands-photos/lemmer.webp', alt: 'Lemmer' }],
    },
    {
      id: 'dutch-waters-14-days-day-14',
      routeFrom: 'Lemmer',
      routeTo: 'Lemmer',
      day: 14,
      mapPin: { desktop: { left: 86.8, top: 34.6 }, mobile: { left: 86.8, top: 34.6 } },
      description: 'Day 14: Lemmer to Lemmer.',
      gallery: [{ src: '/images/itinerary/netherlands/netherlands-photos/lemmer.webp', alt: 'Lemmer' }],
    },
  ],
  map: {
    desktop: {
      image: {
        src: '/images/itinerary/netherlands/netherlands-maps/dutch-waters-14-days-map.webp',
        alt: 'IJsselmeer & Dutch Waters route map',
      },
      width: 1350,
      height: 2393,
    },
    mobile: {
      image: {
        src: '/images/itinerary/netherlands/netherlands-maps/dutch-waters-14-days-map.webp',
        alt: 'IJsselmeer & Dutch Waters route map',
      },
      width: 1350,
      height: 2393,
    },
  },
};

export default computeItineraryNumberOfDays(dutchWaters14Route);
