import { computeItineraryNumberOfDays } from '@/helper/itineraryDaysHelper';
import { ItineraryRoute } from '@/types/itinerary.type';

const aeolianFullCircle14Route: ItineraryRoute = {
  metaTitle: '14-Day Portorosa Route | Boat4You',
  metaDesc: 'Two-week itinerary from Portorosa.',
  id: 'aeolian-full-circle-14-days',
  startingPoint: 'Portorosa',
  otherPoints: ['Cefalù', 'Filicudi Porto', 'Lipari'],
  cardImage: { src: '/images/itinerary/italy/sicily-itinerary/routes/capo-dorlando.webp', alt: '14-day route' },
  gallery: [],
  routeDays: [
    {
      id: 'aeolian-full-circle-14-days-day-1',
      routeFrom: 'Portorosa',
      routeTo: 'Vulcano Porto',
      day: 1,
      mapPin: { desktop: { left: 70.0, top: 50.9 }, mobile: { left: 70.0, top: 50.9 } },
      description: 'Day 1: Portorosa to Vulcano Porto.',
      gallery: [],
    },
    {
      id: 'aeolian-full-circle-14-days-day-2',
      routeFrom: 'Vulcano Porto',
      routeTo: 'Lipari',
      day: 2,
      mapPin: { desktop: { left: 69.7, top: 45.2 }, mobile: { left: 69.7, top: 45.2 } },
      description: 'Day 2: Vulcano Porto to Lipari.',
      gallery: [],
    },
    {
      id: 'aeolian-full-circle-14-days-day-3',
      routeFrom: 'Lipari',
      routeTo: 'Salina',
      day: 3,
      mapPin: { desktop: { left: 66.3, top: 34.4 }, mobile: { left: 66.3, top: 34.4 } },
      description: 'Day 3: Lipari to Salina.',
      gallery: [],
    },
    {
      id: 'aeolian-full-circle-14-days-day-4',
      routeFrom: 'Salina',
      routeTo: 'Filicudi Porto',
      day: 4,
      mapPin: { desktop: { left: 56.6, top: 34.3 }, mobile: { left: 56.6, top: 34.3 } },
      description: 'Day 4: Salina to Filicudi Porto.',
      gallery: [],
    },
    {
      id: 'aeolian-full-circle-14-days-day-5',
      routeFrom: 'Filicudi Porto',
      routeTo: 'Salina',
      day: 5,
      mapPin: { desktop: { left: 66.3, top: 34.4 }, mobile: { left: 66.3, top: 34.4 } },
      description: 'Day 5: Filicudi Porto to Salina.',
      gallery: [],
    },
    {
      id: 'aeolian-full-circle-14-days-day-6',
      routeFrom: 'Salina',
      routeTo: 'Panarea',
      day: 6,
      mapPin: { desktop: { left: 73.9, top: 28.4 }, mobile: { left: 73.9, top: 28.4 } },
      description: 'Day 6: Salina to Panarea.',
      gallery: [],
    },
    {
      id: 'aeolian-full-circle-14-days-day-7',
      routeFrom: 'Panarea',
      routeTo: 'Stromboli',
      day: 7,
      mapPin: { desktop: { left: 78.8, top: 13.2 }, mobile: { left: 78.8, top: 13.2 } },
      description: 'Day 7: Panarea to Stromboli.',
      gallery: [],
    },
    {
      id: 'aeolian-full-circle-14-days-day-8',
      routeFrom: 'Stromboli',
      routeTo: 'Panarea',
      day: 8,
      mapPin: { desktop: { left: 73.9, top: 28.4 }, mobile: { left: 73.9, top: 28.4 } },
      description: 'Day 8: Stromboli to Panarea.',
      gallery: [],
    },
    {
      id: 'aeolian-full-circle-14-days-day-9',
      routeFrom: 'Panarea',
      routeTo: 'Lipari',
      day: 9,
      mapPin: { desktop: { left: 69.7, top: 45.2 }, mobile: { left: 69.7, top: 45.2 } },
      description: 'Day 9: Panarea to Lipari.',
      gallery: [],
    },
    {
      id: 'aeolian-full-circle-14-days-day-10',
      routeFrom: 'Lipari',
      routeTo: 'Vulcano Porto',
      day: 10,
      mapPin: { desktop: { left: 70.0, top: 50.9 }, mobile: { left: 70.0, top: 50.9 } },
      description: 'Day 10: Lipari to Vulcano Porto.',
      gallery: [],
    },
    {
      id: 'aeolian-full-circle-14-days-day-11',
      routeFrom: 'Vulcano Porto',
      routeTo: 'Cefalù',
      day: 11,
      mapPin: { desktop: { left: 36.7, top: 86.8 }, mobile: { left: 36.7, top: 86.8 } },
      description: 'Day 11: Vulcano Porto to Cefalù.',
      gallery: [],
    },
    {
      id: 'aeolian-full-circle-14-days-day-12',
      routeFrom: 'Cefalù',
      routeTo: 'Palermo',
      day: 12,
      mapPin: { desktop: { left: 13.2, top: 79.3 }, mobile: { left: 13.2, top: 79.3 } },
      description: 'Day 12: Cefalù to Palermo.',
      gallery: [],
    },
    {
      id: 'aeolian-full-circle-14-days-day-13',
      routeFrom: 'Palermo',
      routeTo: 'Cefalù',
      day: 13,
      mapPin: { desktop: { left: 36.7, top: 86.8 }, mobile: { left: 36.7, top: 86.8 } },
      description: 'Day 13: Palermo to Cefalù.',
      gallery: [],
    },
    {
      id: 'aeolian-full-circle-14-days-day-14',
      routeFrom: 'Cefalù',
      routeTo: 'Portorosa',
      day: 14,
      mapPin: { desktop: { left: 86.8, top: 82.2 }, mobile: { left: 86.8, top: 82.2 } },
      description: 'Day 14: Cefalù to Portorosa.',
      gallery: [],
    },
  ],
  map: {
    desktop: {
      image: { src: '/images/itinerary/italy/sicily-maps/aeolian-full-circle-14-days-map.webp', alt: 'Route map' },
      width: 1350,
      height: 625,
    },
    mobile: {
      image: { src: '/images/itinerary/italy/sicily-maps/aeolian-full-circle-14-days-map.webp', alt: 'Route map' },
      width: 1350,
      height: 625,
    },
  },
};

export default computeItineraryNumberOfDays(aeolianFullCircle14Route);
