export enum CountryIsoEnum {
  AF = 'AF',
  AL = 'AL',
  DZ = 'DZ',
  AS = 'AS',
  AD = 'AD',
  AO = 'AO',
  AI = 'AI',
  AQ = 'AQ',
  AG = 'AG',
  AR = 'AR',
  AM = 'AM',
  AW = 'AW',
  AU = 'AU',
  AT = 'AT',
  AZ = 'AZ',
  BS = 'BS',
  BH = 'BH',
  BD = 'BD',
  BB = 'BB',
  BY = 'BY',
  BE = 'BE',
  BZ = 'BZ',
  BJ = 'BJ',
  BM = 'BM',
  BT = 'BT',
  BO = 'BO',
  BQ = 'BQ',
  BA = 'BA',
  BW = 'BW',
  BV = 'BV',
  BR = 'BR',
  IO = 'IO',
  BN = 'BN',
  BG = 'BG',
  BF = 'BF',
  BI = 'BI',
  CV = 'CV',
  KH = 'KH',
  CM = 'CM',
  CA = 'CA',
  KY = 'KY',
  CF = 'CF',
  TD = 'TD',
  CL = 'CL',
  CN = 'CN',
  CX = 'CX',
  CC = 'CC',
  CO = 'CO',
  KM = 'KM',
  CD = 'CD',
  CG = 'CG',
  CK = 'CK',
  CR = 'CR',
  HR = 'HR',
  CU = 'CU',
  CW = 'CW',
  CY = 'CY',
  CZ = 'CZ',
  CI = 'CI',
  DK = 'DK',
  DJ = 'DJ',
  DM = 'DM',
  DO = 'DO',
  EC = 'EC',
  EG = 'EG',
  SV = 'SV',
  GQ = 'GQ',
  ER = 'ER',
  EE = 'EE',
  SZ = 'SZ',
  ET = 'ET',
  FK = 'FK',
  FO = 'FO',
  FJ = 'FJ',
  FI = 'FI',
  FR = 'FR',
  GF = 'GF',
  PF = 'PF',
  TF = 'TF',
  GA = 'GA',
  GM = 'GM',
  GE = 'GE',
  DE = 'DE',
  GH = 'GH',
  GI = 'GI',
  GR = 'GR',
  GL = 'GL',
  GD = 'GD',
  GP = 'GP',
  GU = 'GU',
  GT = 'GT',
  GG = 'GG',
  GN = 'GN',
  GW = 'GW',
  GY = 'GY',
  HT = 'HT',
  HM = 'HM',
  VA = 'VA',
  HN = 'HN',
  HK = 'HK',
  HU = 'HU',
  IS = 'IS',
  IN = 'IN',
  ID = 'ID',
  IR = 'IR',
  IQ = 'IQ',
  IE = 'IE',
  IM = 'IM',
  IL = 'IL',
  IT = 'IT',
  JM = 'JM',
  JP = 'JP',
  JE = 'JE',
  JO = 'JO',
  KZ = 'KZ',
  KE = 'KE',
  KI = 'KI',
  KP = 'KP',
  KR = 'KR',
  KW = 'KW',
  KG = 'KG',
  LA = 'LA',
  LV = 'LV',
  LB = 'LB',
  LS = 'LS',
  LR = 'LR',
  LY = 'LY',
  LI = 'LI',
  LT = 'LT',
  LU = 'LU',
  MO = 'MO',
  MG = 'MG',
  MW = 'MW',
  MY = 'MY',
  MV = 'MV',
  ML = 'ML',
  MT = 'MT',
  MH = 'MH',
  MQ = 'MQ',
  MR = 'MR',
  MU = 'MU',
  YT = 'YT',
  MX = 'MX',
  FM = 'FM',
  MD = 'MD',
  MC = 'MC',
  MN = 'MN',
  ME = 'ME',
  MS = 'MS',
  MA = 'MA',
  MZ = 'MZ',
  MM = 'MM',
  NA = 'NA',
  NR = 'NR',
  NP = 'NP',
  NL = 'NL',
  NC = 'NC',
  NZ = 'NZ',
  NI = 'NI',
  NE = 'NE',
  NG = 'NG',
  NU = 'NU',
  NF = 'NF',
  MK = 'MK',
  MP = 'MP',
  NO = 'NO',
  OM = 'OM',
  PK = 'PK',
  PW = 'PW',
  PS = 'PS',
  PA = 'PA',
  PG = 'PG',
  PY = 'PY',
  PE = 'PE',
  PH = 'PH',
  PN = 'PN',
  PL = 'PL',
  PT = 'PT',
  PR = 'PR',
  QA = 'QA',
  RO = 'RO',
  RU = 'RU',
  RW = 'RW',
  RE = 'RE',
  BL = 'BL',
  SH = 'SH',
  KN = 'KN',
  LC = 'LC',
  MF = 'MF',
  PM = 'PM',
  VC = 'VC',
  WS = 'WS',
  SM = 'SM',
  ST = 'ST',
  SA = 'SA',
  SN = 'SN',
  RS = 'RS',
  SC = 'SC',
  SL = 'SL',
  SG = 'SG',
  SX = 'SX',
  SK = 'SK',
  SI = 'SI',
  SB = 'SB',
  SO = 'SO',
  ZA = 'ZA',
  GS = 'GS',
  SS = 'SS',
  ES = 'ES',
  LK = 'LK',
  SD = 'SD',
  SR = 'SR',
  SJ = 'SJ',
  SE = 'SE',
  CH = 'CH',
  SY = 'SY',
  TW = 'TW',
  TJ = 'TJ',
  TZ = 'TZ',
  TH = 'TH',
  TL = 'TL',
  TG = 'TG',
  TK = 'TK',
  TO = 'TO',
  TT = 'TT',
  TN = 'TN',
  TM = 'TM',
  TC = 'TC',
  TV = 'TV',
  TR = 'TR',
  UG = 'UG',
  UA = 'UA',
  AE = 'AE',
  GB = 'GB',
  UM = 'UM',
  US = 'US',
  UY = 'UY',
  UZ = 'UZ',
  VU = 'VU',
  VE = 'VE',
  VN = 'VN',
  VG = 'VG',
  VI = 'VI',
  WF = 'WF',
  EH = 'EH',
  YE = 'YE',
  ZM = 'ZM',
  ZW = 'ZW',
  AX = 'AX',
}
export const COUNTRY_NAME_MAP: Record<CountryIsoEnum, string> = {
  [CountryIsoEnum.AF]: 'Afghanistan',
  [CountryIsoEnum.AL]: 'Albania',
  [CountryIsoEnum.DZ]: 'Algeria',
  [CountryIsoEnum.AS]: 'American Samoa',
  [CountryIsoEnum.AD]: 'Andorra',
  [CountryIsoEnum.AO]: 'Angola',
  [CountryIsoEnum.AI]: 'Anguilla',
  [CountryIsoEnum.AQ]: 'Antarctica',
  [CountryIsoEnum.AG]: 'Antigua and Barbuda',
  [CountryIsoEnum.AR]: 'Argentina',
  [CountryIsoEnum.AM]: 'Armenia',
  [CountryIsoEnum.AW]: 'Aruba',
  [CountryIsoEnum.AU]: 'Australia',
  [CountryIsoEnum.AT]: 'Austria',
  [CountryIsoEnum.AZ]: 'Azerbaijan',
  [CountryIsoEnum.BS]: 'Bahamas',
  [CountryIsoEnum.BH]: 'Bahrain',
  [CountryIsoEnum.BD]: 'Bangladesh',
  [CountryIsoEnum.BB]: 'Barbados',
  [CountryIsoEnum.BY]: 'Belarus',
  [CountryIsoEnum.BE]: 'Belgium',
  [CountryIsoEnum.BZ]: 'Belize',
  [CountryIsoEnum.BJ]: 'Benin',
  [CountryIsoEnum.BM]: 'Bermuda',
  [CountryIsoEnum.BT]: 'Bhutan',
  [CountryIsoEnum.BO]: 'Bolivia',
  [CountryIsoEnum.BQ]: 'Caribbean Netherlands',
  [CountryIsoEnum.BA]: 'Bosnia and Herzegovina',
  [CountryIsoEnum.BW]: 'Botswana',
  [CountryIsoEnum.BV]: 'Bouvet Island',
  [CountryIsoEnum.BR]: 'Brazil',
  [CountryIsoEnum.IO]: 'British Indian Ocean Territory',
  [CountryIsoEnum.BN]: 'Brunei Darussalam',
  [CountryIsoEnum.BG]: 'Bulgaria',
  [CountryIsoEnum.BF]: 'Burkina Faso',
  [CountryIsoEnum.BI]: 'Burundi',
  [CountryIsoEnum.CV]: 'Cabo Verde',
  [CountryIsoEnum.KH]: 'Cambodia',
  [CountryIsoEnum.CM]: 'Cameroon',
  [CountryIsoEnum.CA]: 'Canada',
  [CountryIsoEnum.KY]: 'Cayman Islands',
  [CountryIsoEnum.CF]: 'Central African Republic',
  [CountryIsoEnum.TD]: 'Chad',
  [CountryIsoEnum.CL]: 'Chile',
  [CountryIsoEnum.CN]: 'China',
  [CountryIsoEnum.CX]: 'Christmas Island',
  [CountryIsoEnum.CC]: 'Cocos (Keeling) Islands',
  [CountryIsoEnum.CO]: 'Colombia',
  [CountryIsoEnum.KM]: 'Comoros',
  [CountryIsoEnum.CD]: 'Democratic Republic of the Congo',
  [CountryIsoEnum.CG]: 'Congo',
  [CountryIsoEnum.CK]: 'Cook Islands',
  [CountryIsoEnum.CR]: 'Costa Rica',
  [CountryIsoEnum.HR]: 'Croatia',
  [CountryIsoEnum.CU]: 'Cuba',
  [CountryIsoEnum.CW]: 'Curaçao',
  [CountryIsoEnum.CY]: 'Cyprus',
  [CountryIsoEnum.CZ]: 'Czechia',
  [CountryIsoEnum.CI]: "Côte d'Ivoire",
  [CountryIsoEnum.DK]: 'Denmark',
  [CountryIsoEnum.DJ]: 'Djibouti',
  [CountryIsoEnum.DM]: 'Dominica',
  [CountryIsoEnum.DO]: 'Dominican Republic',
  [CountryIsoEnum.EC]: 'Ecuador',
  [CountryIsoEnum.EG]: 'Egypt',
  [CountryIsoEnum.SV]: 'El Salvador',
  [CountryIsoEnum.GQ]: 'Equatorial Guinea',
  [CountryIsoEnum.ER]: 'Eritrea',
  [CountryIsoEnum.EE]: 'Estonia',
  [CountryIsoEnum.SZ]: 'Eswatini',
  [CountryIsoEnum.ET]: 'Ethiopia',
  [CountryIsoEnum.FK]: 'Falkland Islands',
  [CountryIsoEnum.FO]: 'Faroe Islands',
  [CountryIsoEnum.FJ]: 'Fiji',
  [CountryIsoEnum.FI]: 'Finland',
  [CountryIsoEnum.FR]: 'France',
  [CountryIsoEnum.GF]: 'French Guiana',
  [CountryIsoEnum.PF]: 'French Polynesia',
  [CountryIsoEnum.TF]: 'French Southern Territories',
  [CountryIsoEnum.GA]: 'Gabon',
  [CountryIsoEnum.GM]: 'Gambia',
  [CountryIsoEnum.GE]: 'Georgia',
  [CountryIsoEnum.DE]: 'Germany',
  [CountryIsoEnum.GH]: 'Ghana',
  [CountryIsoEnum.GI]: 'Gibraltar',
  [CountryIsoEnum.GR]: 'Greece',
  [CountryIsoEnum.GL]: 'Greenland',
  [CountryIsoEnum.GD]: 'Grenada',
  [CountryIsoEnum.GP]: 'Guadeloupe',
  [CountryIsoEnum.GU]: 'Guam',
  [CountryIsoEnum.GT]: 'Guatemala',
  [CountryIsoEnum.GG]: 'Guernsey',
  [CountryIsoEnum.GN]: 'Guinea',
  [CountryIsoEnum.GW]: 'Guinea-Bissau',
  [CountryIsoEnum.GY]: 'Guyana',
  [CountryIsoEnum.HT]: 'Haiti',
  [CountryIsoEnum.HM]: 'Heard Island and McDonald Islands',
  [CountryIsoEnum.VA]: 'Holy See',
  [CountryIsoEnum.HN]: 'Honduras',
  [CountryIsoEnum.HK]: 'Hong Kong',
  [CountryIsoEnum.HU]: 'Hungary',
  [CountryIsoEnum.IS]: 'Iceland',
  [CountryIsoEnum.IN]: 'India',
  [CountryIsoEnum.ID]: 'Indonesia',
  [CountryIsoEnum.IR]: 'Iran',
  [CountryIsoEnum.IQ]: 'Iraq',
  [CountryIsoEnum.IE]: 'Ireland',
  [CountryIsoEnum.IM]: 'Isle of Man',
  [CountryIsoEnum.IL]: 'Israel',
  [CountryIsoEnum.IT]: 'Italy',
  [CountryIsoEnum.JM]: 'Jamaica',
  [CountryIsoEnum.JP]: 'Japan',
  [CountryIsoEnum.JE]: 'Jersey',
  [CountryIsoEnum.JO]: 'Jordan',
  [CountryIsoEnum.KZ]: 'Kazakhstan',
  [CountryIsoEnum.KE]: 'Kenya',
  [CountryIsoEnum.KI]: 'Kiribati',
  [CountryIsoEnum.KP]: 'North Korea',
  [CountryIsoEnum.KR]: 'South Korea',
  [CountryIsoEnum.KW]: 'Kuwait',
  [CountryIsoEnum.KG]: 'Kyrgyzstan',
  [CountryIsoEnum.LA]: "Lao People's Democratic Republic",
  [CountryIsoEnum.LV]: 'Latvia',
  [CountryIsoEnum.LB]: 'Lebanon',
  [CountryIsoEnum.LS]: 'Lesotho',
  [CountryIsoEnum.LR]: 'Liberia',
  [CountryIsoEnum.LY]: 'Libya',
  [CountryIsoEnum.LI]: 'Liechtenstein',
  [CountryIsoEnum.LT]: 'Lithuania',
  [CountryIsoEnum.LU]: 'Luxembourg',
  [CountryIsoEnum.MO]: 'Macao',
  [CountryIsoEnum.MG]: 'Madagascar',
  [CountryIsoEnum.MW]: 'Malawi',
  [CountryIsoEnum.MY]: 'Malaysia',
  [CountryIsoEnum.MV]: 'Maldives',
  [CountryIsoEnum.ML]: 'Mali',
  [CountryIsoEnum.MT]: 'Malta',
  [CountryIsoEnum.MH]: 'Marshall Islands',
  [CountryIsoEnum.MQ]: 'Martinique',
  [CountryIsoEnum.MR]: 'Mauritania',
  [CountryIsoEnum.MU]: 'Mauritius',
  [CountryIsoEnum.YT]: 'Mayotte',
  [CountryIsoEnum.MX]: 'Mexico',
  [CountryIsoEnum.FM]: 'Micronesia',
  [CountryIsoEnum.MD]: 'Moldova',
  [CountryIsoEnum.MC]: 'Monaco',
  [CountryIsoEnum.MN]: 'Mongolia',
  [CountryIsoEnum.ME]: 'Montenegro',
  [CountryIsoEnum.MS]: 'Montserrat',
  [CountryIsoEnum.MA]: 'Morocco',
  [CountryIsoEnum.MZ]: 'Mozambique',
  [CountryIsoEnum.MM]: 'Myanmar',
  [CountryIsoEnum.NA]: 'Namibia',
  [CountryIsoEnum.NR]: 'Nauru',
  [CountryIsoEnum.NP]: 'Nepal',
  [CountryIsoEnum.NL]: 'Netherlands',
  [CountryIsoEnum.NC]: 'New Caledonia',
  [CountryIsoEnum.NZ]: 'New Zealand',
  [CountryIsoEnum.NI]: 'Nicaragua',
  [CountryIsoEnum.NE]: 'Niger',
  [CountryIsoEnum.NG]: 'Nigeria',
  [CountryIsoEnum.NU]: 'Niue',
  [CountryIsoEnum.NF]: 'Norfolk Island',
  [CountryIsoEnum.MK]: 'North Macedonia',
  [CountryIsoEnum.MP]: 'Northern Mariana Islands',
  [CountryIsoEnum.NO]: 'Norway',
  [CountryIsoEnum.OM]: 'Oman',
  [CountryIsoEnum.PK]: 'Pakistan',
  [CountryIsoEnum.PW]: 'Palau',
  [CountryIsoEnum.PS]: 'Palestine, State of',
  [CountryIsoEnum.PA]: 'Panama',
  [CountryIsoEnum.PG]: 'Papua New Guinea',
  [CountryIsoEnum.PY]: 'Paraguay',
  [CountryIsoEnum.PE]: 'Peru',
  [CountryIsoEnum.PH]: 'Philippines',
  [CountryIsoEnum.PN]: 'Pitcairn',
  [CountryIsoEnum.PL]: 'Poland',
  [CountryIsoEnum.PT]: 'Portugal',
  [CountryIsoEnum.PR]: 'Puerto Rico',
  [CountryIsoEnum.QA]: 'Qatar',
  [CountryIsoEnum.RO]: 'Romania',
  [CountryIsoEnum.RU]: 'Russian Federation',
  [CountryIsoEnum.RW]: 'Rwanda',
  [CountryIsoEnum.RE]: 'Réunion',
  [CountryIsoEnum.BL]: 'Saint Barthélemy',
  [CountryIsoEnum.SH]: 'Saint Helena, Ascension and Tristan da Cunha',
  [CountryIsoEnum.KN]: 'Saint Kitts and Nevis',
  [CountryIsoEnum.LC]: 'Saint Lucia',
  [CountryIsoEnum.MF]: 'Saint Martin (French part)',
  [CountryIsoEnum.PM]: 'Saint Pierre and Miquelon',
  [CountryIsoEnum.VC]: 'Saint Vincent and the Grenadines',
  [CountryIsoEnum.WS]: 'Samoa',
  [CountryIsoEnum.SM]: 'San Marino',
  [CountryIsoEnum.ST]: 'Sao Tome and Principe',
  [CountryIsoEnum.SA]: 'Saudi Arabia',
  [CountryIsoEnum.SN]: 'Senegal',
  [CountryIsoEnum.RS]: 'Serbia',
  [CountryIsoEnum.SC]: 'Seychelles',
  [CountryIsoEnum.SL]: 'Sierra Leone',
  [CountryIsoEnum.SG]: 'Singapore',
  [CountryIsoEnum.SX]: 'Sint Maarten (Dutch part)',
  [CountryIsoEnum.SK]: 'Slovakia',
  [CountryIsoEnum.SI]: 'Slovenia',
  [CountryIsoEnum.SB]: 'Solomon Islands',
  [CountryIsoEnum.SO]: 'Somalia',
  [CountryIsoEnum.ZA]: 'South Africa',
  [CountryIsoEnum.GS]: 'South Georgia and the South Sandwich Islands',
  [CountryIsoEnum.SS]: 'South Sudan',
  [CountryIsoEnum.ES]: 'Spain',
  [CountryIsoEnum.LK]: 'Sri Lanka',
  [CountryIsoEnum.SD]: 'Sudan',
  [CountryIsoEnum.SR]: 'Suriname',
  [CountryIsoEnum.SJ]: 'Svalbard and Jan Mayen',
  [CountryIsoEnum.SE]: 'Sweden',
  [CountryIsoEnum.CH]: 'Switzerland',
  [CountryIsoEnum.SY]: 'Syrian Arab Republic',
  [CountryIsoEnum.TW]: 'Taiwan',
  [CountryIsoEnum.TJ]: 'Tajikistan',
  [CountryIsoEnum.TZ]: 'Tanzania, the United Republic of',
  [CountryIsoEnum.TH]: 'Thailand',
  [CountryIsoEnum.TL]: 'Timor-Leste',
  [CountryIsoEnum.TG]: 'Togo',
  [CountryIsoEnum.TK]: 'Tokelau',
  [CountryIsoEnum.TO]: 'Tonga',
  [CountryIsoEnum.TT]: 'Trinidad and Tobago',
  [CountryIsoEnum.TN]: 'Tunisia',
  [CountryIsoEnum.TM]: 'Turkmenistan',
  [CountryIsoEnum.TC]: 'Turks and Caicos Islands',
  [CountryIsoEnum.TV]: 'Tuvalu',
  [CountryIsoEnum.TR]: 'Türkiye',
  [CountryIsoEnum.UG]: 'Uganda',
  [CountryIsoEnum.UA]: 'Ukraine',
  [CountryIsoEnum.AE]: 'United Arab Emirates',
  [CountryIsoEnum.GB]: 'United Kingdom of Great Britain and Northern Ireland',
  [CountryIsoEnum.UM]: 'United States Minor Outlying Islands',
  [CountryIsoEnum.US]: 'United States of America',
  [CountryIsoEnum.UY]: 'Uruguay',
  [CountryIsoEnum.UZ]: 'Uzbekistan',
  [CountryIsoEnum.VU]: 'Vanuatu',
  [CountryIsoEnum.VE]: 'Venezuela',
  [CountryIsoEnum.VN]: 'Viet Nam',
  [CountryIsoEnum.VG]: 'Virgin Islands (British)',
  [CountryIsoEnum.VI]: 'Virgin Islands (U.S.)',
  [CountryIsoEnum.WF]: 'Wallis and Futuna',
  [CountryIsoEnum.EH]: 'Western Sahara',
  [CountryIsoEnum.YE]: 'Yemen',
  [CountryIsoEnum.ZM]: 'Zambia',
  [CountryIsoEnum.ZW]: 'Zimbabwe',
  [CountryIsoEnum.AX]: 'Åland Islands',
};

export const COUNTRY_ARRAY = Object.values(CountryIsoEnum);
