export interface PhoneCountry {
  name: string;
  iso2Code: string;
  dialCode: string;
  flag: string;
}

export const phoneCountries: PhoneCountry[] = [
  { name: 'Afghanistan', iso2Code: 'AF', dialCode: '+93', flag: '🇦🇫' },
  { name: 'Åland Islands', iso2Code: 'AX', dialCode: '+358', flag: '🇦🇽' },
  { name: 'Albania', iso2Code: 'AL', dialCode: '+355', flag: '🇦🇱' },
  { name: 'Algeria', iso2Code: 'DZ', dialCode: '+213', flag: '🇩🇿' },
  { name: 'American Samoa', iso2Code: 'AS', dialCode: '+1684', flag: '🇦🇸' },
  { name: 'Andorra', iso2Code: 'AD', dialCode: '+376', flag: '🇦🇩' },
  { name: 'Angola', iso2Code: 'AO', dialCode: '+244', flag: '🇦🇴' },
  { name: 'Anguilla', iso2Code: 'AI', dialCode: '+1264', flag: '🇦🇮' },
  { name: 'Antarctica', iso2Code: 'AQ', dialCode: '+672', flag: '🇦🇶' },
  { name: 'Antigua and Barbuda', iso2Code: 'AG', dialCode: '+1268', flag: '🇦🇬' },
  { name: 'Argentina', iso2Code: 'AR', dialCode: '+54', flag: '🇦🇷' },
  { name: 'Armenia', iso2Code: 'AM', dialCode: '+374', flag: '🇦🇲' },
  { name: 'Aruba', iso2Code: 'AW', dialCode: '+297', flag: '🇦🇼' },
  { name: 'Australia', iso2Code: 'AU', dialCode: '+61', flag: '🇦🇺' },
  { name: 'Austria', iso2Code: 'AT', dialCode: '+43', flag: '🇦🇹' },
  { name: 'Azerbaijan', iso2Code: 'AZ', dialCode: '+994', flag: '🇦🇿' },
  { name: 'Bahamas', iso2Code: 'BS', dialCode: '+1242', flag: '🇧🇸' },
  { name: 'Bahrain', iso2Code: 'BH', dialCode: '+973', flag: '🇧🇭' },
  { name: 'Bangladesh', iso2Code: 'BD', dialCode: '+880', flag: '🇧🇩' },
  { name: 'Barbados', iso2Code: 'BB', dialCode: '+1246', flag: '🇧🇧' },
  { name: 'Belarus', iso2Code: 'BY', dialCode: '+375', flag: '🇧🇾' },
  { name: 'Belgium', iso2Code: 'BE', dialCode: '+32', flag: '🇧🇪' },
  { name: 'Belize', iso2Code: 'BZ', dialCode: '+501', flag: '🇧🇿' },
  { name: 'Benin', iso2Code: 'BJ', dialCode: '+229', flag: '🇧🇯' },
  { name: 'Bermuda', iso2Code: 'BM', dialCode: '+1441', flag: '🇧🇲' },
  { name: 'Bhutan', iso2Code: 'BT', dialCode: '+975', flag: '🇧🇹' },
  { name: 'Bolivia, Plurinational State of', iso2Code: 'BO', dialCode: '+591', flag: '🇧🇴' },
  { name: 'Bonaire, Sint Eustatius and Saba', iso2Code: 'BQ', dialCode: '+599', flag: '🇧🇶' },
  { name: 'Bosnia and Herzegovina', iso2Code: 'BA', dialCode: '+387', flag: '🇧🇦' },
  { name: 'Botswana', iso2Code: 'BW', dialCode: '+267', flag: '🇧🇼' },
  { name: 'Brazil', iso2Code: 'BR', dialCode: '+55', flag: '🇧🇷' },
  { name: 'British Indian Ocean Territory', iso2Code: 'IO', dialCode: '+246', flag: '🇮🇴' },
  { name: 'Brunei Darussalam', iso2Code: 'BN', dialCode: '+673', flag: '🇧🇳' },
  { name: 'Bulgaria', iso2Code: 'BG', dialCode: '+359', flag: '🇧🇬' },
  { name: 'Burkina Faso', iso2Code: 'BF', dialCode: '+226', flag: '🇧🇫' },
  { name: 'Burundi', iso2Code: 'BI', dialCode: '+257', flag: '🇧🇮' },
  { name: 'Cabo Verde', iso2Code: 'CV', dialCode: '+238', flag: '🇨🇻' },
  { name: 'Cambodia', iso2Code: 'KH', dialCode: '+855', flag: '🇰🇭' },
  { name: 'Cameroon', iso2Code: 'CM', dialCode: '+237', flag: '🇨🇲' },
  { name: 'Canada', iso2Code: 'CA', dialCode: '+1', flag: '🇨🇦' },
  { name: 'Cayman Islands', iso2Code: 'KY', dialCode: '+1345', flag: '🇰🇾' },
  { name: 'Central African Republic', iso2Code: 'CF', dialCode: '+236', flag: '🇨🇫' },
  { name: 'Chad', iso2Code: 'TD', dialCode: '+235', flag: '🇹🇩' },
  { name: 'Chile', iso2Code: 'CL', dialCode: '+56', flag: '🇨🇱' },
  { name: 'China', iso2Code: 'CN', dialCode: '+86', flag: '🇨🇳' },
  { name: 'Christmas Island', iso2Code: 'CX', dialCode: '+61', flag: '🇨🇽' },
  { name: 'Cocos (Keeling) Islands', iso2Code: 'CC', dialCode: '+61', flag: '🇨🇨' },
  { name: 'Colombia', iso2Code: 'CO', dialCode: '+57', flag: '🇨🇴' },
  { name: 'Comoros', iso2Code: 'KM', dialCode: '+269', flag: '🇰🇲' },
  { name: 'Congo', iso2Code: 'CG', dialCode: '+242', flag: '🇨🇬' },
  { name: 'Congo, The Democratic Republic of the', iso2Code: 'CD', dialCode: '+243', flag: '🇨🇩' },
  { name: 'Cook Islands', iso2Code: 'CK', dialCode: '+682', flag: '🇨🇰' },
  { name: 'Costa Rica', iso2Code: 'CR', dialCode: '+506', flag: '🇨🇷' },
  { name: "Côte d'Ivoire", iso2Code: 'CI', dialCode: '+225', flag: '🇨🇮' },
  { name: 'Croatia', iso2Code: 'HR', dialCode: '+385', flag: '🇭🇷' },
  { name: 'Cuba', iso2Code: 'CU', dialCode: '+53', flag: '🇨🇺' },
  { name: 'Curaçao', iso2Code: 'CW', dialCode: '+599', flag: '🇨🇼' },
  { name: 'Cyprus', iso2Code: 'CY', dialCode: '+357', flag: '🇨🇾' },
  { name: 'Czechia', iso2Code: 'CZ', dialCode: '+420', flag: '🇨🇿' },
  { name: 'Denmark', iso2Code: 'DK', dialCode: '+45', flag: '🇩🇰' },
  { name: 'Djibouti', iso2Code: 'DJ', dialCode: '+253', flag: '🇩🇯' },
  { name: 'Dominica', iso2Code: 'DM', dialCode: '+1767', flag: '🇩🇲' },
  { name: 'Dominican Republic', iso2Code: 'DO', dialCode: '+1849', flag: '🇩🇴' },
  { name: 'Ecuador', iso2Code: 'EC', dialCode: '+593', flag: '🇪🇨' },
  { name: 'Egypt', iso2Code: 'EG', dialCode: '+20', flag: '🇪🇬' },
  { name: 'El Salvador', iso2Code: 'SV', dialCode: '+503', flag: '🇸🇻' },
  { name: 'Equatorial Guinea', iso2Code: 'GQ', dialCode: '+240', flag: '🇬🇶' },
  { name: 'Eritrea', iso2Code: 'ER', dialCode: '+291', flag: '🇪🇷' },
  { name: 'Estonia', iso2Code: 'EE', dialCode: '+372', flag: '🇪🇪' },
  { name: 'Eswatini', iso2Code: 'SZ', dialCode: '+268', flag: '🇸🇿' },
  { name: 'Ethiopia', iso2Code: 'ET', dialCode: '+251', flag: '🇪🇹' },
  { name: 'Falkland Islands (Malvinas)', iso2Code: 'FK', dialCode: '+500', flag: '🇫🇰' },
  { name: 'Faroe Islands', iso2Code: 'FO', dialCode: '+298', flag: '🇫🇴' },
  { name: 'Fiji', iso2Code: 'FJ', dialCode: '+679', flag: '🇫🇯' },
  { name: 'Finland', iso2Code: 'FI', dialCode: '+358', flag: '🇫🇮' },
  { name: 'France', iso2Code: 'FR', dialCode: '+33', flag: '🇫🇷' },
  { name: 'French Guiana', iso2Code: 'GF', dialCode: '+594', flag: '🇬🇫' },
  { name: 'French Polynesia', iso2Code: 'PF', dialCode: '+689', flag: '🇵🇫' },
  { name: 'French Southern Territories', iso2Code: 'TF', dialCode: '+262', flag: '🇹🇫' },
  { name: 'Gabon', iso2Code: 'GA', dialCode: '+241', flag: '🇬🇦' },
  { name: 'Gambia', iso2Code: 'GM', dialCode: '+220', flag: '🇬🇲' },
  { name: 'Georgia', iso2Code: 'GE', dialCode: '+995', flag: '🇬🇪' },
  { name: 'Germany', iso2Code: 'DE', dialCode: '+49', flag: '🇩🇪' },
  { name: 'Ghana', iso2Code: 'GH', dialCode: '+233', flag: '🇬🇭' },
  { name: 'Gibraltar', iso2Code: 'GI', dialCode: '+350', flag: '🇬🇮' },
  { name: 'Greece', iso2Code: 'GR', dialCode: '+30', flag: '🇬🇷' },
  { name: 'Greenland', iso2Code: 'GL', dialCode: '+299', flag: '🇬🇱' },
  { name: 'Grenada', iso2Code: 'GD', dialCode: '+1473', flag: '🇬🇩' },
  { name: 'Guadeloupe', iso2Code: 'GP', dialCode: '+590', flag: '🇬🇵' },
  { name: 'Guam', iso2Code: 'GU', dialCode: '+1671', flag: '🇬🇺' },
  { name: 'Guatemala', iso2Code: 'GT', dialCode: '+502', flag: '🇬🇹' },
  { name: 'Guernsey', iso2Code: 'GG', dialCode: '+44', flag: '🇬🇬' },
  { name: 'Guinea', iso2Code: 'GN', dialCode: '+224', flag: '🇬🇳' },
  { name: 'Guinea-Bissau', iso2Code: 'GW', dialCode: '+245', flag: '🇬🇼' },
  { name: 'Guyana', iso2Code: 'GY', dialCode: '+592', flag: '🇬🇾' },
  { name: 'Haiti', iso2Code: 'HT', dialCode: '+509', flag: '🇭🇹' },
  { name: 'Heard Island and McDonald Islands', iso2Code: 'HM', dialCode: '+672', flag: '🇭🇲' },
  { name: 'Holy See (Vatican City State)', iso2Code: 'VA', dialCode: '+39', flag: '🇻🇦' },
  { name: 'Honduras', iso2Code: 'HN', dialCode: '+504', flag: '🇭🇳' },
  { name: 'Hong Kong', iso2Code: 'HK', dialCode: '+852', flag: '🇭🇰' },
  { name: 'Hungary', iso2Code: 'HU', dialCode: '+36', flag: '🇭🇺' },
  { name: 'Iceland', iso2Code: 'IS', dialCode: '+354', flag: '🇮🇸' },
  { name: 'India', iso2Code: 'IN', dialCode: '+91', flag: '🇮🇳' },
  { name: 'Indonesia', iso2Code: 'ID', dialCode: '+62', flag: '🇮🇩' },
  { name: 'Iran, Islamic Republic of', iso2Code: 'IR', dialCode: '+98', flag: '🇮🇷' },
  { name: 'Iraq', iso2Code: 'IQ', dialCode: '+964', flag: '🇮🇶' },
  { name: 'Ireland', iso2Code: 'IE', dialCode: '+353', flag: '🇮🇪' },
  { name: 'Isle of Man', iso2Code: 'IM', dialCode: '+44', flag: '🇮🇲' },
  { name: 'Israel', iso2Code: 'IL', dialCode: '+972', flag: '🇮🇱' },
  { name: 'Italy', iso2Code: 'IT', dialCode: '+39', flag: '🇮🇹' },
  { name: 'Jamaica', iso2Code: 'JM', dialCode: '+1876', flag: '🇯🇲' },
  { name: 'Japan', iso2Code: 'JP', dialCode: '+81', flag: '🇯🇵' },
  { name: 'Jersey', iso2Code: 'JE', dialCode: '+44', flag: '🇯🇪' },
  { name: 'Jordan', iso2Code: 'JO', dialCode: '+962', flag: '🇯🇴' },
  { name: 'Kazakhstan', iso2Code: 'KZ', dialCode: '+7', flag: '🇰🇿' },
  { name: 'Kenya', iso2Code: 'KE', dialCode: '+254', flag: '🇰🇪' },
  { name: 'Kiribati', iso2Code: 'KI', dialCode: '+686', flag: '🇰🇮' },
  { name: "Korea, Democratic People's Republic of", iso2Code: 'KP', dialCode: '+850', flag: '🇰🇵' },
  { name: 'Korea, Republic of (South Korea)', iso2Code: 'KR', dialCode: '+82', flag: '🇰🇷' },
  { name: 'Kuwait', iso2Code: 'KW', dialCode: '+965', flag: '🇰🇼' },
  { name: 'Kyrgyzstan', iso2Code: 'KG', dialCode: '+996', flag: '🇰🇬' },
  { name: "Lao People's Democratic Republic", iso2Code: 'LA', dialCode: '+856', flag: '🇱🇦' },
  { name: 'Latvia', iso2Code: 'LV', dialCode: '+371', flag: '🇱🇻' },
  { name: 'Lebanon', iso2Code: 'LB', dialCode: '+961', flag: '🇱🇧' },
  { name: 'Lesotho', iso2Code: 'LS', dialCode: '+266', flag: '🇱🇸' },
  { name: 'Liberia', iso2Code: 'LR', dialCode: '+231', flag: '🇱🇷' },
  { name: 'Libya', iso2Code: 'LY', dialCode: '+218', flag: '🇱🇾' },
  { name: 'Liechtenstein', iso2Code: 'LI', dialCode: '+423', flag: '🇱🇮' },
  { name: 'Lithuania', iso2Code: 'LT', dialCode: '+370', flag: '🇱🇹' },
  { name: 'Luxembourg', iso2Code: 'LU', dialCode: '+352', flag: '🇱🇺' },
  { name: 'Macao', iso2Code: 'MO', dialCode: '+853', flag: '🇲🇴' },
  { name: 'Madagascar', iso2Code: 'MG', dialCode: '+261', flag: '🇲🇬' },
  { name: 'Malawi', iso2Code: 'MW', dialCode: '+265', flag: '🇲🇼' },
  { name: 'Malaysia', iso2Code: 'MY', dialCode: '+60', flag: '🇲🇾' },
  { name: 'Maldives', iso2Code: 'MV', dialCode: '+960', flag: '🇲🇻' },
  { name: 'Mali', iso2Code: 'ML', dialCode: '+223', flag: '🇲🇱' },
  { name: 'Malta', iso2Code: 'MT', dialCode: '+356', flag: '🇲🇹' },
  { name: 'Marshall Islands', iso2Code: 'MH', dialCode: '+692', flag: '🇲🇭' },
  { name: 'Martinique', iso2Code: 'MQ', dialCode: '+596', flag: '🇲🇶' },
  { name: 'Mauritania', iso2Code: 'MR', dialCode: '+222', flag: '🇲🇷' },
  { name: 'Mauritius', iso2Code: 'MU', dialCode: '+230', flag: '🇲🇺' },
  { name: 'Mayotte', iso2Code: 'YT', dialCode: '+262', flag: '🇾🇹' },
  { name: 'Mexico', iso2Code: 'MX', dialCode: '+52', flag: '🇲🇽' },
  { name: 'Micronesia, Federated States of', iso2Code: 'FM', dialCode: '+691', flag: '🇫🇲' },
  { name: 'Moldova, Republic of', iso2Code: 'MD', dialCode: '+373', flag: '🇲🇩' },
  { name: 'Monaco', iso2Code: 'MC', dialCode: '+377', flag: '🇲🇨' },
  { name: 'Mongolia', iso2Code: 'MN', dialCode: '+976', flag: '🇲🇳' },
  { name: 'Montenegro', iso2Code: 'ME', dialCode: '+382', flag: '🇲🇪' },
  { name: 'Montserrat', iso2Code: 'MS', dialCode: '+1664', flag: '🇲🇸' },
  { name: 'Morocco', iso2Code: 'MA', dialCode: '+212', flag: '🇲🇦' },
  { name: 'Mozambique', iso2Code: 'MZ', dialCode: '+258', flag: '🇲🇿' },
  { name: 'Myanmar', iso2Code: 'MM', dialCode: '+95', flag: '🇲🇲' },
  { name: 'Namibia', iso2Code: 'NA', dialCode: '+264', flag: '🇳🇦' },
  { name: 'Nauru', iso2Code: 'NR', dialCode: '+674', flag: '🇳🇷' },
  { name: 'Nepal', iso2Code: 'NP', dialCode: '+977', flag: '🇳🇵' },
  { name: 'Netherlands', iso2Code: 'NL', dialCode: '+31', flag: '🇳🇱' },
  { name: 'New Caledonia', iso2Code: 'NC', dialCode: '+687', flag: '🇳🇨' },
  { name: 'New Zealand', iso2Code: 'NZ', dialCode: '+64', flag: '🇳🇿' },
  { name: 'Nicaragua', iso2Code: 'NI', dialCode: '+505', flag: '🇳🇮' },
  { name: 'Niger', iso2Code: 'NE', dialCode: '+227', flag: '🇳🇪' },
  { name: 'Nigeria', iso2Code: 'NG', dialCode: '+234', flag: '🇳🇬' },
  { name: 'Niue', iso2Code: 'NU', dialCode: '+683', flag: '🇳🇺' },
  { name: 'Norfolk Island', iso2Code: 'NF', dialCode: '+672', flag: '🇳🇫' },
  { name: 'Northern Mariana Islands', iso2Code: 'MP', dialCode: '+1670', flag: '🇲🇵' },
  { name: 'Norway', iso2Code: 'NO', dialCode: '+47', flag: '🇳🇴' },
  { name: 'Oman', iso2Code: 'OM', dialCode: '+968', flag: '🇴🇲' },
  { name: 'Pakistan', iso2Code: 'PK', dialCode: '+92', flag: '🇵🇰' },
  { name: 'Palau', iso2Code: 'PW', dialCode: '+680', flag: '🇵🇼' },
  { name: 'Palestine, State of', iso2Code: 'PS', dialCode: '+970', flag: '🇵🇸' },
  { name: 'Panama', iso2Code: 'PA', dialCode: '+507', flag: '🇵🇦' },
  { name: 'Papua New Guinea', iso2Code: 'PG', dialCode: '+675', flag: '🇵🇬' },
  { name: 'Paraguay', iso2Code: 'PY', dialCode: '+595', flag: '🇵🇾' },
  { name: 'Peru', iso2Code: 'PE', dialCode: '+51', flag: '🇵🇪' },
  { name: 'Philippines', iso2Code: 'PH', dialCode: '+63', flag: '🇵🇭' },
  { name: 'Pitcairn', iso2Code: 'PN', dialCode: '+64', flag: '🇵🇳' },
  { name: 'Poland', iso2Code: 'PL', dialCode: '+48', flag: '🇵🇱' },
  { name: 'Portugal', iso2Code: 'PT', dialCode: '+351', flag: '🇵🇹' },
  { name: 'Puerto Rico', iso2Code: 'PR', dialCode: '+1', flag: '🇵🇷' },
  { name: 'Qatar', iso2Code: 'QA', dialCode: '+974', flag: '🇶🇦' },
  { name: 'Réunion', iso2Code: 'RE', dialCode: '+262', flag: '🇷🇪' },
  { name: 'Romania', iso2Code: 'RO', dialCode: '+40', flag: '🇷🇴' },
  { name: 'Russian Federation', iso2Code: 'RU', dialCode: '+7', flag: '🇷🇺' },
  { name: 'Rwanda', iso2Code: 'RW', dialCode: '+250', flag: '🇷🇼' },
  { name: 'Saint Barthélemy', iso2Code: 'BL', dialCode: '+590', flag: '🇧🇱' },
  { name: 'Saint Helena, Ascension and Tristan da Cunha', iso2Code: 'SH', dialCode: '+290', flag: '🇸🇭' },
  { name: 'Saint Kitts and Nevis', iso2Code: 'KN', dialCode: '+1869', flag: '🇰🇳' },
  { name: 'Saint Lucia', iso2Code: 'LC', dialCode: '+1758', flag: '🇱🇨' },
  { name: 'Saint Martin (French part)', iso2Code: 'MF', dialCode: '+590', flag: '🇲🇫' },
  { name: 'Saint Pierre and Miquelon', iso2Code: 'PM', dialCode: '+508', flag: '🇵🇲' },
  { name: 'Saint Vincent and the Grenadines', iso2Code: 'VC', dialCode: '+1784', flag: '🇻🇨' },
  { name: 'Samoa', iso2Code: 'WS', dialCode: '+685', flag: '🇼🇸' },
  { name: 'San Marino', iso2Code: 'SM', dialCode: '+378', flag: '🇸🇲' },
  { name: 'Sao Tome and Principe', iso2Code: 'ST', dialCode: '+239', flag: '🇸🇹' },
  { name: 'Saudi Arabia', iso2Code: 'SA', dialCode: '+966', flag: '🇸🇦' },
  { name: 'Senegal', iso2Code: 'SN', dialCode: '+221', flag: '🇸🇳' },
  { name: 'Serbia', iso2Code: 'RS', dialCode: '+381', flag: '🇷🇸' },
  { name: 'Seychelles', iso2Code: 'SC', dialCode: '+248', flag: '🇸🇨' },
  { name: 'Sierra Leone', iso2Code: 'SL', dialCode: '+232', flag: '🇸🇱' },
  { name: 'Singapore', iso2Code: 'SG', dialCode: '+65', flag: '🇸🇬' },
  { name: 'Sint Maarten (Dutch part)', iso2Code: 'SX', dialCode: '+1721', flag: '🇸🇽' },
  { name: 'Slovakia', iso2Code: 'SK', dialCode: '+421', flag: '🇸🇰' },
  { name: 'Slovenia', iso2Code: 'SI', dialCode: '+386', flag: '🇸🇮' },
  { name: 'Solomon Islands', iso2Code: 'SB', dialCode: '+677', flag: '🇸🇧' },
  { name: 'Somalia', iso2Code: 'SO', dialCode: '+252', flag: '🇸🇴' },
  { name: 'South Africa', iso2Code: 'ZA', dialCode: '+27', flag: '🇿🇦' },
  { name: 'South Georgia and the South Sandwich Islands', iso2Code: 'GS', dialCode: '+500', flag: '🇬🇸' },
  { name: 'South Sudan', iso2Code: 'SS', dialCode: '+211', flag: '🇸🇸' },
  { name: 'Spain', iso2Code: 'ES', dialCode: '+34', flag: '🇪🇸' },
  { name: 'Sri Lanka', iso2Code: 'LK', dialCode: '+94', flag: '🇱🇰' },
  { name: 'Sudan', iso2Code: 'SD', dialCode: '+249', flag: '🇸🇩' },
  { name: 'Suriname', iso2Code: 'SR', dialCode: '+597', flag: '🇸🇷' },
  { name: 'Svalbard and Jan Mayen', iso2Code: 'SJ', dialCode: '+47', flag: '🇸🇯' },
  { name: 'Sweden', iso2Code: 'SE', dialCode: '+46', flag: '🇸🇪' },
  { name: 'Switzerland', iso2Code: 'CH', dialCode: '+41', flag: '🇨🇭' },
  { name: 'Syrian Arab Republic', iso2Code: 'SY', dialCode: '+963', flag: '🇸🇾' },
  { name: 'Taiwan, Province of China', iso2Code: 'TW', dialCode: '+886', flag: '🇹🇼' },
  { name: 'Tajikistan', iso2Code: 'TJ', dialCode: '+992', flag: '🇹🇯' },
  { name: 'Tanzania, United Republic of', iso2Code: 'TZ', dialCode: '+255', flag: '🇹🇿' },
  { name: 'Thailand', iso2Code: 'TH', dialCode: '+66', flag: '🇹🇭' },
  { name: 'Timor-Leste', iso2Code: 'TL', dialCode: '+670', flag: '🇹🇱' },
  { name: 'Togo', iso2Code: 'TG', dialCode: '+228', flag: '🇹🇬' },
  { name: 'Tokelau', iso2Code: 'TK', dialCode: '+690', flag: '🇹🇰' },
  { name: 'Tonga', iso2Code: 'TO', dialCode: '+676', flag: '🇹🇴' },
  { name: 'Trinidad and Tobago', iso2Code: 'TT', dialCode: '+1868', flag: '🇹🇹' },
  { name: 'Tunisia', iso2Code: 'TN', dialCode: '+216', flag: '🇹🇳' },
  { name: 'Turkey', iso2Code: 'TR', dialCode: '+90', flag: '🇹🇷' },
  { name: 'Turkmenistan', iso2Code: 'TM', dialCode: '+993', flag: '🇹🇲' },
  { name: 'Turks and Caicos Islands', iso2Code: 'TC', dialCode: '+1649', flag: '🇹🇨' },
  { name: 'Tuvalu', iso2Code: 'TV', dialCode: '+688', flag: '🇹🇻' },
  { name: 'Uganda', iso2Code: 'UG', dialCode: '+256', flag: '🇺🇬' },
  { name: 'Ukraine', iso2Code: 'UA', dialCode: '+380', flag: '🇺🇦' },
  { name: 'United Arab Emirates', iso2Code: 'AE', dialCode: '+971', flag: '🇦🇪' },
  { name: 'United Kingdom', iso2Code: 'GB', dialCode: '+44', flag: '🇬🇧' },
  { name: 'United States', iso2Code: 'US', dialCode: '+1', flag: '🇺🇸' },
  { name: 'Uruguay', iso2Code: 'UY', dialCode: '+598', flag: '🇺🇾' },
  { name: 'Uzbekistan', iso2Code: 'UZ', dialCode: '+998', flag: '🇺🇿' },
  { name: 'Vanuatu', iso2Code: 'VU', dialCode: '+678', flag: '🇻🇺' },
  { name: 'Venezuela, Bolivarian Republic of', iso2Code: 'VE', dialCode: '+58', flag: '🇻🇪' },
  { name: 'Viet Nam', iso2Code: 'VN', dialCode: '+84', flag: '🇻🇳' },
  { name: 'Virgin Islands, British', iso2Code: 'VG', dialCode: '+1284', flag: '🇻🇬' },
  { name: 'Virgin Islands, U.S.', iso2Code: 'VI', dialCode: '+1340', flag: '🇻🇮' },
  { name: 'Wallis and Futuna', iso2Code: 'WF', dialCode: '+681', flag: '🇼🇫' },
  { name: 'Western Sahara', iso2Code: 'EH', dialCode: '+212', flag: '🇪🇭' },
  { name: 'Yemen', iso2Code: 'YE', dialCode: '+967', flag: '🇾🇪' },
  { name: 'Zambia', iso2Code: 'ZM', dialCode: '+260', flag: '🇿🇲' },
  { name: 'Zimbabwe', iso2Code: 'ZW', dialCode: '+263', flag: '🇿🇼' },
];
