import { computeItineraryNumberOfDays } from '@/helper/itineraryDaysHelper';
import { ItineraryRoute } from '@/types/itinerary.type';

const mallorcaRoundIsland14Route: ItineraryRoute = {
  metaTitle: '14-Day Palma de Mallorca Route | Boat4You',
  metaDesc: 'Two-week itinerary from Palma de Mallorca.',
  id: 'mallorca-round-island-14-days',
  startingPoint: 'Palma de Mallorca',
  otherPoints: ['Alcúdia', 'Cabrera Archipelago', 'Cala Figuera'],
  cardImage: { src: '/images/itinerary/spain/mallorca-itinerary/routes/ciutadella.webp', alt: '14-day route' },
  gallery: [],
  routeDays: [
    {
      id: 'mallorca-round-island-14-days-day-1',
      routeFrom: 'Palma de Mallorca',
      routeTo: 'El Toro',
      day: 1,
      mapPin: { desktop: { left: 13.2, top: 53.4 }, mobile: { left: 13.2, top: 53.4 } },
      description: 'Day 1: Palma de Mallorca to El Toro.',
      gallery: [{ src: '/images/itinerary/spain/destinations/el-toro-mallorca.webp', alt: 'El Toro' }],
    },
    {
      id: 'mallorca-round-island-14-days-day-2',
      routeFrom: 'El Toro',
      routeTo: 'Port de Sóller',
      day: 2,
      mapPin: { desktop: { left: 28.9, top: 24.9 }, mobile: { left: 28.9, top: 24.9 } },
      description: 'Day 2: El Toro to Port de Sóller.',
      gallery: [{ src: '/images/itinerary/spain/destinations/port-de-soller.webp', alt: 'Port de Sóller' }],
    },
    {
      id: 'mallorca-round-island-14-days-day-3',
      routeFrom: 'Port de Sóller',
      routeTo: 'Cala Sant Vicenç',
      day: 3,
      mapPin: { desktop: { left: 56.4, top: 13.2 }, mobile: { left: 56.4, top: 13.2 } },
      description: 'Day 3: Port de Sóller to Cala Sant Vicenç.',
      gallery: [{ src: '/images/itinerary/spain/destinations/cala-sant-vicenc.webp', alt: 'Cala Sant Vicenç' }],
    },
    {
      id: 'mallorca-round-island-14-days-day-4',
      routeFrom: 'Cala Sant Vicenç',
      routeTo: 'Port de Pollença',
      day: 4,
      mapPin: { desktop: { left: 58.2, top: 14.1 }, mobile: { left: 58.2, top: 14.1 } },
      description: 'Day 4: Cala Sant Vicenç to Port de Pollença.',
      gallery: [{ src: '/images/itinerary/spain/destinations/port-de-pollenca.webp', alt: 'Port de Pollença' }],
    },
    {
      id: 'mallorca-round-island-14-days-day-5',
      routeFrom: 'Port de Pollença',
      routeTo: 'Alcúdia',
      day: 5,
      mapPin: { desktop: { left: 61.0, top: 19.4 }, mobile: { left: 61.0, top: 19.4 } },
      description: 'Day 5: Port de Pollença to Alcúdia.',
      gallery: [{ src: '/images/itinerary/spain/destinations/alcudia.webp', alt: 'Alcúdia' }],
    },
    {
      id: 'mallorca-round-island-14-days-day-6',
      routeFrom: 'Alcúdia',
      routeTo: 'Cala Ratjada (Mallorca)',
      day: 6,
      mapPin: { desktop: { left: 86.8, top: 33.6 }, mobile: { left: 86.8, top: 33.6 } },
      description: 'Day 6: Alcúdia to Cala Ratjada (Mallorca).',
      gallery: [{ src: '/images/itinerary/spain/destinations/cala-ratjada.webp', alt: 'Cala Ratjada (Mallorca)' }],
    },
    {
      id: 'mallorca-round-island-14-days-day-7',
      routeFrom: 'Cala Ratjada (Mallorca)',
      routeTo: 'Porto Cristo',
      day: 7,
      mapPin: { desktop: { left: 77.1, top: 49.5 }, mobile: { left: 77.1, top: 49.5 } },
      description: 'Day 7: Cala Ratjada (Mallorca) to Porto Cristo.',
      gallery: [{ src: '/images/itinerary/spain/destinations/porto-cristo.webp', alt: 'Porto Cristo' }],
    },
    {
      id: 'mallorca-round-island-14-days-day-8',
      routeFrom: 'Porto Cristo',
      routeTo: 'Portocolom',
      day: 8,
      mapPin: { desktop: { left: 72.1, top: 61.0 }, mobile: { left: 72.1, top: 61.0 } },
      description: 'Day 8: Porto Cristo to Portocolom.',
      gallery: [{ src: '/images/itinerary/spain/destinations/portocolom.webp', alt: 'Portocolom' }],
    },
    {
      id: 'mallorca-round-island-14-days-day-9',
      routeFrom: 'Portocolom',
      routeTo: 'Cala Santanyí',
      day: 9,
      mapPin: { desktop: { left: 61.7, top: 68.7 }, mobile: { left: 61.7, top: 68.7 } },
      description: 'Day 9: Portocolom to Cala Santanyí.',
      gallery: [{ src: '/images/itinerary/spain/destinations/cala-santanyi.webp', alt: 'Cala Santanyí' }],
    },
    {
      id: 'mallorca-round-island-14-days-day-10',
      routeFrom: 'Cala Santanyí',
      routeTo: 'Cala Pi',
      day: 10,
      mapPin: { desktop: { left: 40.1, top: 66.2 }, mobile: { left: 40.1, top: 66.2 } },
      description: 'Day 10: Cala Santanyí to Cala Pi.',
      gallery: [{ src: '/images/itinerary/spain/destinations/cala-pi.webp', alt: 'Cala Pi' }],
    },
    {
      id: 'mallorca-round-island-14-days-day-11',
      routeFrom: 'Cala Pi',
      routeTo: 'Cabrera Archipelago',
      day: 11,
      mapPin: { desktop: { left: 48.0, top: 86.8 }, mobile: { left: 48.0, top: 86.8 } },
      description: 'Day 11: Cala Pi to Cabrera Archipelago.',
      gallery: [{ src: '/images/itinerary/spain/destinations/cabrera-archipelago.webp', alt: 'Cabrera Archipelago' }],
    },
    {
      id: 'mallorca-round-island-14-days-day-12',
      routeFrom: 'Cabrera Archipelago',
      routeTo: 'Es Trenc',
      day: 12,
      mapPin: { desktop: { left: 51.0, top: 67.7 }, mobile: { left: 51.0, top: 67.7 } },
      description: 'Day 12: Cabrera Archipelago to Es Trenc.',
      gallery: [{ src: '/images/itinerary/spain/destinations/es-trenc.webp', alt: 'Es Trenc' }],
    },
    {
      id: 'mallorca-round-island-14-days-day-13',
      routeFrom: 'Es Trenc',
      routeTo: 'Cala Figuera',
      day: 13,
      mapPin: { desktop: { left: 65.1, top: 69.4 }, mobile: { left: 65.1, top: 69.4 } },
      description: 'Day 13: Es Trenc to Cala Figuera.',
      gallery: [{ src: '/images/itinerary/spain/destinations/cala-figuera.webp', alt: 'Cala Figuera' }],
    },
    {
      id: 'mallorca-round-island-14-days-day-14',
      routeFrom: 'Cala Figuera',
      routeTo: 'Palma de Mallorca',
      day: 14,
      mapPin: { desktop: { left: 25.7, top: 46.6 }, mobile: { left: 25.7, top: 46.6 } },
      description: 'Day 14: Cala Figuera to Palma de Mallorca.',
      gallery: [{ src: '/images/itinerary/spain/destinations/palma.webp', alt: 'Palma de Mallorca' }],
    },
  ],
  map: {
    desktop: {
      image: { src: '/images/itinerary/spain/mallorca-maps/mallorca-round-island-14-days-map.webp', alt: 'Route map' },
      width: 1350,
      height: 1377,
    },
    mobile: {
      image: { src: '/images/itinerary/spain/mallorca-maps/mallorca-round-island-14-days-map.webp', alt: 'Route map' },
      width: 1350,
      height: 1377,
    },
  },
};

export default computeItineraryNumberOfDays(mallorcaRoundIsland14Route);
