import { computeItineraryNumberOfDays } from '@/helper/itineraryDaysHelper';
import { ItineraryRoute } from '@/types/itinerary.type';

const ibizaFormentera14Route: ItineraryRoute = {
  metaTitle: '14-Day Marina Eivissa Route | Boat4You',
  metaDesc: 'Two-week itinerary from Marina Eivissa.',
  id: 'ibiza-formentera-14-days',
  startingPoint: 'Marina Eivissa',
  otherPoints: ['Cala Vedella', 'Formentera', 'Marina Eivissa'],
  cardImage: { src: '/images/itinerary/spain/ibiza-itinerary/routes/ibiza.webp', alt: '14-day route' },
  gallery: [],
  routeDays: [
    {
      id: 'ibiza-formentera-14-days-day-1',
      routeFrom: 'Marina Eivissa',
      routeTo: 'Platja de ses Salines',
      day: 1,
      mapPin: { desktop: { left: 56.2, top: 63.1 }, mobile: { left: 56.2, top: 63.1 } },
      description: 'Day 1: Marina Eivissa to Platja de ses Salines.',
      gallery: [{ src: '/images/itinerary/spain/destinations/platja-daro.webp', alt: 'Platja de ses Salines' }],
    },
    {
      id: 'ibiza-formentera-14-days-day-2',
      routeFrom: 'Platja de ses Salines',
      routeTo: 'Puerto Formentera',
      day: 2,
      mapPin: { desktop: { left: 60.0, top: 81.2 }, mobile: { left: 60.0, top: 81.2 } },
      description: 'Day 2: Platja de ses Salines to Puerto Formentera.',
      gallery: [{ src: '/images/itinerary/spain/destinations/puerto-de-addaya.webp', alt: 'Puerto Formentera' }],
    },
    {
      id: 'ibiza-formentera-14-days-day-3',
      routeFrom: 'Puerto Formentera',
      routeTo: 'Formentera',
      day: 3,
      mapPin: { desktop: { left: 63.0, top: 86.8 }, mobile: { left: 63.0, top: 86.8 } },
      description: 'Day 3: Puerto Formentera to Formentera.',
      gallery: [{ src: '/images/itinerary/spain/destinations/puerto-formentera.webp', alt: 'Formentera' }],
    },
    {
      id: 'ibiza-formentera-14-days-day-4',
      routeFrom: 'Formentera',
      routeTo: 'Cala Vedella',
      day: 4,
      mapPin: { desktop: { left: 13.2, top: 54.5 }, mobile: { left: 13.2, top: 54.5 } },
      description: 'Day 4: Formentera to Cala Vedella.',
      gallery: [{ src: '/images/itinerary/spain/destinations/cala-vedella.webp', alt: 'Cala Vedella' }],
    },
    {
      id: 'ibiza-formentera-14-days-day-5',
      routeFrom: 'Cala Vedella',
      routeTo: 'Sant Antoni de Portmany',
      day: 5,
      mapPin: { desktop: { left: 33.6, top: 37.3 }, mobile: { left: 33.6, top: 37.3 } },
      description: 'Day 5: Cala Vedella to Sant Antoni de Portmany.',
      gallery: [
        { src: '/images/itinerary/spain/destinations/sant-antoni-de-portmany.webp', alt: 'Sant Antoni de Portmany' },
      ],
    },
    {
      id: 'ibiza-formentera-14-days-day-6',
      routeFrom: 'Sant Antoni de Portmany',
      routeTo: 'Portinatx',
      day: 6,
      mapPin: { desktop: { left: 82.6, top: 13.2 }, mobile: { left: 82.6, top: 13.2 } },
      description: 'Day 6: Sant Antoni de Portmany to Portinatx.',
      gallery: [{ src: '/images/itinerary/spain/destinations/portinatx.webp', alt: 'Portinatx' }],
    },
    {
      id: 'ibiza-formentera-14-days-day-7',
      routeFrom: 'Portinatx',
      routeTo: 'Santa Eulària des Riu',
      day: 7,
      mapPin: { desktop: { left: 86.8, top: 36.4 }, mobile: { left: 86.8, top: 36.4 } },
      description: 'Day 7: Portinatx to Santa Eulària des Riu.',
      gallery: [
        { src: '/images/itinerary/spain/destinations/santa-eularia-des-riu.webp', alt: 'Santa Eulària des Riu' },
      ],
    },
    {
      id: 'ibiza-formentera-14-days-day-8',
      routeFrom: 'Santa Eulària des Riu',
      routeTo: 'Marina Eivissa',
      day: 8,
      mapPin: { desktop: { left: 60.5, top: 50.5 }, mobile: { left: 60.5, top: 50.5 } },
      description: 'Day 8: Santa Eulària des Riu to Marina Eivissa.',
      gallery: [{ src: '/images/itinerary/spain/destinations/eivissa.webp', alt: 'Marina Eivissa' }],
    },
    {
      id: 'ibiza-formentera-14-days-day-9',
      routeFrom: 'Marina Eivissa',
      routeTo: 'Ses Salines',
      day: 9,
      mapPin: { desktop: { left: 56.2, top: 63.1 }, mobile: { left: 56.2, top: 63.1 } },
      description: 'Day 9: Marina Eivissa to Ses Salines.',
      gallery: [{ src: '/images/itinerary/spain/destinations/platja-de-ses-salines.webp', alt: 'Ses Salines' }],
    },
    {
      id: 'ibiza-formentera-14-days-day-10',
      routeFrom: 'Ses Salines',
      routeTo: 'Formentera',
      day: 10,
      mapPin: { desktop: { left: 63.0, top: 86.8 }, mobile: { left: 63.0, top: 86.8 } },
      description: 'Day 10: Ses Salines to Formentera.',
      gallery: [{ src: '/images/itinerary/spain/destinations/puerto-formentera.webp', alt: 'Formentera' }],
    },
    {
      id: 'ibiza-formentera-14-days-day-11',
      routeFrom: 'Formentera',
      routeTo: 'Cala Vedella',
      day: 11,
      mapPin: { desktop: { left: 13.2, top: 54.5 }, mobile: { left: 13.2, top: 54.5 } },
      description: 'Day 11: Formentera to Cala Vedella.',
      gallery: [{ src: '/images/itinerary/spain/destinations/cala-vedella.webp', alt: 'Cala Vedella' }],
    },
    {
      id: 'ibiza-formentera-14-days-day-12',
      routeFrom: 'Cala Vedella',
      routeTo: 'Sant Antoni de Portmany',
      day: 12,
      mapPin: { desktop: { left: 33.6, top: 37.3 }, mobile: { left: 33.6, top: 37.3 } },
      description: 'Day 12: Cala Vedella to Sant Antoni de Portmany.',
      gallery: [
        { src: '/images/itinerary/spain/destinations/sant-antoni-de-portmany.webp', alt: 'Sant Antoni de Portmany' },
      ],
    },
    {
      id: 'ibiza-formentera-14-days-day-13',
      routeFrom: 'Sant Antoni de Portmany',
      routeTo: 'Santa Eulària des Riu',
      day: 13,
      mapPin: { desktop: { left: 86.8, top: 36.4 }, mobile: { left: 86.8, top: 36.4 } },
      description: 'Day 13: Sant Antoni de Portmany to Santa Eulària des Riu.',
      gallery: [
        { src: '/images/itinerary/spain/destinations/santa-eularia-des-riu.webp', alt: 'Santa Eulària des Riu' },
      ],
    },
    {
      id: 'ibiza-formentera-14-days-day-14',
      routeFrom: 'Santa Eulària des Riu',
      routeTo: 'Marina Eivissa',
      day: 14,
      mapPin: { desktop: { left: 60.5, top: 50.5 }, mobile: { left: 60.5, top: 50.5 } },
      description: 'Day 14: Santa Eulària des Riu to Marina Eivissa.',
      gallery: [{ src: '/images/itinerary/spain/destinations/eivissa.webp', alt: 'Marina Eivissa' }],
    },
  ],
  map: {
    desktop: {
      image: { src: '/images/itinerary/spain/ibiza-maps/ibiza-formentera-14-days-map.webp', alt: 'Route map' },
      width: 1350,
      height: 2220,
    },
    mobile: {
      image: { src: '/images/itinerary/spain/ibiza-maps/ibiza-formentera-14-days-map.webp', alt: 'Route map' },
      width: 1350,
      height: 2220,
    },
  },
};

export default computeItineraryNumberOfDays(ibizaFormentera14Route);
