import { computeItineraryNumberOfDays } from '@/helper/itineraryDaysHelper';
import { ItineraryRoute } from '@/types/itinerary.type';

const costaBrava14Route: ItineraryRoute = {
  metaTitle: '14-Day Barcelona (Port Olímpic) Route | Boat4You',
  metaDesc: 'Two-week itinerary from Barcelona (Port Olímpic).',
  id: 'costa-brava-14-days',
  startingPoint: 'Barcelona (Port Olímpic)',
  otherPoints: ['Arenys de Mar', 'Blanes', 'Calella'],
  cardImage: { src: '/images/itinerary/spain/catalonia-itinerary/routes/barcelona.webp', alt: '14-day route' },
  gallery: [],
  routeDays: [
    {
      id: 'costa-brava-14-days-day-1',
      routeFrom: 'Barcelona (Port Olímpic)',
      routeTo: 'El Masnou',
      day: 1,
      mapPin: { desktop: { left: 41.4, top: 57.4 }, mobile: { left: 41.4, top: 57.4 } },
      description: 'Day 1: Barcelona (Port Olímpic) to El Masnou.',
      gallery: [],
    },
    {
      id: 'costa-brava-14-days-day-2',
      routeFrom: 'El Masnou',
      routeTo: 'Mataró',
      day: 2,
      mapPin: { desktop: { left: 48.7, top: 50.5 }, mobile: { left: 48.7, top: 50.5 } },
      description: 'Day 2: El Masnou to Mataró.',
      gallery: [],
    },
    {
      id: 'costa-brava-14-days-day-3',
      routeFrom: 'Mataró',
      routeTo: 'Arenys de Mar',
      day: 3,
      mapPin: { desktop: { left: 54.6, top: 45.4 }, mobile: { left: 54.6, top: 45.4 } },
      description: 'Day 3: Mataró to Arenys de Mar.',
      gallery: [],
    },
    {
      id: 'costa-brava-14-days-day-4',
      routeFrom: 'Arenys de Mar',
      routeTo: 'Calella',
      day: 4,
      mapPin: { desktop: { left: 60.9, top: 41.4 }, mobile: { left: 60.9, top: 41.4 } },
      description: 'Day 4: Arenys de Mar to Calella.',
      gallery: [],
    },
    {
      id: 'costa-brava-14-days-day-5',
      routeFrom: 'Calella',
      routeTo: 'Blanes',
      day: 5,
      mapPin: { desktop: { left: 67.9, top: 34.1 }, mobile: { left: 67.9, top: 34.1 } },
      description: 'Day 5: Calella to Blanes.',
      gallery: [],
    },
    {
      id: 'costa-brava-14-days-day-6',
      routeFrom: 'Blanes',
      routeTo: 'Lloret de Mar',
      day: 6,
      mapPin: { desktop: { left: 71.0, top: 31.2 }, mobile: { left: 71.0, top: 31.2 } },
      description: 'Day 6: Blanes to Lloret de Mar.',
      gallery: [],
    },
    {
      id: 'costa-brava-14-days-day-7',
      routeFrom: 'Lloret de Mar',
      routeTo: 'Tossa de Mar',
      day: 7,
      mapPin: { desktop: { left: 75.8, top: 28.7 }, mobile: { left: 75.8, top: 28.7 } },
      description: 'Day 7: Lloret de Mar to Tossa de Mar.',
      gallery: [],
    },
    {
      id: 'costa-brava-14-days-day-8',
      routeFrom: 'Tossa de Mar',
      routeTo: 'Sant Feliu de Guíxols',
      day: 8,
      mapPin: { desktop: { left: 81.2, top: 21.3 }, mobile: { left: 81.2, top: 21.3 } },
      description: 'Day 8: Tossa de Mar to Sant Feliu de Guíxols.',
      gallery: [],
    },
    {
      id: 'costa-brava-14-days-day-9',
      routeFrom: 'Sant Feliu de Guíxols',
      routeTo: 'Palamós',
      day: 9,
      mapPin: { desktop: { left: 86.8, top: 13.2 }, mobile: { left: 86.8, top: 13.2 } },
      description: 'Day 9: Sant Feliu de Guíxols to Palamós.',
      gallery: [],
    },
    {
      id: 'costa-brava-14-days-day-10',
      routeFrom: 'Palamós',
      routeTo: 'Sant Feliu de Guíxols',
      day: 10,
      mapPin: { desktop: { left: 81.2, top: 21.3 }, mobile: { left: 81.2, top: 21.3 } },
      description: 'Day 10: Palamós to Sant Feliu de Guíxols.',
      gallery: [],
    },
    {
      id: 'costa-brava-14-days-day-11',
      routeFrom: 'Sant Feliu de Guíxols',
      routeTo: 'Tossa de Mar',
      day: 11,
      mapPin: { desktop: { left: 75.8, top: 28.7 }, mobile: { left: 75.8, top: 28.7 } },
      description: 'Day 11: Sant Feliu de Guíxols to Tossa de Mar.',
      gallery: [],
    },
    {
      id: 'costa-brava-14-days-day-12',
      routeFrom: 'Tossa de Mar',
      routeTo: 'Sitges',
      day: 12,
      mapPin: { desktop: { left: 13.2, top: 86.8 }, mobile: { left: 13.2, top: 86.8 } },
      description: 'Day 12: Tossa de Mar to Sitges.',
      gallery: [],
    },
    {
      id: 'costa-brava-14-days-day-13',
      routeFrom: 'Sitges',
      routeTo: 'Garraf',
      day: 13,
      mapPin: { desktop: { left: 18.9, top: 83.6 }, mobile: { left: 18.9, top: 83.6 } },
      description: 'Day 13: Sitges to Garraf.',
      gallery: [],
    },
    {
      id: 'costa-brava-14-days-day-14',
      routeFrom: 'Garraf',
      routeTo: 'Barcelona (Port Olímpic)',
      day: 14,
      mapPin: { desktop: { left: 33.7, top: 69.0 }, mobile: { left: 33.7, top: 69.0 } },
      description: 'Day 14: Garraf to Barcelona (Port Olímpic).',
      gallery: [],
    },
  ],
  map: {
    desktop: {
      image: { src: '/images/itinerary/spain/catalonia-maps/costa-brava-14-days-map.webp', alt: 'Route map' },
      width: 1350,
      height: 830,
    },
    mobile: {
      image: { src: '/images/itinerary/spain/catalonia-maps/costa-brava-14-days-map.webp', alt: 'Route map' },
      width: 1350,
      height: 830,
    },
  },
};

export default computeItineraryNumberOfDays(costaBrava14Route);
