import { computeItineraryNumberOfDays } from '@/helper/itineraryDaysHelper';
import { ItineraryRoute } from '@/types/itinerary.type';

const abacosUnhurried14Route: ItineraryRoute = {
  metaTitle: '14-Day Marsh Harbour Route | Boat4You',
  metaDesc: 'Two-week itinerary from Marsh Harbour.',
  id: 'abacos-unhurried-14-days',
  startingPoint: 'Marsh Harbour',
  otherPoints: ['Great Guana Cay', 'Green Turtle Cay', 'Hope Town'],
  cardImage: { src: '/images/itinerary/caribbeans/bahamas-itinerary/itinerary-card.webp', alt: '14-day route' },
  gallery: [],
  routeDays: [
    {
      id: 'abacos-unhurried-14-days-day-1',
      routeFrom: 'Marsh Harbour',
      routeTo: 'Hope Town',
      day: 1,
      mapPin: { desktop: { left: 86.8, top: 86.8 }, mobile: { left: 86.8, top: 86.8 } },
      description: 'Day 1: Marsh Harbour to Hope Town.',
      gallery: [{ src: '/images/itinerary/caribbeans/destinations/hope-town.webp', alt: 'Hope Town' }],
    },
    {
      id: 'abacos-unhurried-14-days-day-2',
      routeFrom: 'Hope Town',
      routeTo: 'Man-O-War Cay',
      day: 2,
      mapPin: { desktop: { left: 78.4, top: 69.2 }, mobile: { left: 78.4, top: 69.2 } },
      description: 'Day 2: Hope Town to Man-O-War Cay.',
      gallery: [],
    },
    {
      id: 'abacos-unhurried-14-days-day-3',
      routeFrom: 'Man-O-War Cay',
      routeTo: 'Great Guana Cay',
      day: 3,
      mapPin: { desktop: { left: 54.6, top: 46.7 }, mobile: { left: 54.6, top: 46.7 } },
      description: 'Day 3: Man-O-War Cay to Great Guana Cay.',
      gallery: [{ src: '/images/itinerary/caribbeans/destinations/great-guana-cay.webp', alt: 'Great Guana Cay' }],
    },
    {
      id: 'abacos-unhurried-14-days-day-4',
      routeFrom: 'Great Guana Cay',
      routeTo: 'Green Turtle Cay',
      day: 4,
      mapPin: { desktop: { left: 13.2, top: 13.2 }, mobile: { left: 13.2, top: 13.2 } },
      description: 'Day 4: Great Guana Cay to Green Turtle Cay.',
      gallery: [{ src: '/images/itinerary/caribbeans/destinations/green-turtle-cay.webp', alt: 'Green Turtle Cay' }],
    },
    {
      id: 'abacos-unhurried-14-days-day-5',
      routeFrom: 'Green Turtle Cay',
      routeTo: 'Great Guana Cay',
      day: 5,
      mapPin: { desktop: { left: 54.6, top: 46.7 }, mobile: { left: 54.6, top: 46.7 } },
      description: 'Day 5: Green Turtle Cay to Great Guana Cay.',
      gallery: [{ src: '/images/itinerary/caribbeans/destinations/great-guana-cay.webp', alt: 'Great Guana Cay' }],
    },
    {
      id: 'abacos-unhurried-14-days-day-6',
      routeFrom: 'Great Guana Cay',
      routeTo: 'Marsh Harbour',
      day: 6,
      mapPin: { desktop: { left: 66.7, top: 85.2 }, mobile: { left: 66.7, top: 85.2 } },
      description: 'Day 6: Great Guana Cay to Marsh Harbour.',
      gallery: [{ src: '/images/itinerary/caribbeans/destinations/marsh-harbour.webp', alt: 'Marsh Harbour' }],
    },
    {
      id: 'abacos-unhurried-14-days-day-7',
      routeFrom: 'Marsh Harbour',
      routeTo: 'Hope Town',
      day: 7,
      mapPin: { desktop: { left: 86.8, top: 86.8 }, mobile: { left: 86.8, top: 86.8 } },
      description: 'Day 7: Marsh Harbour to Hope Town.',
      gallery: [{ src: '/images/itinerary/caribbeans/destinations/hope-town.webp', alt: 'Hope Town' }],
    },
    {
      id: 'abacos-unhurried-14-days-day-8',
      routeFrom: 'Hope Town',
      routeTo: 'Man-O-War Cay',
      day: 8,
      mapPin: { desktop: { left: 78.4, top: 69.2 }, mobile: { left: 78.4, top: 69.2 } },
      description: 'Day 8: Hope Town to Man-O-War Cay.',
      gallery: [],
    },
    {
      id: 'abacos-unhurried-14-days-day-9',
      routeFrom: 'Man-O-War Cay',
      routeTo: 'Great Guana Cay',
      day: 9,
      mapPin: { desktop: { left: 54.6, top: 46.7 }, mobile: { left: 54.6, top: 46.7 } },
      description: 'Day 9: Man-O-War Cay to Great Guana Cay.',
      gallery: [{ src: '/images/itinerary/caribbeans/destinations/great-guana-cay.webp', alt: 'Great Guana Cay' }],
    },
    {
      id: 'abacos-unhurried-14-days-day-10',
      routeFrom: 'Great Guana Cay',
      routeTo: 'Green Turtle Cay',
      day: 10,
      mapPin: { desktop: { left: 13.2, top: 13.2 }, mobile: { left: 13.2, top: 13.2 } },
      description: 'Day 10: Great Guana Cay to Green Turtle Cay.',
      gallery: [{ src: '/images/itinerary/caribbeans/destinations/green-turtle-cay.webp', alt: 'Green Turtle Cay' }],
    },
    {
      id: 'abacos-unhurried-14-days-day-11',
      routeFrom: 'Green Turtle Cay',
      routeTo: 'Man-O-War Cay',
      day: 11,
      mapPin: { desktop: { left: 78.4, top: 69.2 }, mobile: { left: 78.4, top: 69.2 } },
      description: 'Day 11: Green Turtle Cay to Man-O-War Cay.',
      gallery: [],
    },
    {
      id: 'abacos-unhurried-14-days-day-12',
      routeFrom: 'Man-O-War Cay',
      routeTo: 'Hope Town',
      day: 12,
      mapPin: { desktop: { left: 86.8, top: 86.8 }, mobile: { left: 86.8, top: 86.8 } },
      description: 'Day 12: Man-O-War Cay to Hope Town.',
      gallery: [{ src: '/images/itinerary/caribbeans/destinations/hope-town.webp', alt: 'Hope Town' }],
    },
    {
      id: 'abacos-unhurried-14-days-day-13',
      routeFrom: 'Hope Town',
      routeTo: 'Marsh Harbour',
      day: 13,
      mapPin: { desktop: { left: 66.7, top: 85.2 }, mobile: { left: 66.7, top: 85.2 } },
      description: 'Day 13: Hope Town to Marsh Harbour.',
      gallery: [{ src: '/images/itinerary/caribbeans/destinations/marsh-harbour.webp', alt: 'Marsh Harbour' }],
    },
    {
      id: 'abacos-unhurried-14-days-day-14',
      routeFrom: 'Marsh Harbour',
      routeTo: 'Marsh Harbour',
      day: 14,
      mapPin: { desktop: { left: 66.7, top: 85.2 }, mobile: { left: 66.7, top: 85.2 } },
      description: 'Day 14: Marsh Harbour to Marsh Harbour.',
      gallery: [{ src: '/images/itinerary/caribbeans/destinations/marsh-harbour.webp', alt: 'Marsh Harbour' }],
    },
  ],
  map: {
    desktop: {
      image: { src: '/images/itinerary/caribbeans/bahamas-maps/abacos-unhurried-14-days-map.webp', alt: 'Route map' },
      width: 1350,
      height: 915,
    },
    mobile: {
      image: { src: '/images/itinerary/caribbeans/bahamas-maps/abacos-unhurried-14-days-map.webp', alt: 'Route map' },
      width: 1350,
      height: 915,
    },
  },
};

export default computeItineraryNumberOfDays(abacosUnhurried14Route);
