import { computeItineraryNumberOfDays } from '@/helper/itineraryDaysHelper';
import { ItineraryRoute } from '@/types/itinerary.type';

const seychellesExplorer14Route: ItineraryRoute = {
  metaTitle: '14-Day Eden Island (Mahe) Route | Boat4You',
  metaDesc: '14-day itinerary from Eden Island (Mahe).',
  id: 'seychelles-explorer-14-days',
  startingPoint: 'Eden Island (Mahe)',
  otherPoints: ['Silhouette', 'Praslin (Baie Sainte Anne)', 'Felicite'],
  cardImage: { src: '/images/itinerary/seychelles/seychelles-photos/mahe-eden-island.webp', alt: 'Seychelles' },
  gallery: [],
  routeDays: [
    {
      id: 'seychelles-explorer-14-days-day-1',
      routeFrom: 'Eden Island (Mahe)',
      routeTo: 'Sainte Anne',
      day: 1,
      mapPin: { desktop: { left: 41.3, top: 81.1 }, mobile: { left: 41.3, top: 81.1 } },
      description: 'Day 1: Eden Island (Mahe) to Sainte Anne.',
      gallery: [],
    },
    {
      id: 'seychelles-explorer-14-days-day-2',
      routeFrom: 'Sainte Anne',
      routeTo: 'Baie Ternay',
      day: 2,
      mapPin: { desktop: { left: 27.5, top: 86.8 }, mobile: { left: 27.5, top: 86.8 } },
      description: 'Day 2: Sainte Anne to Baie Ternay.',
      gallery: [],
    },
    {
      id: 'seychelles-explorer-14-days-day-3',
      routeFrom: 'Baie Ternay',
      routeTo: 'Silhouette',
      day: 3,
      mapPin: { desktop: { left: 13.2, top: 58.9 }, mobile: { left: 13.2, top: 58.9 } },
      description: 'Day 3: Baie Ternay to Silhouette.',
      gallery: [{ src: '/images/itinerary/seychelles/seychelles-photos/silhouette-island.webp', alt: 'Silhouette' }],
    },
    {
      id: 'seychelles-explorer-14-days-day-4',
      routeFrom: 'Silhouette',
      routeTo: 'Cousin',
      day: 4,
      mapPin: { desktop: { left: 59.1, top: 33.2 }, mobile: { left: 59.1, top: 33.2 } },
      description: 'Day 4: Silhouette to Cousin.',
      gallery: [],
    },
    {
      id: 'seychelles-explorer-14-days-day-5',
      routeFrom: 'Cousin',
      routeTo: 'Praslin (Baie Sainte Anne)',
      day: 5,
      mapPin: { desktop: { left: 69.9, top: 37.0 }, mobile: { left: 69.9, top: 37.0 } },
      description: 'Day 5: Cousin to Praslin (Baie Sainte Anne).',
      gallery: [
        {
          src: '/images/itinerary/seychelles/seychelles-photos/praslin-anse-lazio.webp',
          alt: 'Praslin (Baie Sainte Anne)',
        },
      ],
    },
    {
      id: 'seychelles-explorer-14-days-day-6',
      routeFrom: 'Praslin (Baie Sainte Anne)',
      routeTo: 'Aride',
      day: 6,
      mapPin: { desktop: { left: 59.5, top: 13.2 }, mobile: { left: 59.5, top: 13.2 } },
      description: 'Day 6: Praslin (Baie Sainte Anne) to Aride.',
      gallery: [],
    },
    {
      id: 'seychelles-explorer-14-days-day-7',
      routeFrom: 'Aride',
      routeTo: 'Curieuse',
      day: 7,
      mapPin: { desktop: { left: 66.3, top: 25.2 }, mobile: { left: 66.3, top: 25.2 } },
      description: 'Day 7: Aride to Curieuse.',
      gallery: [{ src: '/images/itinerary/seychelles/seychelles-photos/curieuse-tortoises.webp', alt: 'Curieuse' }],
    },
    {
      id: 'seychelles-explorer-14-days-day-8',
      routeFrom: 'Curieuse',
      routeTo: 'Anse Lazio',
      day: 8,
      mapPin: { desktop: { left: 62.9, top: 26.9 }, mobile: { left: 62.9, top: 26.9 } },
      description: 'Day 8: Curieuse to Anse Lazio.',
      gallery: [{ src: '/images/itinerary/seychelles/seychelles-photos/praslin-anse-lazio.webp', alt: 'Anse Lazio' }],
    },
    {
      id: 'seychelles-explorer-14-days-day-9',
      routeFrom: 'Anse Lazio',
      routeTo: 'La Digue',
      day: 9,
      mapPin: { desktop: { left: 77.6, top: 38.0 }, mobile: { left: 77.6, top: 38.0 } },
      description: 'Day 9: Anse Lazio to La Digue.',
      gallery: [
        { src: '/images/itinerary/seychelles/seychelles-photos/la-digue-anse-source-d-argent.webp', alt: 'La Digue' },
      ],
    },
    {
      id: 'seychelles-explorer-14-days-day-10',
      routeFrom: 'La Digue',
      routeTo: 'Marianne',
      day: 10,
      mapPin: { desktop: { left: 86.8, top: 36.3 }, mobile: { left: 86.8, top: 36.3 } },
      description: 'Day 10: La Digue to Marianne.',
      gallery: [],
    },
    {
      id: 'seychelles-explorer-14-days-day-11',
      routeFrom: 'Marianne',
      routeTo: 'Felicite',
      day: 11,
      mapPin: { desktop: { left: 81.8, top: 31.5 }, mobile: { left: 81.8, top: 31.5 } },
      description: 'Day 11: Marianne to Felicite.',
      gallery: [],
    },
    {
      id: 'seychelles-explorer-14-days-day-12',
      routeFrom: 'Felicite',
      routeTo: 'Grande Soeur',
      day: 12,
      mapPin: { desktop: { left: 81.7, top: 26.9 }, mobile: { left: 81.7, top: 26.9 } },
      description: 'Day 12: Felicite to Grande Soeur.',
      gallery: [],
    },
    {
      id: 'seychelles-explorer-14-days-day-13',
      routeFrom: 'Grande Soeur',
      routeTo: 'Ile Cocos',
      day: 13,
      mapPin: { desktop: { left: 82.0, top: 32.4 }, mobile: { left: 82.0, top: 32.4 } },
      description: 'Day 13: Grande Soeur to Ile Cocos.',
      gallery: [],
    },
    {
      id: 'seychelles-explorer-14-days-day-14',
      routeFrom: 'Ile Cocos',
      routeTo: 'Eden Island (Mahe)',
      day: 14,
      mapPin: { desktop: { left: 38.4, top: 85.1 }, mobile: { left: 38.4, top: 85.1 } },
      description: 'Day 14: Ile Cocos to Eden Island (Mahe).',
      gallery: [
        { src: '/images/itinerary/seychelles/seychelles-photos/mahe-eden-island.webp', alt: 'Eden Island (Mahe)' },
      ],
    },
  ],
  map: {
    desktop: {
      image: {
        src: '/images/itinerary/seychelles/seychelles-maps/seychelles-explorer-14-days-map.webp',
        alt: 'Seychelles route map',
      },
      width: 1350,
      height: 871,
    },
    mobile: {
      image: {
        src: '/images/itinerary/seychelles/seychelles-maps/seychelles-explorer-14-days-map.webp',
        alt: 'Seychelles route map',
      },
      width: 1350,
      height: 871,
    },
  },
};

export default computeItineraryNumberOfDays(seychellesExplorer14Route);
