export const _boatNames = [
  'Libertas DS',
  'Big Blue Yacht',
  'Ocean Dream',
  'Sea Breeze',
  'White Pearl',
  'Blue Horizon',
  'Majestic Wave',
  'Sunset Voyager',
  'Golden Tide',
  'Freedom 45',
  'Azure Spirit',
  'Coral Queen',
  'Wind Whisperer',
  'Silver Cloud',
  'Starlight One',
  'Island Escape',
  'Nautical Star',
  'Voyager X',
  'Pacific Grace',
  'Eclipse 60',
  'Aurora Bay',
  'Sea Whisper',
  'Mediterraneo',
  'Atlantic Belle',
  'Liberty Sail',
  'Crimson Tide',
  'Neptune’s Jewel',
  'Southern Wind',
  'Crystal Lagoon',
  'Serenity 50',
];

export const _boatModels = [
  'Lagoon 450 F',
  'Sunseeker Manhattan',
  'Bali 4.6',
  'Beneteau Oceanis 45',
  'Princess V50',
  'Hanse 458',
  'Jeanneau 54',
  'Lagoon 46',
  'Bavaria Cruiser 51',
  'Dufour 470',
  'Fountaine Pajot Astrea 42',
  'Bali Catspace',
  'Beneteau First 53',
  'Jeanneau Sun Odyssey 490',
  'Lagoon 50',
  'Nautitech 46 Fly',
  'Hanse 588',
  'Bavaria C50',
  'Dufour 530',
  'Fountaine Pajot Tanna 47',
  'Beneteau Oceanis 51.1',
  'Lagoon 42',
  'Jeanneau Yachts 60',
  'Princess F55',
  'Sun Odyssey 440',
  'Bavaria Cruiser 46',
  'Nautitech Open 40',
  'Lagoon 450 F',
  'Fountaine Pajot Elba 45',
  'Beneteau Oceanis 38.1',
];
