import { computeItineraryNumberOfDays } from '@/helper/itineraryDaysHelper';
import { ItineraryRoute } from '@/types/itinerary.type';

const grenadinesExplorer14Route: ItineraryRoute = {
  metaTitle: '14-Day Port Louis Marina Route | Boat4You',
  metaDesc: 'Two-week itinerary from Port Louis Marina.',
  id: 'grenadines-explorer-14-days',
  startingPoint: 'Port Louis Marina',
  otherPoints: ['Dragon Bay, Grenada', 'Salt Whistle Bay, Mayreau', 'Sandy Island, Carriacou'],
  cardImage: { src: '/images/itinerary/caribbeans/grenada-itinerary/itinerary-card.webp', alt: '14-day route' },
  gallery: [],
  routeDays: [
    {
      id: 'grenadines-explorer-14-days-day-1',
      routeFrom: 'Port Louis Marina',
      routeTo: 'Dragon Bay, Grenada',
      day: 1,
      mapPin: { desktop: { left: 13.8, top: 83.2 }, mobile: { left: 13.8, top: 83.2 } },
      description: 'Day 1: Port Louis Marina to Dragon Bay, Grenada.',
      gallery: [],
    },
    {
      id: 'grenadines-explorer-14-days-day-2',
      routeFrom: 'Dragon Bay, Grenada',
      routeTo: 'Tyrell Bay, Carriacou',
      day: 2,
      mapPin: { desktop: { left: 62.8, top: 36.6 }, mobile: { left: 62.8, top: 36.6 } },
      description: 'Day 2: Dragon Bay, Grenada to Tyrell Bay, Carriacou.',
      gallery: [],
    },
    {
      id: 'grenadines-explorer-14-days-day-3',
      routeFrom: 'Tyrell Bay, Carriacou',
      routeTo: 'Sandy Island, Carriacou',
      day: 3,
      mapPin: { desktop: { left: 60.7, top: 32.0 }, mobile: { left: 60.7, top: 32.0 } },
      description: 'Day 3: Tyrell Bay, Carriacou to Sandy Island, Carriacou.',
      gallery: [],
    },
    {
      id: 'grenadines-explorer-14-days-day-4',
      routeFrom: 'Sandy Island, Carriacou',
      routeTo: 'Salt Whistle Bay, Mayreau',
      day: 4,
      mapPin: { desktop: { left: 77.5, top: 13.2 }, mobile: { left: 77.5, top: 13.2 } },
      description: 'Day 4: Sandy Island, Carriacou to Salt Whistle Bay, Mayreau.',
      gallery: [],
    },
    {
      id: 'grenadines-explorer-14-days-day-5',
      routeFrom: 'Salt Whistle Bay, Mayreau',
      routeTo: 'Tobago Cays',
      day: 5,
      mapPin: { desktop: { left: 86.8, top: 14.6 }, mobile: { left: 86.8, top: 14.6 } },
      description: 'Day 5: Salt Whistle Bay, Mayreau to Tobago Cays.',
      gallery: [],
    },
    {
      id: 'grenadines-explorer-14-days-day-6',
      routeFrom: 'Tobago Cays',
      routeTo: 'Tobago Cays',
      day: 6,
      mapPin: { desktop: { left: 86.8, top: 14.6 }, mobile: { left: 86.8, top: 14.6 } },
      description: 'Day 6: Tobago Cays to Tobago Cays.',
      gallery: [],
    },
    {
      id: 'grenadines-explorer-14-days-day-7',
      routeFrom: 'Tobago Cays',
      routeTo: 'Salt Whistle Bay, Mayreau',
      day: 7,
      mapPin: { desktop: { left: 77.5, top: 13.2 }, mobile: { left: 77.5, top: 13.2 } },
      description: 'Day 7: Tobago Cays to Salt Whistle Bay, Mayreau.',
      gallery: [],
    },
    {
      id: 'grenadines-explorer-14-days-day-8',
      routeFrom: 'Salt Whistle Bay, Mayreau',
      routeTo: 'Tyrell Bay, Carriacou',
      day: 8,
      mapPin: { desktop: { left: 62.8, top: 36.6 }, mobile: { left: 62.8, top: 36.6 } },
      description: 'Day 8: Salt Whistle Bay, Mayreau to Tyrell Bay, Carriacou.',
      gallery: [],
    },
    {
      id: 'grenadines-explorer-14-days-day-9',
      routeFrom: 'Tyrell Bay, Carriacou',
      routeTo: 'Sandy Island, Carriacou',
      day: 9,
      mapPin: { desktop: { left: 60.7, top: 32.0 }, mobile: { left: 60.7, top: 32.0 } },
      description: 'Day 9: Tyrell Bay, Carriacou to Sandy Island, Carriacou.',
      gallery: [],
    },
    {
      id: 'grenadines-explorer-14-days-day-10',
      routeFrom: 'Sandy Island, Carriacou',
      routeTo: 'Tyrell Bay, Carriacou',
      day: 10,
      mapPin: { desktop: { left: 62.8, top: 36.6 }, mobile: { left: 62.8, top: 36.6 } },
      description: 'Day 10: Sandy Island, Carriacou to Tyrell Bay, Carriacou.',
      gallery: [],
    },
    {
      id: 'grenadines-explorer-14-days-day-11',
      routeFrom: 'Tyrell Bay, Carriacou',
      routeTo: 'Dragon Bay, Grenada',
      day: 11,
      mapPin: { desktop: { left: 13.8, top: 83.2 }, mobile: { left: 13.8, top: 83.2 } },
      description: 'Day 11: Tyrell Bay, Carriacou to Dragon Bay, Grenada.',
      gallery: [],
    },
    {
      id: 'grenadines-explorer-14-days-day-12',
      routeFrom: 'Dragon Bay, Grenada',
      routeTo: 'St. George’s, Grenada',
      day: 12,
      mapPin: { desktop: { left: 27.3, top: 78.6 }, mobile: { left: 27.3, top: 78.6 } },
      description: 'Day 12: Dragon Bay, Grenada to St. George’s, Grenada.',
      gallery: [],
    },
    {
      id: 'grenadines-explorer-14-days-day-13',
      routeFrom: 'St. George’s, Grenada',
      routeTo: 'Dragon Bay, Grenada',
      day: 13,
      mapPin: { desktop: { left: 13.8, top: 83.2 }, mobile: { left: 13.8, top: 83.2 } },
      description: 'Day 13: St. George’s, Grenada to Dragon Bay, Grenada.',
      gallery: [],
    },
    {
      id: 'grenadines-explorer-14-days-day-14',
      routeFrom: 'Dragon Bay, Grenada',
      routeTo: 'Port Louis Marina',
      day: 14,
      mapPin: { desktop: { left: 13.2, top: 86.8 }, mobile: { left: 13.2, top: 86.8 } },
      description: 'Day 14: Dragon Bay, Grenada to Port Louis Marina.',
      gallery: [],
    },
  ],
  map: {
    desktop: {
      image: {
        src: '/images/itinerary/caribbeans/grenada-maps/grenadines-explorer-14-days-map.webp',
        alt: 'Route map',
      },
      width: 1350,
      height: 2020,
    },
    mobile: {
      image: {
        src: '/images/itinerary/caribbeans/grenada-maps/grenadines-explorer-14-days-map.webp',
        alt: 'Route map',
      },
      width: 1350,
      height: 2020,
    },
  },
};

export default computeItineraryNumberOfDays(grenadinesExplorer14Route);
