import { computeItineraryNumberOfDays } from '@/helper/itineraryDaysHelper';
import { ItineraryRoute } from '@/types/itinerary.type';

const canalDuMidi14Route: ItineraryRoute = {
  metaTitle: '14-Day Port Cassafieres Route | Boat4You',
  metaDesc: '14-day itinerary from Port Cassafieres.',
  id: 'canal-du-midi-14-days',
  startingPoint: 'Port Cassafieres',
  otherPoints: ['Beziers', 'Carcassonne', 'Castelnaudary'],
  cardImage: { src: '/images/destinations/france.webp', alt: 'French Canals' },
  gallery: [],
  routeDays: [
    {
      id: 'canal-du-midi-14-days-day-1',
      routeFrom: 'Port Cassafieres',
      routeTo: 'Agde',
      day: 1,
      mapPin: { desktop: { left: 83.7, top: 34.8 }, mobile: { left: 83.7, top: 34.8 } },
      description: 'Day 1: Port Cassafieres to Agde.',
      gallery: [],
    },
    {
      id: 'canal-du-midi-14-days-day-2',
      routeFrom: 'Agde',
      routeTo: 'Beziers',
      day: 2,
      mapPin: { desktop: { left: 72.1, top: 19.4 }, mobile: { left: 72.1, top: 19.4 } },
      description: 'Day 2: Agde to Beziers.',
      gallery: [],
    },
    {
      id: 'canal-du-midi-14-days-day-3',
      routeFrom: 'Beziers',
      routeTo: 'Capestang',
      day: 3,
      mapPin: { desktop: { left: 64.2, top: 26.1 }, mobile: { left: 64.2, top: 26.1 } },
      description: 'Day 3: Beziers to Capestang.',
      gallery: [],
    },
    {
      id: 'canal-du-midi-14-days-day-4',
      routeFrom: 'Capestang',
      routeTo: 'Le Somail',
      day: 4,
      mapPin: { desktop: { left: 55.7, top: 63.1 }, mobile: { left: 55.7, top: 63.1 } },
      description: 'Day 4: Capestang to Le Somail.',
      gallery: [],
    },
    {
      id: 'canal-du-midi-14-days-day-5',
      routeFrom: 'Le Somail',
      routeTo: 'Homps',
      day: 5,
      mapPin: { desktop: { left: 49.0, top: 57.5 }, mobile: { left: 49.0, top: 57.5 } },
      description: 'Day 5: Le Somail to Homps.',
      gallery: [],
    },
    {
      id: 'canal-du-midi-14-days-day-6',
      routeFrom: 'Homps',
      routeTo: 'Trebes',
      day: 6,
      mapPin: { desktop: { left: 36.1, top: 86.8 }, mobile: { left: 36.1, top: 86.8 } },
      description: 'Day 6: Homps to Trebes.',
      gallery: [],
    },
    {
      id: 'canal-du-midi-14-days-day-7',
      routeFrom: 'Trebes',
      routeTo: 'Carcassonne',
      day: 7,
      mapPin: { desktop: { left: 31.7, top: 85.2 }, mobile: { left: 31.7, top: 85.2 } },
      description: 'Day 7: Trebes to Carcassonne.',
      gallery: [],
    },
    {
      id: 'canal-du-midi-14-days-day-8',
      routeFrom: 'Carcassonne',
      routeTo: 'Bram',
      day: 8,
      mapPin: { desktop: { left: 20.7, top: 69.3 }, mobile: { left: 20.7, top: 69.3 } },
      description: 'Day 8: Carcassonne to Bram.',
      gallery: [],
    },
    {
      id: 'canal-du-midi-14-days-day-9',
      routeFrom: 'Bram',
      routeTo: 'Castelnaudary',
      day: 9,
      mapPin: { desktop: { left: 13.2, top: 31.2 }, mobile: { left: 13.2, top: 31.2 } },
      description: 'Day 9: Bram to Castelnaudary.',
      gallery: [],
    },
    {
      id: 'canal-du-midi-14-days-day-10',
      routeFrom: 'Castelnaudary',
      routeTo: 'Carcassonne',
      day: 10,
      mapPin: { desktop: { left: 31.7, top: 85.2 }, mobile: { left: 31.7, top: 85.2 } },
      description: 'Day 10: Castelnaudary to Carcassonne.',
      gallery: [],
    },
    {
      id: 'canal-du-midi-14-days-day-11',
      routeFrom: 'Carcassonne',
      routeTo: 'Homps',
      day: 11,
      mapPin: { desktop: { left: 49.0, top: 57.5 }, mobile: { left: 49.0, top: 57.5 } },
      description: 'Day 11: Carcassonne to Homps.',
      gallery: [],
    },
    {
      id: 'canal-du-midi-14-days-day-12',
      routeFrom: 'Homps',
      routeTo: 'Capestang',
      day: 12,
      mapPin: { desktop: { left: 64.2, top: 26.1 }, mobile: { left: 64.2, top: 26.1 } },
      description: 'Day 12: Homps to Capestang.',
      gallery: [],
    },
    {
      id: 'canal-du-midi-14-days-day-13',
      routeFrom: 'Capestang',
      routeTo: 'Marseillan',
      day: 13,
      mapPin: { desktop: { left: 86.8, top: 13.2 }, mobile: { left: 86.8, top: 13.2 } },
      description: 'Day 13: Capestang to Marseillan.',
      gallery: [],
    },
    {
      id: 'canal-du-midi-14-days-day-14',
      routeFrom: 'Marseillan',
      routeTo: 'Port Cassafieres',
      day: 14,
      mapPin: { desktop: { left: 79.4, top: 45.1 }, mobile: { left: 79.4, top: 45.1 } },
      description: 'Day 14: Marseillan to Port Cassafieres.',
      gallery: [],
    },
  ],
  map: {
    desktop: {
      image: {
        src: '/images/itinerary/france/french-canals-maps/canal-du-midi-14-days-map.webp',
        alt: 'French Canals route map',
      },
      width: 1350,
      height: 168,
    },
    mobile: {
      image: {
        src: '/images/itinerary/france/french-canals-maps/canal-du-midi-14-days-map.webp',
        alt: 'French Canals route map',
      },
      width: 1350,
      height: 168,
    },
  },
};

export default computeItineraryNumberOfDays(canalDuMidi14Route);
