/**
 * Normalised catalogue name (normalizeDestinationName) → key under
 * `landing.names` / `landing.in` for the REGIONS a destination landing can
 * be about. Countries and the two popular regions go through
 * DESTINATION_KEY_BY_LABEL (home.destinationsSection); marinas / bases keep
 * their catalogue name, wrapped in the locale's `landing.inFallback`.
 * Generated with the translations in messages/<locale>/landing.json.
 */
export const REGION_KEY_BY_NAME: Record<string, string> = {
  'dubrovnik region': 'dubrovnikRegion',
  'istria kvarner': 'istriaKvarner',
  kornati: 'kornati',
  zadar: 'zadar',
  sibenik: 'sibenik',
  'dubrovnik montenegro': 'dubrovnikMontenegro',
  'athens saronic gulf': 'athensSaronicGulf',
  'athens area saronic peloponese': 'athensSaronicPeloponnese',
  cyclades: 'cyclades',
  dodecanese: 'dodecanese',
  'east macedonia and thrace': 'eastMacedoniaThrace',
  'north east aegean': 'northEastAegean',
  'northern greece aegean': 'northernGreeceAegean',
  paros: 'paros',
  'skiathos sporades volos': 'skiathosSporadesVolos',
  'south peloponnese': 'southPeloponnese',
  sporades: 'sporades',
  apulia: 'apulia',
  calabria: 'calabria',
  campania: 'campania',
  'gulf of taranto': 'gulfOfTaranto',
  'italian adriatic': 'italianAdriatic',
  liguria: 'liguria',
  'liguria toscana': 'liguriaTuscany',
  sardinia: 'sardinia',
  'sardinia corsica': 'sardiniaCorsica',
  sicily: 'sicily',
  tuscany: 'tuscany',
  veneto: 'veneto',
  'venice lagoon': 'veniceLagoon',
  'tyrrhenian sea': 'tyrrhenianSea',
  alicante: 'alicante',
  andalusia: 'andalusia',
  'balearic islands': 'balearicIslands',
  'canary islands': 'canaryIslands',
  catalonia: 'catalonia',
  galicia: 'galicia',
  ibiza: 'ibiza',
  mallorca: 'mallorca',
  menorca: 'menorca',
  murcia: 'murcia',
  valencia: 'valencia',
  bretagne: 'brittany',
  corsica: 'corsica',
  'french riviera cote d azur': 'frenchRiviera',
  'normandy bretagne': 'normandyBrittany',
  'poitou charentes': 'poitouCharentes',
  'provence alpes cote d azur': 'provenceAlpesCoteDAzur',
  aegean: 'aegean',
  bodrum: 'bodrum',
  'istanbul bosphorus': 'istanbulBosphorus',
  izmir: 'izmir',
  'marmaris fethiye gocek': 'marmarisFethiyeGocek',
  mediterranean: 'mediterranean',
  'abaco islands': 'abacoIslands',
  'new providence': 'newProvidence',
  mahe: 'mahe',
  'british virgin islands': 'britishVirginIslands',
};
