import { computeItineraryNumberOfDays } from '@/helper/itineraryDaysHelper';
import { ItineraryRoute } from '@/types/itinerary.type';

const rivieraEsterel14Route: ItineraryRoute = {
  metaTitle: '14-Day Cannes Route | Boat4You',
  metaDesc: '14-day itinerary from Cannes.',
  id: 'riviera-esterel-14-days',
  startingPoint: 'Cannes',
  otherPoints: ['Monaco', 'Porquerolles', 'Saint-Tropez'],
  cardImage: { src: '/images/destinations/france.webp', alt: "Côte d'Azur" },
  gallery: [],
  routeDays: [
    {
      id: 'riviera-esterel-14-days-day-1',
      routeFrom: 'Cannes',
      routeTo: 'Antibes',
      day: 1,
      mapPin: { desktop: { left: 69.2, top: 28.3 }, mobile: { left: 69.2, top: 28.3 } },
      description: 'Day 1: Cannes to Antibes.',
      gallery: [],
    },
    {
      id: 'riviera-esterel-14-days-day-2',
      routeFrom: 'Antibes',
      routeTo: 'Villefranche-sur-Mer',
      day: 2,
      mapPin: { desktop: { left: 80.1, top: 16.5 }, mobile: { left: 80.1, top: 16.5 } },
      description: 'Day 2: Antibes to Villefranche-sur-Mer.',
      gallery: [],
    },
    {
      id: 'riviera-esterel-14-days-day-3',
      routeFrom: 'Villefranche-sur-Mer',
      routeTo: 'Monaco',
      day: 3,
      mapPin: { desktop: { left: 86.8, top: 13.2 }, mobile: { left: 86.8, top: 13.2 } },
      description: 'Day 3: Villefranche-sur-Mer to Monaco.',
      gallery: [],
    },
    {
      id: 'riviera-esterel-14-days-day-4',
      routeFrom: 'Monaco',
      routeTo: 'Antibes',
      day: 4,
      mapPin: { desktop: { left: 69.2, top: 28.3 }, mobile: { left: 69.2, top: 28.3 } },
      description: 'Day 4: Monaco to Antibes.',
      gallery: [],
    },
    {
      id: 'riviera-esterel-14-days-day-5',
      routeFrom: 'Antibes',
      routeTo: 'Iles de Lerins',
      day: 5,
      mapPin: { desktop: { left: 64.1, top: 34.9 }, mobile: { left: 64.1, top: 34.9 } },
      description: 'Day 5: Antibes to Iles de Lerins.',
      gallery: [],
    },
    {
      id: 'riviera-esterel-14-days-day-6',
      routeFrom: 'Iles de Lerins',
      routeTo: 'Agay',
      day: 6,
      mapPin: { desktop: { left: 52.8, top: 43.7 }, mobile: { left: 52.8, top: 43.7 } },
      description: 'Day 6: Iles de Lerins to Agay.',
      gallery: [],
    },
    {
      id: 'riviera-esterel-14-days-day-7',
      routeFrom: 'Agay',
      routeTo: 'Saint-Raphael',
      day: 7,
      mapPin: { desktop: { left: 47.4, top: 44.8 }, mobile: { left: 47.4, top: 44.8 } },
      description: 'Day 7: Agay to Saint-Raphael.',
      gallery: [],
    },
    {
      id: 'riviera-esterel-14-days-day-8',
      routeFrom: 'Saint-Raphael',
      routeTo: 'Saint-Tropez',
      day: 8,
      mapPin: { desktop: { left: 39.7, top: 59.7 }, mobile: { left: 39.7, top: 59.7 } },
      description: 'Day 8: Saint-Raphael to Saint-Tropez.',
      gallery: [],
    },
    {
      id: 'riviera-esterel-14-days-day-9',
      routeFrom: 'Saint-Tropez',
      routeTo: 'Port Grimaud',
      day: 9,
      mapPin: { desktop: { left: 36.1, top: 59.6 }, mobile: { left: 36.1, top: 59.6 } },
      description: 'Day 9: Saint-Tropez to Port Grimaud.',
      gallery: [],
    },
    {
      id: 'riviera-esterel-14-days-day-10',
      routeFrom: 'Port Grimaud',
      routeTo: 'Cavalaire',
      day: 10,
      mapPin: { desktop: { left: 33.1, top: 69.9 }, mobile: { left: 33.1, top: 69.9 } },
      description: 'Day 10: Port Grimaud to Cavalaire.',
      gallery: [],
    },
    {
      id: 'riviera-esterel-14-days-day-11',
      routeFrom: 'Cavalaire',
      routeTo: 'Le Lavandou',
      day: 11,
      mapPin: { desktop: { left: 23.4, top: 73.3 }, mobile: { left: 23.4, top: 73.3 } },
      description: 'Day 11: Cavalaire to Le Lavandou.',
      gallery: [],
    },
    {
      id: 'riviera-esterel-14-days-day-12',
      routeFrom: 'Le Lavandou',
      routeTo: 'Port-Cros',
      day: 12,
      mapPin: { desktop: { left: 24.3, top: 86.1 }, mobile: { left: 24.3, top: 86.1 } },
      description: 'Day 12: Le Lavandou to Port-Cros.',
      gallery: [],
    },
    {
      id: 'riviera-esterel-14-days-day-13',
      routeFrom: 'Port-Cros',
      routeTo: 'Porquerolles',
      day: 13,
      mapPin: { desktop: { left: 13.2, top: 86.8 }, mobile: { left: 13.2, top: 86.8 } },
      description: 'Day 13: Port-Cros to Porquerolles.',
      gallery: [],
    },
    {
      id: 'riviera-esterel-14-days-day-14',
      routeFrom: 'Porquerolles',
      routeTo: 'Cannes',
      day: 14,
      mapPin: { desktop: { left: 62.4, top: 32.0 }, mobile: { left: 62.4, top: 32.0 } },
      description: 'Day 14: Porquerolles to Cannes.',
      gallery: [],
    },
  ],
  map: {
    desktop: {
      image: {
        src: '/images/itinerary/france/cote-azur-maps/riviera-esterel-14-days-map.webp',
        alt: "Côte d'Azur route map",
      },
      width: 1350,
      height: 1116,
    },
    mobile: {
      image: {
        src: '/images/itinerary/france/cote-azur-maps/riviera-esterel-14-days-map.webp',
        alt: "Côte d'Azur route map",
      },
      width: 1350,
      height: 1116,
    },
  },
};

export default computeItineraryNumberOfDays(rivieraEsterel14Route);
